//
//     Generated by class-dump 3.5b1 (64 bit) (Debug version compiled Dec  3 2019 19:59:57).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Contacts/CNContact.h>

@interface CNContact (Additions)
- (BOOL)hasEmailAddress:(id)arg1;	// IMP=0x0000000000047f55
@end

