//
//     Generated by class-dump 3.5b1 (64 bit) (Debug version compiled Dec  3 2019 19:59:57).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class MCActivityMonitor, NSProgress;

@interface MCActivityUpdater : NSObject
{
    BOOL _valid;	// 8 = 0x8
    MCActivityMonitor *_monitor;	// 16 = 0x10
    NSProgress *_progress;	// 24 = 0x18
}

@property(nonatomic) BOOL valid; // @synthesize valid=_valid;
@property(retain, nonatomic) NSProgress *progress; // @synthesize progress=_progress;
@property(retain, nonatomic) MCActivityMonitor *monitor; // @synthesize monitor=_monitor;
// - (void).cxx_destruct;	// IMP=0x000000000003a419
- (void)invalidate;	// IMP=0x000000000003a281
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;	// IMP=0x000000000003a0fa
- (void)dealloc;	// IMP=0x0000000000039fff
- (id)init;	// IMP=0x0000000000039f30
- (id)initWithMonitor:(id)arg1 progress:(id)arg2;	// IMP=0x0000000000039e43

@end

