//
//     Generated by class-dump 3.5b1 (64 bit) (Debug version compiled Dec  3 2019 19:59:57).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <MailCore/MCPowerLog.h>

#import <MailCore/_MCBatchingTimerDelegate-Protocol.h>

@class NSLock, NSMutableDictionary, NSString, _MCBatchingTimer;

@interface MCAggregablePowerLog : MCPowerLog <_MCBatchingTimerDelegate>
{
    NSLock *_aggregationLock;	// 24 = 0x18
    NSMutableDictionary *_aggregatedEventDictionary;	// 32 = 0x20
    _MCBatchingTimer *_timer;	// 40 = 0x28
    id _aggregationBlock;	// 48 = 0x30
    double _aggregationPeriod;	// 56 = 0x38
}

@property(readonly, nonatomic) double aggregationPeriod; // @synthesize aggregationPeriod=_aggregationPeriod;
@property(readonly, copy, nonatomic) id aggregationBlock; // @synthesize aggregationBlock=_aggregationBlock;
// - (void).cxx_destruct;	// IMP=0x000000000008a310
- (void)batchingTimerDidFire:(id)arg1;	// IMP=0x000000000008a1e6
- (void)logEventWithDictionary:(id)arg1;	// IMP=0x000000000008a07b
- (id)initWithEventName:(id)arg1 aggregationPeriod:(double)arg2 aggregationBlock:(id)arg3;	// IMP=0x0000000000089f62

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

