//
//     Generated by class-dump 3.5b1 (64 bit) (Debug version compiled Dec  3 2019 19:59:57).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class CNAvatarCache, CNContact, CNContactStore, NSMutableDictionary, NSOperationQueue;

@interface MCContactsManager : NSObject
{
    NSMutableDictionary *_contactsCache;	// 8 = 0x8
    NSObject *_contactsCacheLock;	// 16 = 0x10
    CNAvatarCache *_avatarCache;	// 24 = 0x18
    CNContactStore *_contactStore;	// 32 = 0x20
    NSOperationQueue *_contactsUpdateQueue;	// 40 = 0x28
}

+ (id)_defaultKeyDescriptors;	// IMP=0x00000000000479c8
+ (id)sharedInstance;	// IMP=0x00000000000077cb
+ (id)allocWithZone:(struct _NSZone *)arg1;	// IMP=0x00000000000476c1
@property(readonly, nonatomic) NSOperationQueue *contactsUpdateQueue; // @synthesize contactsUpdateQueue=_contactsUpdateQueue;
@property(readonly, nonatomic) CNContactStore *contactStore; // @synthesize contactStore=_contactStore;
@property(readonly, nonatomic) CNAvatarCache *avatarCache; // @synthesize avatarCache=_avatarCache;
// - (void).cxx_destruct;	// IMP=0x0000000000047f0c
@property(readonly, copy, nonatomic) CNContact *meContact;
- (void)fetchContactForAddress:(id)arg1 withCompletion:(id)arg2;	// IMP=0x0000000000047af3
- (id)contactForAddress:(id)arg1;	// IMP=0x00000000000087b6
- (void)_contactsChanged:(id)arg1;	// IMP=0x00000000000478bc
- (void)dealloc;	// IMP=0x000000000004777a
- (id)init;	// IMP=0x0000000000007884

@end

