//
//     Generated by class-dump 3.5b1 (64 bit) (Debug version compiled Dec  3 2019 19:59:57).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <MailCore/EFLoggable-Protocol.h>
#import <MailCore/MCConnectionLogging-Protocol.h>

@class ECSASLClient, MCSocket, NSArray, NSData, NSDate, NSFileHandle, NSString;
@protocol MCAccount;

@interface MCConnection : NSObject <EFLoggable, MCConnectionLogging>
{
    id _accountLock;	// 8 = 0x8
    id <MCAccount> _account;	// 16 = 0x10
    BOOL _isBackground;	// 24 = 0x18
    MCSocket *_socket;	// 32 = 0x20
    double _connectTimeout;	// 40 = 0x28
    double _readWriteTimeout;	// 48 = 0x30
    unsigned long long _totalBytesRead;	// 56 = 0x38
    NSDate *_readTimestamp;	// 64 = 0x40
    void *_buffer;	// 72 = 0x48
    long long _bufferRemainingBytes;	// 80 = 0x50
    unsigned long long _bufferStart;	// 88 = 0x58
    unsigned long long _bufferLength;	// 96 = 0x60
    NSData *_logHeader;	// 104 = 0x68
    ECSASLClient *_saslClient;	// 112 = 0x70
    NSFileHandle *_logFile;	// 120 = 0x78
}

+ (BOOL)shouldLogActivityForHost:(id)arg1 port:(long long)arg2;	// IMP=0x0000000000015993
+ (void)setLogActivityToFile:(BOOL)arg1;	// IMP=0x0000000000046d03
+ (BOOL)logActivityToFile;	// IMP=0x0000000000046cf6
+ (void)setLogActivityOnHosts:(id)arg1;	// IMP=0x0000000000046c66
+ (id)logActivityOnHosts;	// IMP=0x0000000000046c55
+ (void)setLogActivityOnPorts:(id)arg1;	// IMP=0x0000000000046bc5
+ (id)logActivityOnPorts;	// IMP=0x0000000000046bb4
+ (void)setLogAllSocketActivity:(BOOL)arg1;	// IMP=0x0000000000046b58
+ (BOOL)logAllSocketActivity;	// IMP=0x0000000000046b4b
+ (void)setLoggingDelegate:(id)arg1;	// IMP=0x0000000000046ad2
+ (id)loggingDelegate;	// IMP=0x0000000000046a85
+ (BOOL)_defaultsToBackground;	// IMP=0x00000000000348d8
+ (void)initialize;	// IMP=0x000000000001361e
+ (id)log;	// IMP=0x0000000000043f39
@property(retain) NSFileHandle *logFile; // @synthesize logFile=_logFile;
@property(retain, nonatomic) ECSASLClient *saslClient; // @synthesize saslClient=_saslClient;
@property(retain, nonatomic) NSData *logHeader; // @synthesize logHeader=_logHeader;
@property(nonatomic) unsigned long long bufferLength; // @synthesize bufferLength=_bufferLength;
@property(nonatomic) unsigned long long bufferStart; // @synthesize bufferStart=_bufferStart;
@property(nonatomic) long long bufferRemainingBytes; // @synthesize bufferRemainingBytes=_bufferRemainingBytes;
@property(nonatomic) void *buffer; // @synthesize buffer=_buffer;
@property(retain, nonatomic) NSDate *readTimestamp; // @synthesize readTimestamp=_readTimestamp;
@property(nonatomic) unsigned long long totalBytesRead; // @synthesize totalBytesRead=_totalBytesRead;
@property BOOL isBackground; // @synthesize isBackground=_isBackground;
@property(nonatomic) double readWriteTimeout; // @synthesize readWriteTimeout=_readWriteTimeout;
@property(nonatomic) double connectTimeout; // @synthesize connectTimeout=_connectTimeout;
@property(retain, nonatomic) MCSocket *socket; // @synthesize socket=_socket;
// - (void).cxx_destruct;	// IMP=0x0000000000035430
- (void)_resetLogHeaderWithPort:(long long)arg1;	// IMP=0x00000000000157c0
- (void)_logToFileDidChange:(id)arg1;	// IMP=0x0000000000013adb
- (void)_loggingDidChange:(id)arg1;	// IMP=0x000000000004752a
- (void)_logEventWithPrefix:(const char *)arg1 bytes:(const void *)arg2 length:(unsigned long long)arg3 maskStartIndex:(unsigned long long)arg4 maskLength:(unsigned long long)arg5;	// IMP=0x0000000000046d60
- (void)flushLog;	// IMP=0x0000000000046a7f
- (void)logBytes:(void *)arg1 length:(unsigned long long)arg2;	// IMP=0x0000000000046a1e
- (void)logData:(id)arg1 range:(struct _NSRange)arg2;	// IMP=0x00000000000469c9
- (void)logData:(id)arg1;	// IMP=0x00000000000468db
- (void)logString:(id)arg1;	// IMP=0x0000000000046884
- (BOOL)_isSSLError:(id)arg1;	// IMP=0x0000000000037522
- (void)_setupWriteErrorForMonitor;	// IMP=0x00000000000461e1
- (void)_setupReadErrorForMonitor;	// IMP=0x0000000000036e80
- (id)_adjustedSSLErrorWithHostname:(id)arg1 serverTrust:(struct __SecTrust *)arg2;	// IMP=0x0000000000045997
- (void)_setupConnectionErrorForMonitorWithPort:(long long)arg1 usingSSL:(BOOL)arg2 serverTrust:(struct __SecTrust *)arg3;	// IMP=0x0000000000044bd0
- (BOOL)_writeData:(id)arg1 dontLogBytesInRange:(struct _NSRange)arg2 error:(id *)arg3;	// IMP=0x000000000001921a
- (long long)_readBytesFromSocketIntoBuffer:(void *)arg1 amount:(unsigned long long)arg2 requireAllBytes:(BOOL)arg3 error:(id *)arg4;	// IMP=0x0000000000018326
- (BOOL)_fillBuffer:(id *)arg1;	// IMP=0x000000000001794e
- (BOOL)_readBytesIntoData:(id)arg1 desiredLength:(long long)arg2 error:(id *)arg3;	// IMP=0x0000000000020690
- (BOOL)_readLineIntoData:(id)arg1 error:(id *)arg2;	// IMP=0x0000000000017761
@property(readonly, nonatomic) BOOL hasBytesAvailable;
- (void)disconnect;	// IMP=0x0000000000035173
- (void)quit;	// IMP=0x0000000000044b69
- (BOOL)isValidAllowNetworking:(BOOL)arg1;	// IMP=0x0000000000044ae7
- (void)discoverAccountSettings;	// IMP=0x0000000000044ae1
@property(readonly, nonatomic) BOOL supportsPlainTextSchemes;
- (id)_authenticateWithPlainTextSchemes;	// IMP=0x0000000000044ad1
- (id)_authenticateWithNonPlainTextSchemes;	// IMP=0x0000000000044ac9
- (BOOL)_authenticateWithSASLClient:(id)arg1;	// IMP=0x0000000000044ac1
- (BOOL)_authenticateWithAuthenticationMechanisms:(id)arg1 allowPlainText:(BOOL)arg2;	// IMP=0x000000000001b21d
- (BOOL)_shouldKeepTryingAfterProcessingAuthenticationFailureAllowingReconnect:(BOOL)arg1 bestError:(id *)arg2;	// IMP=0x0000000000044967
- (id)renewCredentialsIfNeededForAccount:(id)arg1;	// IMP=0x00000000000443cf
- (BOOL)authenticate;	// IMP=0x000000000001a7e1
- (BOOL)_completeConnectionWithResult:(BOOL)arg1;	// IMP=0x0000000000044391
- (void)_setupConnection;	// IMP=0x000000000004438b
- (BOOL)_startTLS;	// IMP=0x000000000001a161
- (void)_setupSocketWithSecurityLayer:(long long)arg1 disableEphemeralDiffieHellmanCiphers:(BOOL)arg2 connectTimeout:(double)arg3;	// IMP=0x00000000000441c4
- (id)_newConnectionAttemptsConfigureDynamically:(BOOL)arg1;	// IMP=0x0000000000014e52
- (BOOL)connectDiscoveringBestSettings:(BOOL)arg1;	// IMP=0x000000000001400b
@property(readonly, nonatomic) BOOL isExpensive;
@property(readonly, copy, nonatomic) NSArray *authenticationMechanisms;
@property(readonly, nonatomic) unsigned int cipherKeyLength;
@property __weak id <MCAccount> account;
- (void)dealloc;	// IMP=0x0000000000035394
@property(readonly, copy) NSString *description;
- (id)init;	// IMP=0x00000000000138e0

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

