//
//     Generated by class-dump 3.5b1 (64 bit) (Debug version compiled Dec  3 2019 19:59:57).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface MCDateFormatterFactory : NSObject
{
}

+ (id)newUncommonInternetMessageDateFormatters;	// IMP=0x0000000000048e24
+ (id)newCommonInternetMessageDateFormatters;	// IMP=0x0000000000021eaa
+ (id)newInternetMessageDateFormatter;	// IMP=0x000000000002cb8b
+ (id)newIMAPDateFormatter;	// IMP=0x0000000000021814

@end

