//
//     Generated by class-dump 3.5b1 (64 bit) (Debug version compiled Dec  3 2019 19:59:57).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSOperationQueue.h>

@class NSPort;

@interface MCInvocationQueue : NSOperationQueue
{
    id _runLoopCancelPortOnceLock;	// 8 = 0x8
    NSPort *_runLoopCancelPort;	// 16 = 0x10
    NSOperationQueue *_secondaryQueue;	// 24 = 0x18
}

+ (BOOL)didCancelAllMonitoredItems;	// IMP=0x00000000000124ca
+ (void)cancelAllMonitoredItems;	// IMP=0x0000000000036b49
@property(readonly, nonatomic) NSOperationQueue *secondaryQueue; // @synthesize secondaryQueue=_secondaryQueue;
// - (void).cxx_destruct;	// IMP=0x000000000001c153
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;	// IMP=0x0000000000052d3a
- (id)_newOperationWithInvocation:(id)arg1;	// IMP=0x000000000000361c
- (void)runInvocationOnQueueSynchronously:(id)arg1;	// IMP=0x0000000000052a5c
- (void)addInvocation:(id)arg1;	// IMP=0x0000000000003589
- (void)waitUntilAllOperationsAreFinished;	// IMP=0x00000000000529ef
- (void)cancelAllOperations;	// IMP=0x0000000000052982
- (unsigned long long)operationCount;	// IMP=0x0000000000052901
- (id)operations;	// IMP=0x000000000005282e
- (void)dealloc;	// IMP=0x000000000001c10a
- (id)initWithMaxConcurrentOperationCount:(long long)arg1;	// IMP=0x00000000000027f0
- (id)init;	// IMP=0x000000000000282c
- (id)initWithSecondaryQueue:(BOOL)arg1;	// IMP=0x0000000000052777

@end

