//
//     Generated by class-dump 3.5b1 (64 bit) (Debug version compiled Dec  3 2019 19:59:57).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <MailCore/ECMIMECharset-Protocol.h>
#import <MailCore/NSSecureCoding-Protocol.h>

@class NSString;

@interface MCMimeCharset : NSObject <ECMIMECharset, NSSecureCoding>
{
    BOOL _canBeUsedForOutgoingMessages;	// 8 = 0x8
    unsigned long long _encoding;	// 16 = 0x10
    NSString *_charsetName;	// 24 = 0x18
}

+ (unsigned long long)encodingVariantForEncoding:(unsigned long long)arg1 address:(id)arg2;	// IMP=0x000000000000d4c7
+ (id)preferredMimeCharset;	// IMP=0x000000000002b9c2
+ (id)charsetForEncoding:(unsigned long long)arg1;	// IMP=0x0000000000028864
+ (id)allMimeCharsets;	// IMP=0x000000000002891a
+ (BOOL)supportsSecureCoding;	// IMP=0x000000000006b4ea
@property(readonly, nonatomic) BOOL canBeUsedForOutgoingMessages; // @synthesize canBeUsedForOutgoingMessages=_canBeUsedForOutgoingMessages;
@property(readonly, copy, nonatomic) NSString *charsetName; // @synthesize charsetName=_charsetName;
@property(readonly) unsigned long long encoding; // @synthesize encoding=_encoding;
// - (void).cxx_destruct;	// IMP=0x000000000006bb67
- (void)encodeWithCoder:(id)arg1;	// IMP=0x000000000006bafb
- (id)initWithCoder:(id)arg1;	// IMP=0x000000000006babe
@property(readonly, copy) NSString *description;
@property(readonly, copy, nonatomic) NSString *displayName;
- (id)init;	// IMP=0x000000000006b8e2
- (id)initWithCFEncoding:(unsigned int)arg1;	// IMP=0x000000000006b56c

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

