//
//     Generated by class-dump 3.5b1 (64 bit) (Debug version compiled Dec  3 2019 19:59:57).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;
@protocol OS_dispatch_queue;

@interface MCPowerLog : NSObject
{
    NSString *_eventName;	// 8 = 0x8
    NSObject<OS_dispatch_queue> *_logQueue;	// 16 = 0x10
}

@property(readonly, nonatomic) NSObject<OS_dispatch_queue> *logQueue; // @synthesize logQueue=_logQueue;
@property(readonly, copy, nonatomic) NSString *eventName; // @synthesize eventName=_eventName;
// - (void).cxx_destruct;	// IMP=0x0000000000089f3a
- (void)_logEventWithDictionary:(id)arg1;	// IMP=0x0000000000089e12
- (void)logEventWithDictionary:(id)arg1;	// IMP=0x0000000000089d44
- (id)initWithEventName:(id)arg1;	// IMP=0x0000000000089c87

@end

