//
//     Generated by class-dump 3.5b1 (64 bit) (Debug version compiled Dec  3 2019 19:59:57).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class EFObservable;

@interface MCPowerSourceManager : NSObject
{
    struct __CFRunLoopSource *_runLoopSource;	// 8 = 0x8
    BOOL _powerSourceIsLimited;	// 16 = 0x10
}

+ (id)sharedInstance;	// IMP=0x000000000008a479
+ (id)allocWithZone:(struct _NSZone *)arg1;	// IMP=0x000000000008a3c0
+ (id)log;	// IMP=0x000000000008a363
@property(nonatomic) BOOL powerSourceIsLimited; // @synthesize powerSourceIsLimited=_powerSourceIsLimited;
@property(readonly, nonatomic) EFObservable *powerSourceIsLimitedObservable;
- (id)init;	// IMP=0x000000000008a619
- (void)dealloc;	// IMP=0x000000000008a532

@end

