//
//     Generated by class-dump 3.5b1 (64 bit) (Debug version compiled Dec  3 2019 19:59:57).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <MailCore/MCTransferringMessagesProgressEntry.h>

@interface MCPreparingToMoveProgressEntry : MCTransferringMessagesProgressEntry
{
}

+ (id)keyPathsAffectingValuesForProgressName;	// IMP=0x000000000008aa7d
- (id)progressSlice;	// IMP=0x000000000008ab5b
- (id)progressName;	// IMP=0x000000000008aa9d

@end

