//
//     Generated by class-dump 3.5b1 (64 bit) (Debug version compiled Dec  3 2019 19:59:57).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <MailCore/EFLoggable-Protocol.h>
#import <MailCore/MCProgressEntryDelegate-Protocol.h>

@class MCProgressEntry, NSArray, NSMutableArray, NSMutableDictionary, NSString;

@interface MCProgressManager : NSObject <EFLoggable, MCProgressEntryDelegate>
{
    NSMutableDictionary *_entriesBySlice;	// 8 = 0x8
    NSMutableArray *_orderedEntries;	// 16 = 0x10
    MCProgressEntry *_activeEntry;	// 24 = 0x18
    NSArray *_trackedAccountNames;	// 32 = 0x20
}

+ (id)sharedInstance;	// IMP=0x000000000008c754
+ (id)allocWithZone:(struct _NSZone *)arg1;	// IMP=0x000000000008c69b
+ (id)log;	// IMP=0x000000000008c5d2
@property(copy, nonatomic) NSArray *trackedAccountNames; // @synthesize trackedAccountNames=_trackedAccountNames;
@property(retain, nonatomic) MCProgressEntry *activeEntry; // @synthesize activeEntry=_activeEntry;
// - (void).cxx_destruct;	// IMP=0x000000000008da26
- (void)_diagnosticsNotificationReceived:(id)arg1;	// IMP=0x000000000008d635
- (void)removeObjectFromOrderedEntriesAtIndex:(unsigned long long)arg1;	// IMP=0x000000000008d577
- (void)insertObject:(id)arg1 inOrderedEntriesAtIndex:(unsigned long long)arg2;	// IMP=0x000000000008d48d
- (id)objectInOrderedEntriesAtIndex:(unsigned long long)arg1;	// IMP=0x000000000008d477
- (unsigned long long)countOfOrderedEntries;	// IMP=0x000000000008d461
- (id)_entryComparator;	// IMP=0x000000000008d396
- (void)_removeEntry:(id)arg1;	// IMP=0x000000000008d2d1
- (void)_addEntry:(id)arg1;	// IMP=0x000000000008d219
- (void)progressEntryDidFinish:(id)arg1;	// IMP=0x000000000008d0e0
- (void)addProgress:(id)arg1 forSlice:(long long)arg2;	// IMP=0x000000000008cdd3
- (void)_refreshActiveEntry;	// IMP=0x000000000008cbc6
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;	// IMP=0x000000000008caff
@property(readonly, copy, nonatomic) NSArray *orderedEntries;
- (id)init;	// IMP=0x000000000008ca0a
- (void)dealloc;	// IMP=0x000000000008c80d

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

