//
//     Generated by class-dump 3.5b1 (64 bit) (Debug version compiled Dec  3 2019 19:59:57).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSInvocation.h>

@class NSNumber;

@interface MCQOSInvocation : NSInvocation
{
    NSNumber *_requestedQualityOfService;	// 8 = 0x8
}

@property(retain) NSNumber *requestedQualityOfService; // @synthesize requestedQualityOfService=_requestedQualityOfService;
// - (void).cxx_destruct;	// IMP=0x000000000007faa7

@end

