//
//     Generated by class-dump 3.5b1 (64 bit) (Debug version compiled Dec  3 2019 19:59:57).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <MailCore/MCPlaceholderFileWrapper.h>

@class NSURL;

@interface MCRemotePlaceholderFileWrapper : MCPlaceholderFileWrapper
{
    NSURL *_URL;	// 184 = 0xb8
}

@property(readonly, nonatomic) NSURL *URL; // @synthesize URL=_URL;
// - (void).cxx_destruct;	// IMP=0x000000000004f9fc
- (unsigned long long)approximateSizeAllowingDiskIO:(BOOL)arg1;	// IMP=0x000000000004f973
- (id)symbolicLinkDestinationURL;	// IMP=0x000000000004f961
- (BOOL)isRemotelyAccessed;	// IMP=0x000000000004f956
- (id)initWithCoder:(id)arg1;	// IMP=0x000000000004f887
- (id)initWithSerializedRepresentation:(id)arg1;	// IMP=0x000000000004f7b8
- (id)initSymbolicLinkWithDestinationURL:(id)arg1;	// IMP=0x000000000004f6e9
- (id)initRegularFileWithContents:(id)arg1;	// IMP=0x000000000004f61a
- (id)initDirectoryWithFileWrappers:(id)arg1;	// IMP=0x000000000004f54b
- (id)initWithURL:(id)arg1 options:(unsigned long long)arg2 error:(id *)arg3;	// IMP=0x000000000004f47c
- (id)initWithURL:(id)arg1;	// IMP=0x000000000004f3e7

@end

