//
//     Generated by class-dump 3.5b1 (64 bit) (Debug version compiled Dec  3 2019 19:59:57).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <MailCore/MCTaskOperation.h>

@interface MCResultTaskOperation : MCTaskOperation
{
    id _result;	// 24 = 0x18
}

@property(retain, nonatomic) id result; // @synthesize result=_result;
// - (void).cxx_destruct;	// IMP=0x000000000001c28d

@end

