//
//     Generated by class-dump 3.5b1 (64 bit) (Debug version compiled Dec  3 2019 19:59:57).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSEnumerator.h>

#import "DOMNodeFilter-Protocol.h"

@class DOMNode, EditableWebMessageDocument, NSString;

@interface _ComposeAttachmentEnumerator : NSEnumerator <DOMNodeFilter>
{
    BOOL _acceptDeleted;	// 8 = 0x8
    BOOL _acceptNonDeleted;	// 9 = 0x9
    DOMNode *_currentNode;	// 16 = 0x10
    DOMNode *_containerNode;	// 24 = 0x18
    DOMNode *_endNode;	// 32 = 0x20
    EditableWebMessageDocument *_document;	// 40 = 0x28
}

@property(nonatomic) BOOL acceptNonDeleted; // @synthesize acceptNonDeleted=_acceptNonDeleted;
@property(nonatomic) BOOL acceptDeleted; // @synthesize acceptDeleted=_acceptDeleted;
@property(readonly, nonatomic) EditableWebMessageDocument *document; // @synthesize document=_document;
@property(retain, nonatomic) DOMNode *endNode; // @synthesize endNode=_endNode;
@property(retain, nonatomic) DOMNode *containerNode; // @synthesize containerNode=_containerNode;
@property(retain, nonatomic) DOMNode *currentNode; // @synthesize currentNode=_currentNode;
// - (void).cxx_destruct;	// IMP=0x000000010013d4fd
- (id)nextObject;	// IMP=0x0000000100056dd6
- (short)acceptNode:(id)arg1;	// IMP=0x0000000100056f28
- (id)init;	// IMP=0x000000010013d3a8
- (id)initWithDocument:(id)arg1 options:(unsigned long long)arg2 range:(id)arg3;	// IMP=0x0000000100056bc6

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

