//
//     Generated by class-dump 3.5b1 (64 bit) (Debug version compiled Dec  3 2019 19:59:57).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSTextFinderAsynchronousDocumentFindMatch-Protocol.h"

@class ConversationViewFindController, MUICollectionView, NSArray, NSString;
@protocol NSTextFinderAsynchronousDocumentFindMatch;

@interface _ConversationFindMatch : NSObject <NSTextFinderAsynchronousDocumentFindMatch>
{
    MUICollectionView *_containingView;	// 8 = 0x8
    id <NSTextFinderAsynchronousDocumentFindMatch> _backingFindMatch;	// 16 = 0x10
    NSArray *_textRectsInDocument;	// 24 = 0x18
    unsigned long long _cellIndex;	// 32 = 0x20
    ConversationViewFindController *_findController;	// 40 = 0x28
}

@property(retain, nonatomic) ConversationViewFindController *findController; // @synthesize findController=_findController;
@property(nonatomic) unsigned long long cellIndex; // @synthesize cellIndex=_cellIndex;
@property(retain, nonatomic) NSArray *textRectsInDocument; // @synthesize textRectsInDocument=_textRectsInDocument;
@property(retain, nonatomic) id <NSTextFinderAsynchronousDocumentFindMatch> backingFindMatch; // @synthesize backingFindMatch=_backingFindMatch;
@property(retain, nonatomic) MUICollectionView *containingView; // @synthesize containingView=_containingView;
// - (void).cxx_destruct;	// IMP=0x000000010011bb5e
- (void)generateTextImage:(id)arg1;	// IMP=0x000000010011b837
@property(readonly, nonatomic) NSArray *textRects;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

