//
//     Generated by class-dump 3.5b1 (64 bit) (Debug version compiled Dec  3 2019 19:59:57).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSButtonCell.h>

@interface _FavoriteButtonCell : NSButtonCell
{
}

- (BOOL)_shouldDrawBezel;	// IMP=0x000000010001130a

@end

