//
//     Generated by class-dump 3.5b1 (64 bit) (Debug version compiled Dec  3 2019 19:59:57).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSView.h>

@class NSTrackingArea;
@protocol FavoriteHoverViewDirectionProtocol;

@interface _FavoriteMenuScrollHoverView : NSView
{
    id <FavoriteHoverViewDirectionProtocol> _delegate;	// 112 = 0x70
    long long _direction;	// 120 = 0x78
    NSTrackingArea *_trackingArea;	// 128 = 0x80
}

@property(retain, nonatomic) NSTrackingArea *trackingArea; // @synthesize trackingArea=_trackingArea;
@property(readonly, nonatomic) long long direction; // @synthesize direction=_direction;
@property(nonatomic) __weak id <FavoriteHoverViewDirectionProtocol> delegate; // @synthesize delegate=_delegate;
// - (void).cxx_destruct;	// IMP=0x000000010015c5f8
- (void)mouseExited:(id)arg1;	// IMP=0x000000010015c526
- (void)mouseEntered:(id)arg1;	// IMP=0x000000010015c4b7
- (void)updateTrackingAreas;	// IMP=0x000000010015c3ad
- (void)dealloc;	// IMP=0x000000010015c350
- (void)_favoriteMenuScrollHoverViewCommonInitWithDirection:(long long)arg1;	// IMP=0x000000010015bf0d
- (id)initWithCoder:(id)arg1;	// IMP=0x000000010015bec4
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x000000010015bdf5
- (id)initWithDirection:(long long)arg1;	// IMP=0x000000010015bd86

@end

