//
//     Generated by class-dump 3.5b1 (64 bit) (Debug version compiled Dec  3 2019 19:59:57).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSImmediateActionAnimationController-Protocol.h"

@class AttachmentViewController, NSString;

@interface _MarkupImmediateActionAnimationController : NSObject <NSImmediateActionAnimationController>
{
    AttachmentViewController *_attachment;	// 8 = 0x8
}

@property(retain, nonatomic) AttachmentViewController *attachment; // @synthesize attachment=_attachment;
// - (void).cxx_destruct;	// IMP=0x000000010014fa20
- (void)recognizerDidCompleteAnimation:(id)arg1;	// IMP=0x000000010014f8c5

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

