//
//     Generated by class-dump 3.5b1 (64 bit) (Debug version compiled Dec  3 2019 19:59:57).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSTableHeaderCell.h>

@interface _MTMHeaderCell : NSTableHeaderCell
{
}

- (struct CGRect)sortIndicatorRectForBounds:(struct CGRect)arg1;	// IMP=0x0000000100237874
- (struct CGRect)drawingRectForBounds:(struct CGRect)arg1;	// IMP=0x00000001002377bd

@end

