//
//     Generated by class-dump 3.5b1 (64 bit) (Debug version compiled Dec  3 2019 19:59:57).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "_MTMMetaMailbox.h"

@interface _MTMSentMailbox : _MTMMetaMailbox
{
}

- (id)defaultMessageColumnAttributesKey;	// IMP=0x000000010023d964
- (id)messageColumnConfiguration;	// IMP=0x000000010023d945
- (id)recoverDisplayName;	// IMP=0x000000010023d8d8
- (id)displayName;	// IMP=0x000000010023d86b

@end

