//
//     Generated by class-dump 3.5b1 (64 bit) (Debug version compiled Dec  3 2019 19:59:57).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "_MTMMetaMailbox.h"

@interface _MTMInboxMailbox : _MTMMetaMailbox
{
}

- (id)restoreString;	// IMP=0x000000010023d596
- (id)recoverDisplayName;	// IMP=0x000000010023d529
- (id)defaultMessageColumnAttributesKey;	// IMP=0x000000010023d50a
- (id)displayName;	// IMP=0x000000010023d49d

@end

