//
//     Generated by class-dump 3.5b1 (64 bit) (Debug version compiled Dec  3 2019 19:59:57).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "MTMSpecialMailbox.h"

@interface _MTMMetaMailbox : MTMSpecialMailbox
{
}

- (BOOL)_shouldSortMailboxes;	// IMP=0x000000010023be4d
- (id)subRestoreString;	// IMP=0x000000010023bddd
- (id)restoreString;	// IMP=0x000000010023bd06
- (id)paths;	// IMP=0x000000010023bb5c
- (void)loadNextMessagesWithControllingMailbox:(id)arg1 andFetcher:(id)arg2;	// IMP=0x000000010023b936
- (BOOL)needsToLoadMessagesInBackground;	// IMP=0x000000010023b797
- (void)_loadMessages;	// IMP=0x000000010023b52f
- (void)discardMailbox;	// IMP=0x000000010023b36b
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;	// IMP=0x000000010023b1d7

@end

