//
//     Generated by class-dump 3.5b1 (64 bit) (Debug version compiled Dec  3 2019 19:59:57).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "_MTMSubMetaMailbox.h"

@interface _MTMDisabledSubMetaMailbox : _MTMSubMetaMailbox
{
}

- (BOOL)enabled;	// IMP=0x000000010023ce2c

@end

