//
//     Generated by class-dump 3.5b1 (64 bit) (Debug version compiled Dec  3 2019 19:59:57).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSView.h>

@interface _RelatedMessageBannerView : NSView
{
}

- (void)updateLayer;	// IMP=0x00000001002053a6

@end

