//
//     Generated by class-dump 3.5b1 (64 bit) (Debug version compiled Dec  3 2019 19:59:57).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSTableViewDataSource-Protocol.h"
#import "NSTableViewDelegate-Protocol.h"

@class NSButton, NSImage, NSMutableArray, NSMutableDictionary, NSOperationQueue, NSSearchField, NSString, NSTableView, NSWindow;

@interface AddressHistoryController : NSObject <NSTableViewDataSource, NSTableViewDelegate>
{
    NSMutableArray *_historyRecords;	// 8 = 0x8
    BOOL _sortIsAscending;	// 16 = 0x10
    NSTableView *_historyTableView;	// 24 = 0x18
    NSButton *_addToContactsButton;	// 32 = 0x20
    NSWindow *_window;	// 40 = 0x28
    NSSearchField *_searchField;	// 48 = 0x30
    NSMutableDictionary *_abRecordMap;	// 56 = 0x38
    NSOperationQueue *_fetchQueue;	// 64 = 0x40
    NSString *_sortColumn;	// 72 = 0x48
    NSImage *_addressBookPersonImage;	// 80 = 0x50
}

+ (id)sharedInstance;	// IMP=0x00000001000a7436
+ (id)allocWithZone:(struct _NSZone *)arg1;	// IMP=0x00000001000a737d
@property(readonly, nonatomic) NSImage *addressBookPersonImage; // @synthesize addressBookPersonImage=_addressBookPersonImage;
@property(nonatomic) BOOL sortIsAscending; // @synthesize sortIsAscending=_sortIsAscending;
@property(nonatomic) __weak NSString *sortColumn; // @synthesize sortColumn=_sortColumn;
@property(readonly, nonatomic) NSOperationQueue *fetchQueue; // @synthesize fetchQueue=_fetchQueue;
@property(retain, nonatomic) NSMutableDictionary *abRecordMap; // @synthesize abRecordMap=_abRecordMap;
@property(nonatomic) __weak NSSearchField *searchField; // @synthesize searchField=_searchField;
@property(retain, nonatomic) NSWindow *window; // @synthesize window=_window;
@property(nonatomic) __weak NSButton *addToContactsButton; // @synthesize addToContactsButton=_addToContactsButton;
@property(nonatomic) __weak NSTableView *historyTableView; // @synthesize historyTableView=_historyTableView;
// - (void).cxx_destruct;	// IMP=0x00000001000aa753
- (id)_recordForAddress:(id)arg1;	// IMP=0x00000001000aa435
- (void)_addressBookDidChange:(id)arg1;	// IMP=0x00000001000aa1cf
- (id)tableView:(id)arg1 toolTipForCell:(id)arg2 rect:(struct CGRect *)arg3 tableColumn:(id)arg4 row:(long long)arg5 mouseLocation:(struct CGPoint)arg6;	// IMP=0x00000001000a9fe4
- (void)_showColumnSortIndicator;	// IMP=0x00000001000a9d8f
- (void)_sortHistoryData;	// IMP=0x00000001000a960c
- (void)tableView:(id)arg1 didClickTableColumn:(id)arg2;	// IMP=0x00000001000a94ff
- (void)tableViewSelectionDidChange:(id)arg1;	// IMP=0x00000001000a9240
- (void)tableView:(id)arg1 willDisplayCell:(id)arg2 forTableColumn:(id)arg3 row:(long long)arg4;	// IMP=0x00000001000a918b
- (id)tableView:(id)arg1 objectValueForTableColumn:(id)arg2 row:(long long)arg3;	// IMP=0x00000001000a8ee2
- (long long)numberOfRowsInTableView:(id)arg1;	// IMP=0x00000001000a8e52
- (void)openContacts:(id)arg1;	// IMP=0x00000001000a8c71
- (void)windowWillClose:(id)arg1;	// IMP=0x00000001000a8bc5
- (void)_cancelSearch:(id)arg1;	// IMP=0x00000001000a8b66
- (void)search:(id)arg1;	// IMP=0x00000001000a8910
- (void)searchIndex:(id)arg1;	// IMP=0x00000001000a88c4
- (void)deleteFromHistory:(id)arg1;	// IMP=0x00000001000a834f
- (void)addToContacts:(id)arg1;	// IMP=0x00000001000a7e6d
- (void)showAddressHistory;	// IMP=0x00000001000a7c1f
- (void)_fetchRecentsDataWithCompletionBlock:(id)arg1;	// IMP=0x00000001000a78ae
- (void)dealloc;	// IMP=0x00000001000a77a9
- (id)init;	// IMP=0x00000001000a74fb

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

