//
//     Generated by class-dump 3.5b1 (64 bit) (Debug version compiled Dec  3 2019 19:59:57).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSView.h>

@interface BlockedWebPluginView : NSView
{
}

- (void)_blockedWebPluginViewCommonInit;	// IMP=0x00000001000c6c17
- (id)initWithCoder:(id)arg1;	// IMP=0x00000001000c6bd0
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x00000001000c6b71

@end

