//
//     Generated by class-dump 3.5b1 (64 bit) (Debug version compiled Dec  3 2019 19:59:57).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "DynamicErrorWindowDelegate-Protocol.h"

@class MFDatabaseRecoverer, NSString;

@interface BusyStatusErrorWindowDelegate : NSObject <DynamicErrorWindowDelegate>
{
    MFDatabaseRecoverer *_recoverer;	// 8 = 0x8
}

@property(nonatomic) __weak MFDatabaseRecoverer *recoverer; // @synthesize recoverer=_recoverer;
// - (void).cxx_destruct;	// IMP=0x00000001000c906b
- (id)_capitalizedStringForDatabase;	// IMP=0x00000001000c8f5f
- (id)_stringForDatabase;	// IMP=0x00000001000c8e7a
- (long long)helpTopicForDiagnosis:(long long)arg1;	// IMP=0x00000001000c8e72
- (void)rightActionSelectedWithDiagnosis:(long long)arg1;	// IMP=0x00000001000c8d8b
- (void)leftActionSelectedWithDiagnosis:(long long)arg1;	// IMP=0x00000001000c8d4e
- (id)rightButtonTextForErrorDiagnosis:(long long)arg1;	// IMP=0x00000001000c8cde
- (id)leftButtonTextForErrorDiagnosis:(long long)arg1;	// IMP=0x00000001000c8bf8
- (id)errorDescriptionForErrorDiagnosis:(long long)arg1;	// IMP=0x00000001000c89e0
- (id)errorMessageForErrorDiagnosis:(long long)arg1;	// IMP=0x00000001000c87d7
@property(readonly, nonatomic) BOOL displayIndeterminateProgress;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

