//
//     Generated by class-dump 3.5b1 (64 bit) (Debug version compiled Dec  3 2019 19:59:57).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "BannerViewController.h"

@class NSButton, NSImageView, NSLayoutConstraint, NSTextField;

@interface ChildBannerViewController : BannerViewController
{
    NSImageView *_icon;	// 16 = 0x10
    NSTextField *_messageField;	// 24 = 0x18
    NSButton *_helpButton;	// 32 = 0x20
    NSButton *_sendButton;	// 40 = 0x28
    NSLayoutConstraint *_helpButtonTrailingSpace;	// 48 = 0x30
    long long _parentalControlMessageState;	// 56 = 0x38
}

@property(nonatomic) long long parentalControlMessageState; // @synthesize parentalControlMessageState=_parentalControlMessageState;
@property(nonatomic) __weak NSLayoutConstraint *helpButtonTrailingSpace; // @synthesize helpButtonTrailingSpace=_helpButtonTrailingSpace;
@property(nonatomic) __weak NSButton *sendButton; // @synthesize sendButton=_sendButton;
@property(nonatomic) __weak NSButton *helpButton; // @synthesize helpButton=_helpButton;
@property(nonatomic) __weak NSTextField *messageField; // @synthesize messageField=_messageField;
@property(nonatomic) __weak NSImageView *icon; // @synthesize icon=_icon;
// - (void).cxx_destruct;	// IMP=0x00000001000cc1c0
- (void)sendMessage:(id)arg1;	// IMP=0x00000001000cbf62
- (void)updateBannerContents;	// IMP=0x00000001000cbc3c
- (void)updateWantsDisplay;	// IMP=0x000000010003c3be

@end

