//
//     Generated by class-dump 3.5b1 (64 bit) (Debug version compiled Dec  3 2019 19:59:57).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class ComposeViewController, ComposeWindowController, NSDictionary, NSSet;

@protocol ComposeContext <NSObject>
@property(readonly, nonatomic) BOOL shouldBlockTermination;
@property(readonly, nonatomic) BOOL isInteractive;
@property(readonly, copy, nonatomic) NSDictionary *editorSettings;
@property(readonly, copy, nonatomic) NSSet *targetMessages;
@property(readonly, nonatomic) BOOL isMiniaturized;
@property(readonly, nonatomic) long long type;
@property(readonly, nonatomic) BOOL blockMessageContent;
@property(readonly, nonatomic) BOOL shouldTransientlyActivateApplication;
- (ComposeWindowController *)windowControllerWithState:(NSSet *)arg1;
- (void)controllerWillClose:(ComposeViewController *)arg1;
- (void)presentComposeViewController:(ComposeViewController *)arg1 completion:(void (^)(void))arg2;
- (void)loadCompleted:(ComposeViewController *)arg1;
- (void)controllerInitialized:(ComposeViewController *)arg1;
- (void)generateQuotedContentWithCompletion:(void (^)(MCMessageBody *))arg1;

@optional
@property(nonatomic) __weak ComposeWindowController *windowController;
@end

