//
//     Generated by class-dump 3.5b1 (64 bit) (Debug version compiled Dec  3 2019 19:59:57).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <WebKit/WKWebView.h>

#import "MUIComposeBodyFieldObserver-Protocol.h"
#import "NSInspectorBarClient-Protocol.h"

@class NSArray, NSString, NSWindow, _WKRemoteObjectInterface;
@protocol ComposeWebViewDelegate, MUIComposeBodyFieldController;

@interface ComposeWebView : WKWebView <MUIComposeBodyFieldObserver, NSInspectorBarClient>
{
    id <MUIComposeBodyFieldController> _bodyFieldController;	// 112 = 0x70
    _WKRemoteObjectInterface *_bodyFieldObserverInterface;	// 120 = 0x78
    id <ComposeWebViewDelegate> _delegate;	// 128 = 0x80
    NSArray *_attachmentIdentifiersForContextualMenu;	// 136 = 0x88
}

+ (id)_webViewConfiguration;	// IMP=0x0000000100106054
@property(copy, nonatomic) NSArray *attachmentIdentifiersForContextualMenu; // @synthesize attachmentIdentifiersForContextualMenu=_attachmentIdentifiersForContextualMenu;
@property(nonatomic) __weak id <ComposeWebViewDelegate> delegate; // @synthesize delegate=_delegate;
// - (void).cxx_destruct;	// IMP=0x0000000100107ddd
- (void)composeBodyFieldDidThrowException:(id)arg1;	// IMP=0x0000000100107cfa
- (void)composeBodyFieldDidModifySignature;	// IMP=0x0000000100107c9b
- (void)composeBodyFieldDidChange;	// IMP=0x0000000100107c3c
- (void)viewAttachmentInline:(id)arg1;	// IMP=0x00000001001075ae
- (void)exportAttachmentsToIPhoto:(id)arg1;	// IMP=0x000000010010755e
- (void)saveAttachmentToDownloadsDirectory:(id)arg1;	// IMP=0x00000001001074be
- (void)saveAttachment:(id)arg1;	// IMP=0x000000010010741e
- (void)quickLookAttachment:(id)arg1;	// IMP=0x000000010010737e
- (void)chooseApplicationToOpenAttachment:(id)arg1;	// IMP=0x00000001001072de
- (void)openAttachmentWithApplication:(id)arg1;	// IMP=0x00000001001071f0
- (void)openAttachment:(id)arg1;	// IMP=0x0000000100107154
- (id)_attachmentsForContextualMenu;	// IMP=0x000000010010706d
- (void)decreaseIndentation:(id)arg1;	// IMP=0x000000010010705b
- (void)increaseIndentation:(id)arg1;	// IMP=0x0000000100107049
- (void)pasteAsQuotation:(id)arg1;	// IMP=0x0000000100107037
- (void)changeQuoteLevel:(id)arg1;	// IMP=0x0000000100106ffb
- (void)makeFontSmaller:(id)arg1;	// IMP=0x0000000100106f85
- (void)makeFontBigger:(id)arg1;	// IMP=0x0000000100106f0f
@property(readonly) NSArray *inspectorBarItemIdentifiers;
@property(readonly, nonatomic) id <MUIComposeBodyFieldController> bodyFieldController;
- (void)_close;	// IMP=0x0000000100106943
- (BOOL)validateUserInterfaceItem:(id)arg1;	// IMP=0x0000000100106690
- (void)updateLayer;	// IMP=0x000000010010658a
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x0000000100106485

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@property(readonly) NSWindow *window;

@end

