//
//     Generated by class-dump 3.5b1 (64 bit) (Debug version compiled Dec  3 2019 19:59:57).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "ComposeBackEnd.h"

#import "MFScriptingMessage-Protocol.h"

@class DOMHTMLDocument, EditableWebMessageDocumentWK1, NSArray, NSScriptObjectSpecifier, NSString;

@interface ComposeBackEndWK1 : ComposeBackEnd <MFScriptingMessage>
{
}

+ (id)composeBackEndsByUniqueID;	// IMP=0x00000001000e195e
+ (void)unregisterComposeBackEnd:(id)arg1;	// IMP=0x00000001000e1af1
+ (void)registerComposeBackEnd:(id)arg1;	// IMP=0x00000001000e1a4e
+ (id)composeBackEndForUniqueID:(id)arg1;	// IMP=0x00000001000e19bb
- (id)_copyOfContentsForDraft:(BOOL)arg1 isOkayToForceRichText:(BOOL)arg2 isMailDropPlaceholderMessage:(BOOL)arg3;	// IMP=0x00000001000e7b97
@property(readonly, nonatomic) DOMHTMLDocument *htmlDocumentForSave;
- (void)_recursivelyURLifyNode:(id)arg1;	// IMP=0x00000001000e7403
- (void)addBaseURLTagToNode:(id)arg1;	// IMP=0x00000001000e7093
- (id)_newPlainTextRepresentationIncludeAttachments:(BOOL)arg1;	// IMP=0x00000001000e66ac
- (id)htmlStringFromRange:(id)arg1 htmlDocument:(id)arg2 forDraft:(BOOL)arg3 convertObjectsToImages:(BOOL)arg4 convertEditableElements:(BOOL)arg5;	// IMP=0x00000001000e5bcf
- (BOOL)containsRichText;	// IMP=0x00000001000e5b13
- (BOOL)hasContents;	// IMP=0x00000001000e5a76
- (void)_resizeAttachmentElementsForAttachments:(id)arg1;	// IMP=0x00000001000e56b3
- (void)getSignatureElement:(id *)arg1 parent:(id *)arg2 nextSibling:(id *)arg3;	// IMP=0x00000001000e5315
- (BOOL)_mayUseDarkAppearance;	// IMP=0x00000001000e513f
- (void)setupContentsForView:(id)arg1;	// IMP=0x00000001000e3acd
- (void)_initializeDocument;	// IMP=0x00000001000e3a85
- (void)setVcardPath:(id)arg1;	// IMP=0x00000001000e3659
- (void)setHtmlContent:(id)arg1;	// IMP=0x00000001000e3653
@property(readonly) NSScriptObjectSpecifier *objectSpecifier;
- (id)handleCloseScriptCommand:(id)arg1;	// IMP=0x00000001000e319c
- (id)handleSendMessageCommand:(id)arg1;	// IMP=0x00000001000e30e3
- (id)handleSaveMessageCommand:(id)arg1;	// IMP=0x00000001000e3013
- (void)replaceFormattedAddress:(id)arg1 withAddress:(id)arg2 forKey:(id)arg3;	// IMP=0x00000001000e2eb8
- (void)removeFromBccRecipientsAtIndex:(unsigned long long)arg1;	// IMP=0x00000001000e2e52
- (void)removeFromCcRecipientsAtIndex:(unsigned long long)arg1;	// IMP=0x00000001000e2dec
- (void)removeFromToRecipientsAtIndex:(unsigned long long)arg1;	// IMP=0x00000001000e2d86
- (void)insertInBccRecipients:(id)arg1;	// IMP=0x00000001000e2d04
- (void)insertInBccRecipients:(id)arg1 atIndex:(unsigned long long)arg2;	// IMP=0x00000001000e2ce8
- (void)insertInCcRecipients:(id)arg1;	// IMP=0x00000001000e2c66
- (void)insertInCcRecipients:(id)arg1 atIndex:(unsigned long long)arg2;	// IMP=0x00000001000e2c4a
- (void)insertInToRecipients:(id)arg1;	// IMP=0x00000001000e2bc8
- (void)insertInToRecipients:(id)arg1 atIndex:(unsigned long long)arg2;	// IMP=0x00000001000e2bac
- (void)insertRecipient:(id)arg1 atIndex:(unsigned long long)arg2 inHeaderWithKey:(id)arg3;	// IMP=0x00000001000e2aab
@property(readonly, copy, nonatomic) NSArray *bccRecipients;
@property(readonly, copy, nonatomic) NSArray *ccRecipients;
@property(readonly, copy, nonatomic) NSArray *toRecipients;
- (id)recipients;	// IMP=0x00000001000e290d
- (void)_addRecipientsForKey:(id)arg1 toArray:(id)arg2;	// IMP=0x00000001000e264c
- (void)setMessageSignature:(id)arg1;	// IMP=0x00000001000e24f0
- (id)messageSignature;	// IMP=0x00000001000e248d
- (void)setContent:(id)arg1;	// IMP=0x00000001000e213e
- (id)content;	// IMP=0x00000001000e1ffb
- (void)setAppleScriptSubject:(id)arg1;	// IMP=0x00000001000e1fa2
- (id)appleScriptSubject;	// IMP=0x00000001000e1f56
- (void)setAppleScriptSender:(id)arg1;	// IMP=0x00000001000e1efd
- (id)appleScriptSender;	// IMP=0x00000001000e1e9d
- (void)setIsVisible:(BOOL)arg1;	// IMP=0x00000001000e1d71
- (BOOL)isVisible;	// IMP=0x00000001000e1c85

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly, nonatomic) EditableWebMessageDocumentWK1 *document; // @dynamic document;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

