//
//     Generated by class-dump 3.5b1 (64 bit) (Debug version compiled Dec  3 2019 19:59:57).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSTitlebarAccessoryViewController.h>

@interface ComposeWK2TitlebarAccessoryViewController : NSTitlebarAccessoryViewController
{
}

- (void)_showSheet:(id)arg1;	// IMP=0x000000010010ae55
- (void)loadView;	// IMP=0x000000010010ad78
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;	// IMP=0x000000010010ad01

@end

