//
//     Generated by class-dump 3.5b1 (64 bit) (Debug version compiled Dec  3 2019 19:59:57).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "ComposeBackEnd.h"

@class EFFuture, EditableWebMessageDocumentWK2, NSDictionary;
@protocol MUIComposeBodyFieldController;

@interface ComposeBackEndWK2 : ComposeBackEnd
{
    id <MUIComposeBodyFieldController> _bodyFieldController;	// 352 = 0x160
}

// - (void).cxx_destruct;	// IMP=0x00000001000e194b
- (void)setSharedContentHTMLString:(id)arg1 baseURL:(id)arg2 attachmentsByURL:(id)arg3;	// IMP=0x00000001000e15b5
- (void)clearPendingSharedContent;	// IMP=0x00000001000e1598
- (void)_resizeAttachmentElementsForAttachments:(id)arg1;	// IMP=0x00000001000e1592
- (BOOL)hasContents;	// IMP=0x00000001000e1587
@property(readonly, nonatomic) EFFuture *textLengthEstimate;
- (id)_copyOfContentsForDraft:(BOOL)arg1 isOkayToForceRichText:(BOOL)arg2 isMailDropPlaceholderMessage:(BOOL)arg3;	// IMP=0x00000001000e049d
@property(readonly, copy, nonatomic) NSDictionary *attachmentInfoByIdentifier;
- (void)setupContentsForView:(id)arg1 completionHandler:(id)arg2;	// IMP=0x00000001000df369
- (BOOL)containsRichText;	// IMP=0x00000001000df361
- (void)_initializeDocument;	// IMP=0x00000001000df309

// Remaining properties
@property(readonly, nonatomic) EditableWebMessageDocumentWK2 *document; // @dynamic document;

@end

