//
//     Generated by class-dump 3.5b1 (64 bit) (Debug version compiled Dec  3 2019 19:59:57).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "ColorBackgroundView.h"

@class CriteriaUIHelper, MFMailbox, MailboxesChooser, NSButton, NSDatePicker, NSMenu, NSNumberFormatter, NSPopUpButton, NSString, NSTextField, NSView;

@interface CriterionView : ColorBackgroundView
{
    long long _criterionType;	// 112 = 0x70
    BOOL _isSmartMailboxCriterion;	// 120 = 0x78
    NSView *_headerCriteriaView;	// 128 = 0x80
    NSView *_simpleCriteriaView;	// 136 = 0x88
    NSView *_accountOrGroupView;	// 144 = 0x90
    NSView *_mailboxesView;	// 152 = 0x98
    NSView *_daysOldDatesView;	// 160 = 0xa0
    NSView *_simpleDatesView;	// 168 = 0xa8
    NSView *_daysAgoDatesView;	// 176 = 0xb0
    NSView *_inThelastDaysDatesView;	// 184 = 0xb8
    NSView *_daysAgoRangeDatesView;	// 192 = 0xc0
    NSView *_beforeAfterDatesView;	// 200 = 0xc8
    NSView *_dateRangeDatesView;	// 208 = 0xd0
    NSView *_attachmentTypeView;	// 216 = 0xd8
    NSView *_flaggedStatusView;	// 224 = 0xe0
    NSNumberFormatter *_daysFormatter;	// 232 = 0xe8
    NSNumberFormatter *_daysOldFormatter;	// 240 = 0xf0
    MailboxesChooser *_mailboxesChooser;	// 248 = 0xf8
    CriteriaUIHelper *_owner;	// 256 = 0x100
    NSButton *_removeButton;	// 264 = 0x108
    NSButton *_addButton;	// 272 = 0x110
    NSView *_currentView;	// 280 = 0x118
    NSPopUpButton *_criterionPopUp;	// 288 = 0x120
    NSPopUpButton *_qualifierPopUp;	// 296 = 0x128
    NSTextField *_expressionStringField;	// 304 = 0x130
    NSTextField *_expressionNumberField;	// 312 = 0x138
    NSTextField *_expressionOtherNumberField;	// 320 = 0x140
    NSDatePicker *_dateFieldPicker;	// 328 = 0x148
    NSDatePicker *_otherDateFieldPicker;	// 336 = 0x150
    NSPopUpButton *_unitsPopUp;	// 344 = 0x158
    NSMenu *_criterionMenu;	// 352 = 0x160
    NSMenu *_dateQualifierMenu;	// 360 = 0x168
    NSString *_expressionGuess;	// 368 = 0x170
    MFMailbox *_mailboxBeingEdited;	// 376 = 0x178
    long long _criterionTypeForOtherArea;	// 384 = 0x180
}

@property(nonatomic) long long criterionTypeForOtherArea; // @synthesize criterionTypeForOtherArea=_criterionTypeForOtherArea;
@property(retain, nonatomic) MFMailbox *mailboxBeingEdited; // @synthesize mailboxBeingEdited=_mailboxBeingEdited;
@property(copy, nonatomic) NSString *expressionGuess; // @synthesize expressionGuess=_expressionGuess;
@property(nonatomic) BOOL isSmartMailboxCriterion; // @synthesize isSmartMailboxCriterion=_isSmartMailboxCriterion;
@property(retain, nonatomic) NSMenu *dateQualifierMenu; // @synthesize dateQualifierMenu=_dateQualifierMenu;
@property(retain, nonatomic) NSMenu *criterionMenu; // @synthesize criterionMenu=_criterionMenu;
@property(nonatomic) __weak NSPopUpButton *unitsPopUp; // @synthesize unitsPopUp=_unitsPopUp;
@property(nonatomic) __weak NSDatePicker *otherDateFieldPicker; // @synthesize otherDateFieldPicker=_otherDateFieldPicker;
@property(nonatomic) __weak NSDatePicker *dateFieldPicker; // @synthesize dateFieldPicker=_dateFieldPicker;
@property(nonatomic) __weak NSTextField *expressionOtherNumberField; // @synthesize expressionOtherNumberField=_expressionOtherNumberField;
@property(nonatomic) __weak NSTextField *expressionNumberField; // @synthesize expressionNumberField=_expressionNumberField;
@property(nonatomic) __weak NSTextField *expressionStringField; // @synthesize expressionStringField=_expressionStringField;
@property(nonatomic) __weak NSPopUpButton *qualifierPopUp; // @synthesize qualifierPopUp=_qualifierPopUp;
@property(nonatomic) __weak NSPopUpButton *criterionPopUp; // @synthesize criterionPopUp=_criterionPopUp;
@property(nonatomic) __weak NSView *currentView; // @synthesize currentView=_currentView;
@property(retain, nonatomic) NSButton *addButton; // @synthesize addButton=_addButton;
@property(retain, nonatomic) NSButton *removeButton; // @synthesize removeButton=_removeButton;
@property(nonatomic) __weak CriteriaUIHelper *owner; // @synthesize owner=_owner;
@property(retain, nonatomic) MailboxesChooser *mailboxesChooser; // @synthesize mailboxesChooser=_mailboxesChooser;
@property(retain, nonatomic) NSNumberFormatter *daysOldFormatter; // @synthesize daysOldFormatter=_daysOldFormatter;
@property(retain, nonatomic) NSNumberFormatter *daysFormatter; // @synthesize daysFormatter=_daysFormatter;
@property(retain, nonatomic) NSView *flaggedStatusView; // @synthesize flaggedStatusView=_flaggedStatusView;
@property(retain, nonatomic) NSView *attachmentTypeView; // @synthesize attachmentTypeView=_attachmentTypeView;
@property(retain, nonatomic) NSView *dateRangeDatesView; // @synthesize dateRangeDatesView=_dateRangeDatesView;
@property(retain, nonatomic) NSView *beforeAfterDatesView; // @synthesize beforeAfterDatesView=_beforeAfterDatesView;
@property(retain, nonatomic) NSView *daysAgoRangeDatesView; // @synthesize daysAgoRangeDatesView=_daysAgoRangeDatesView;
@property(retain, nonatomic) NSView *inThelastDaysDatesView; // @synthesize inThelastDaysDatesView=_inThelastDaysDatesView;
@property(retain, nonatomic) NSView *daysAgoDatesView; // @synthesize daysAgoDatesView=_daysAgoDatesView;
@property(retain, nonatomic) NSView *simpleDatesView; // @synthesize simpleDatesView=_simpleDatesView;
@property(retain, nonatomic) NSView *daysOldDatesView; // @synthesize daysOldDatesView=_daysOldDatesView;
@property(retain, nonatomic) NSView *mailboxesView; // @synthesize mailboxesView=_mailboxesView;
@property(retain, nonatomic) NSView *accountOrGroupView; // @synthesize accountOrGroupView=_accountOrGroupView;
@property(retain, nonatomic) NSView *simpleCriteriaView; // @synthesize simpleCriteriaView=_simpleCriteriaView;
@property(retain, nonatomic) NSView *headerCriteriaView; // @synthesize headerCriteriaView=_headerCriteriaView;
// - (void).cxx_destruct;	// IMP=0x0000000100126e2b
- (void)ownerSearchAreaChanged:(id)arg1;	// IMP=0x0000000100126833
- (void)mailboxCriterionPopUpChangedSelection:(id)arg1;	// IMP=0x00000001001266b9
- (void)makeRemoveButtonEnabled:(BOOL)arg1;	// IMP=0x000000010012666d
- (void)criterionPopupChanged:(id)arg1;	// IMP=0x0000000100126558
- (void)_criterionPopupWillPopup:(id)arg1;	// IMP=0x0000000100126298
- (void)qualifierPopupChanged:(id)arg1;	// IMP=0x000000010012621a
- (BOOL)_populateQualifierPopup;	// IMP=0x00000001001255e0
- (void)putHeaderCriteriaInPopUpMenu;	// IMP=0x00000001001252d9
- (id)_timeSince1970StringFromDatePicker:(id)arg1 atEndOfDay:(BOOL)arg2;	// IMP=0x0000000100125223
- (id)_subcriteriaForRelativeDatesFrom:(long long)arg1 to:(long long)arg2 units:(long long)arg3 criterionType:(long long)arg4;	// IMP=0x0000000100125039
- (void)_insertBestGuessForExpressionField;	// IMP=0x0000000100124b10
- (void)_configureViewForQualifierTag:(long long)arg1 criterion:(id)arg2;	// IMP=0x0000000100123df5
- (void)_setEnglishStringsForPopUpMenuHeaderItems:(id)arg1;	// IMP=0x0000000100123c00
- (id)criterion;	// IMP=0x0000000100122490
- (void)configureForCriterion:(id)arg1;	// IMP=0x0000000100120f7c
- (id)_menuUsingInfo:(struct menuItemInfo *)arg1 length:(long long)arg2;	// IMP=0x000000010012098c
- (void)setIsSmartMailboxCriterion:(BOOL)arg1 mailbox:(id)arg2;	// IMP=0x000000010012085b
- (void)awakeFromNib;	// IMP=0x00000001001204b6
@property(nonatomic) long long criterionType;
- (void)dealloc;	// IMP=0x00000001001203b8

@end

