//
//     Generated by class-dump 3.5b1 (64 bit) (Debug version compiled Dec  3 2019 19:59:57).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSPopUpButton.h>

@interface DefaultApplicationPopUpButton : NSPopUpButton
{
}

- (void)_selectApplication:(id)arg1;	// IMP=0x000000010012b7c7
- (void)_setDefaultEmailHandler:(struct __CFURL *)arg1;	// IMP=0x000000010012b779
- (void)refreshApplicationList;	// IMP=0x000000010008062f

@end

