//
//     Generated by class-dump 3.5b1 (64 bit) (Debug version compiled Dec  3 2019 19:59:57).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "_NSReaderDelegate-Protocol.h"

@class NSArray, NSDate, NSDictionary, NSMutableDictionary, NSString, NSURL;

@interface EditableWebMessageDocument : NSObject <_NSReaderDelegate>
{
    NSMutableDictionary *_attachmentsByURL;	// 8 = 0x8
    NSMutableDictionary *_backgroundImageAttachments;	// 16 = 0x10
    BOOL _shouldDownloadRemoteURLs;	// 24 = 0x18
    int _uniqueIdentifier;	// 28 = 0x1c
    NSURL *_baseURL;	// 32 = 0x20
    NSArray *_attachments;	// 40 = 0x28
    NSURL *_imageArchiveURL;	// 48 = 0x30
    NSDictionary *_remoteAttachments;	// 56 = 0x38
    NSArray *_savedUserAttachmentsOrdering;	// 64 = 0x40
    NSURL *_imageArchiveDownloadURL;	// 72 = 0x48
    NSDate *_expirationDate;	// 80 = 0x50
}

+ (void)documentWillClose:(id)arg1;	// IMP=0x000000010013a6cd
+ (id)documentWithUniqueIdentifier:(int)arg1;	// IMP=0x000000010013a512
+ (void)document:(id *)arg1 attachment:(id *)arg2 forURL:(id)arg3;	// IMP=0x000000010013a36f
+ (void)document:(id *)arg1 attachmentController:(id *)arg2 forURL:(id)arg3;	// IMP=0x000000010013a057
+ (id)openDocuments;	// IMP=0x0000000100139fc9
+ (void)initialize;	// IMP=0x0000000100139f72
@property(retain, nonatomic) NSDate *expirationDate; // @synthesize expirationDate=_expirationDate;
@property(retain, nonatomic) NSURL *imageArchiveDownloadURL; // @synthesize imageArchiveDownloadURL=_imageArchiveDownloadURL;
@property(readonly, copy, nonatomic) NSArray *savedUserAttachmentsOrdering; // @synthesize savedUserAttachmentsOrdering=_savedUserAttachmentsOrdering;
@property(copy, nonatomic) NSDictionary *remoteAttachments; // @synthesize remoteAttachments=_remoteAttachments;
@property(retain, nonatomic) NSURL *imageArchiveURL; // @synthesize imageArchiveURL=_imageArchiveURL;
@property(readonly, copy, nonatomic) NSArray *attachments; // @synthesize attachments=_attachments;
@property(readonly, nonatomic) int uniqueIdentifier; // @synthesize uniqueIdentifier=_uniqueIdentifier;
@property(nonatomic) BOOL shouldDownloadRemoteURLs; // @synthesize shouldDownloadRemoteURLs=_shouldDownloadRemoteURLs;
@property(retain, nonatomic) NSURL *baseURL; // @synthesize baseURL=_baseURL;
// - (void).cxx_destruct;	// IMP=0x000000010013c1e7
- (id)attachmentElementEnumeratorWithOptions:(unsigned long long)arg1;	// IMP=0x0000000100056afd
- (id)attachmentForURLString:(id)arg1;	// IMP=0x000000010013c09c
@property(readonly, copy, nonatomic) NSArray *attachmentsIncludingBackgrounds;
- (void)saveAttachmentsWithURLsAsBackgroundAttachments:(id)arg1;	// IMP=0x0000000100058d83
- (id)backgroundImageAttachments;	// IMP=0x00000001000617e4
- (id)mailDropBannerMarkupWithSize:(unsigned long long)arg1;	// IMP=0x000000010013ba1e
- (void)addMailDropBannerWithSize:(unsigned long long)arg1;	// IMP=0x000000010013b956
- (void)convertAOSBoundAttachmentsToLinks;	// IMP=0x000000010013af4d
- (id)userImageDictionaryFromAttachment:(id)arg1 withURL:(id)arg2;	// IMP=0x000000010013ae7e
- (void)clearAttachmentsByURL;	// IMP=0x000000010013ae64
@property(readonly, copy, nonatomic) NSDictionary *attachmentsByURL;
@property(readonly, nonatomic) BOOL hasAttachments;
- (void)removeAttachmentForURL:(id)arg1;	// IMP=0x000000010013ae08
- (void)addAttachments:(id)arg1;	// IMP=0x000000010013ac42
- (void)addAttachment:(id)arg1 forURL:(id)arg2;	// IMP=0x000000010013a9d4
- (id)attachmentForURL:(id)arg1;	// IMP=0x000000010013a946
- (id)init;	// IMP=0x000000010013a877
- (id)initForDisplay:(BOOL)arg1;	// IMP=0x000000010013a747
- (id)fileWrapperForURL:(id)arg1;	// IMP=0x000000010013a491

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

