//
//     Generated by class-dump 3.5b1 (64 bit) (Debug version compiled Dec  3 2019 19:59:57).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "EditableWebMessageDocument.h"

@class NSArray, NSDictionary, NSMutableArray, NSMutableDictionary;

@interface EditableWebMessageDocumentWK2 : EditableWebMessageDocument
{
    NSMutableArray *_wkAttachments;	// 88 = 0x58
    NSMutableDictionary *_attachmentURLsByIdentifier;	// 96 = 0x60
}

// - (void).cxx_destruct;	// IMP=0x000000010013ca6d
@property(readonly, copy, nonatomic) NSDictionary *attachmentInfoByURL;
- (void)useAttachmentForURL:(id)arg1 whenAttachmentWithIdentifierIsInserted:(id)arg2;	// IMP=0x000000010013c6f0
- (void)didRemoveAttachment:(id)arg1;	// IMP=0x000000010013c6d3
- (void)didInsertAttachment:(id)arg1;	// IMP=0x000000010013c40d
@property(readonly, copy, nonatomic) NSArray *wkAttachments;
- (id)attachmentElementEnumeratorWithOptions:(unsigned long long)arg1;	// IMP=0x000000010013c390
- (id)attachments;	// IMP=0x000000010013c307
- (id)initForDisplay:(BOOL)arg1;	// IMP=0x000000010013c25c

@end

