//
//     Generated by class-dump 3.5b1 (64 bit) (Debug version compiled Dec  3 2019 19:59:57).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSTitlebarAccessoryViewController.h>

@class FavoritesBarView, MailBarContainerView;

@interface FavoritesBarViewController : NSTitlebarAccessoryViewController
{
    FavoritesBarView *_favoritesBarView;	// 16 = 0x10
}

@property(nonatomic) __weak FavoritesBarView *favoritesBarView; // @synthesize favoritesBarView=_favoritesBarView;
// - (void).cxx_destruct;	// IMP=0x000000010015bd75
@property(retain) MailBarContainerView *view;

@end

