//
//     Generated by class-dump 3.5b1 (64 bit) (Debug version compiled Dec  3 2019 19:59:57).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "FavoriteHoverViewDirectionProtocol-Protocol.h"
#import "NSOutlineViewDataSource-Protocol.h"
#import "NSOutlineViewDelegate-Protocol.h"

@class FavoritesMenuOutlineView, NSScrollView, NSString, NSTimer, NSWindow, _FavoriteMenuScrollHoverView;
@protocol FavoritesMenuDelegateProtocol, MFUIMailbox;

@interface FavoritesMenuController : NSObject <FavoriteHoverViewDirectionProtocol, NSOutlineViewDataSource, NSOutlineViewDelegate>
{
    BOOL _isScrolling;	// 8 = 0x8
    BOOL _isOpeningMenu;	// 9 = 0x9
    BOOL _needsScrollers;	// 10 = 0xa
    id <FavoritesMenuDelegateProtocol> _delegate;	// 16 = 0x10
    NSWindow *_window;	// 24 = 0x18
    NSWindow *_parentWindow;	// 32 = 0x20
    id <MFUIMailbox> _mailbox;	// 40 = 0x28
    NSScrollView *_scrollView;	// 48 = 0x30
    FavoritesMenuOutlineView *_outlineView;	// 56 = 0x38
    id _mouseClickedMonitor;	// 64 = 0x40
    _FavoriteMenuScrollHoverView *_upScrollHoverView;	// 72 = 0x48
    _FavoriteMenuScrollHoverView *_downScrollHoverView;	// 80 = 0x50
    NSTimer *_scrollTimer;	// 88 = 0x58
}

+ (void)closeExitingMenu;	// IMP=0x000000010015cdfe
@property(retain, nonatomic) NSTimer *scrollTimer; // @synthesize scrollTimer=_scrollTimer;
@property(nonatomic) BOOL needsScrollers; // @synthesize needsScrollers=_needsScrollers;
@property(retain, nonatomic) _FavoriteMenuScrollHoverView *downScrollHoverView; // @synthesize downScrollHoverView=_downScrollHoverView;
@property(retain, nonatomic) _FavoriteMenuScrollHoverView *upScrollHoverView; // @synthesize upScrollHoverView=_upScrollHoverView;
@property(nonatomic) BOOL isOpeningMenu; // @synthesize isOpeningMenu=_isOpeningMenu;
@property(retain, nonatomic) id mouseClickedMonitor; // @synthesize mouseClickedMonitor=_mouseClickedMonitor;
@property(retain, nonatomic) FavoritesMenuOutlineView *outlineView; // @synthesize outlineView=_outlineView;
@property(retain, nonatomic) NSScrollView *scrollView; // @synthesize scrollView=_scrollView;
@property(readonly, nonatomic) id <MFUIMailbox> mailbox; // @synthesize mailbox=_mailbox;
@property(readonly, nonatomic) NSWindow *parentWindow; // @synthesize parentWindow=_parentWindow;
@property(retain, nonatomic) NSWindow *window; // @synthesize window=_window;
@property(nonatomic) BOOL isScrolling; // @synthesize isScrolling=_isScrolling;
@property(nonatomic) __weak id <FavoritesMenuDelegateProtocol> delegate; // @synthesize delegate=_delegate;
// - (void).cxx_destruct;	// IMP=0x000000010015ffca
- (void)stopScrolling:(long long)arg1;	// IMP=0x000000010015fd67
- (void)stopScrolling;	// IMP=0x000000010015fd53
- (void)startScrolling:(long long)arg1;	// IMP=0x000000010015faf8
- (void)updateScrollArrows;	// IMP=0x000000010015f898
- (void)_scrollToNextPoint:(id)arg1;	// IMP=0x000000010015f597
- (BOOL)outlineView:(id)arg1 acceptDrop:(id)arg2 item:(id)arg3 childIndex:(long long)arg4;	// IMP=0x000000010015f318
- (BOOL)_canDragMessageIntoMailbox:(id)arg1;	// IMP=0x000000010015f2c4
- (unsigned long long)outlineView:(id)arg1 validateDrop:(id)arg2 proposedItem:(id)arg3 proposedChildIndex:(long long)arg4;	// IMP=0x000000010015f2a3
- (unsigned long long)_dragOperationForCurrentEvent;	// IMP=0x000000010015f21f
- (BOOL)outlineView:(id)arg1 shouldShowOutlineCellForItem:(id)arg2;	// IMP=0x000000010015f217
- (id)outlineView:(id)arg1 rowViewForItem:(id)arg2;	// IMP=0x000000010015f187
- (id)outlineView:(id)arg1 viewForTableColumn:(id)arg2 item:(id)arg3;	// IMP=0x000000010015eedf
- (BOOL)outlineView:(id)arg1 isItemExpandable:(id)arg2;	// IMP=0x000000010015ee76
- (id)outlineView:(id)arg1 child:(long long)arg2 ofItem:(id)arg3;	// IMP=0x000000010015ec00
- (long long)outlineView:(id)arg1 numberOfChildrenOfItem:(id)arg2;	// IMP=0x000000010015e9e2
- (id)_nibForFavoriteMenuItemView;	// IMP=0x000000010015e935
- (id)_titleForTopLevelMailbox:(id)arg1;	// IMP=0x000000010015e81d
- (void)presentPopupAtLocation:(struct CGPoint)arg1;	// IMP=0x000000010015dac5
- (void)_insertOutlineViewInScrollView;	// IMP=0x000000010015d7e2
- (void)_constrainWindowToScreen;	// IMP=0x000000010015d5eb
- (void)_sizeWindowToFitCells;	// IMP=0x000000010015d401
- (struct CGSize)_windowSizeForOutlineViewSize:(struct CGSize)arg1;	// IMP=0x000000010015d3f3
- (void)_mouseClickedInApplicationWithEvent:(id)arg1;	// IMP=0x000000010015d3e1
- (void)_dragEnded:(id)arg1;	// IMP=0x000000010015d3cf
- (void)_applicationShouldClosePopup:(id)arg1;	// IMP=0x000000010015d398
- (void)closePopup;	// IMP=0x000000010015d225
- (void)_cleanupMenu;	// IMP=0x000000010015d042
- (void)dealloc;	// IMP=0x000000010015cf86
- (id)init;	// IMP=0x000000010015ceb7
- (id)initWithMailbox:(id)arg1 atWindow:(id)arg2;	// IMP=0x000000010015ce1e

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

