//
//     Generated by class-dump 3.5b1 (64 bit) (Debug version compiled Dec  3 2019 19:59:57).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSTextView.h>

@protocol NSTextAttachmentCell;

@interface HeaderTextView : NSTextView
{
    BOOL _shouldClearSelectionOnFocusChange;	// 108 = 0x6c
    id <NSTextAttachmentCell> _attachmentCell;	// 112 = 0x70
    struct CGSize _contentSize;	// 120 = 0x78
    struct CGRect _attachmentCellRect;	// 136 = 0x88
}

@property(nonatomic) struct CGSize contentSize; // @synthesize contentSize=_contentSize;
@property(nonatomic) struct CGRect attachmentCellRect; // @synthesize attachmentCellRect=_attachmentCellRect;
@property(retain, nonatomic) id <NSTextAttachmentCell> attachmentCell; // @synthesize attachmentCell=_attachmentCell;
@property(nonatomic) BOOL shouldClearSelectionOnFocusChange; // @synthesize shouldClearSelectionOnFocusChange=_shouldClearSelectionOnFocusChange;
// - (void).cxx_destruct;	// IMP=0x000000010016e4ac
- (BOOL)writeSelectionToPasteboard:(id)arg1 type:(id)arg2;	// IMP=0x0000000100077324
- (id)_selectedString;	// IMP=0x000000010016de66
- (id)_selectedAttributedString;	// IMP=0x00000001000776d7
- (id)writablePasteboardTypes;	// IMP=0x00000001000770bb
- (void)mouseMoved:(id)arg1;	// IMP=0x0000000100045e07
- (void)mouseExited:(id)arg1;	// IMP=0x00000001000461c9
- (void)keyDown:(id)arg1;	// IMP=0x000000010016db17
- (void)mouseEntered:(id)arg1;	// IMP=0x0000000100045852
- (void)rightMouseDown:(id)arg1;	// IMP=0x000000010016d909
- (void)mouseDown:(id)arg1;	// IMP=0x000000010004a2c3
- (void)cursorUpdate:(id)arg1;	// IMP=0x0000000100045d19
- (id)_attachmentCellForCharacterAtIndex:(unsigned long long)arg1;	// IMP=0x0000000100045c01
- (unsigned long long)_glyphIndexForPoint:(struct CGPoint)arg1 glyphRect:(struct CGRect *)arg2;	// IMP=0x0000000100045a21
- (void)resetCursorRects;	// IMP=0x000000010003dff4
- (struct CGSize)intrinsicContentSize;	// IMP=0x000000010003cad7
- (void)setConstrainedFrameSize:(struct CGSize)arg1;	// IMP=0x0000000100036ae8
- (BOOL)respondsToSelector:(SEL)arg1;	// IMP=0x000000010016d89f
- (BOOL)autoscroll:(id)arg1;	// IMP=0x000000010016d7bb
- (BOOL)resignFirstResponder;	// IMP=0x000000010006aec4
- (BOOL)canBecomeKeyView;	// IMP=0x000000010006b171

@end

