//
//     Generated by class-dump 3.5b1 (64 bit) (Debug version compiled Dec  3 2019 19:59:57).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class MCMessage, NSArray;

@protocol IMAPUserAgent <NSObject>
@property(readonly, nonatomic) BOOL addInvitationsToCalendarAutomatically;
@property(readonly, copy, nonatomic) NSArray *headersRequiredForParentalControl;
@property(readonly, copy, nonatomic) NSArray *headersRequiredForRouting;
@property(readonly, nonatomic) BOOL visibleMessageViewerExists;
- (BOOL)doParentalControlProcessingForMessage:(MCMessage *)arg1;
- (void)addInvitationsToCalendarFromMessages:(NSArray *)arg1;
@end

