//
//     Generated by class-dump 3.5b1 (64 bit) (Debug version compiled Dec  3 2019 19:59:57).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class ImportAssistant, NSArray, NSMutableArray, NSString;

@interface Importer : NSObject
{
    NSMutableArray *_importArray;	// 8 = 0x8
    BOOL _importCanceled;	// 16 = 0x10
    ImportAssistant *_delegate;	// 24 = 0x18
}

@property(nonatomic) BOOL importCanceled; // @synthesize importCanceled=_importCanceled;
@property(retain, nonatomic) ImportAssistant *delegate; // @synthesize delegate=_delegate;
// - (void).cxx_destruct;	// IMP=0x000000010018bd92
@property(readonly, copy, nonatomic) NSString *importFinishedText;
- (void)sortImportArray;	// IMP=0x000000010018bbc6
@property(readonly, nonatomic) unsigned long long countOfEnabledItems;
- (void)insertObject:(id)arg1 inImportArrayAtIndex:(unsigned long long)arg2;	// IMP=0x000000010018ba6d
- (void)clearImportArray;	// IMP=0x000000010018ba57
@property(readonly, nonatomic) unsigned long long countOfImportArray;
@property(readonly, copy, nonatomic) NSArray *importArray;
@property(readonly, copy, nonatomic) NSString *name;
- (id)init;	// IMP=0x000000010018b99a

@end

