//
//     Generated by class-dump 3.5b1 (64 bit) (Debug version compiled Dec  3 2019 19:59:57).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "BasicComposeContext.h"

@class PopoutAnimationController;
@protocol PopoutAnimationContentProvider;

@interface InteractiveComposeContext : BasicComposeContext
{
    id <PopoutAnimationContentProvider> _animationSource;	// 8 = 0x8
    PopoutAnimationController *_animationController;	// 16 = 0x10
}

@property(retain, nonatomic) PopoutAnimationController *animationController; // @synthesize animationController=_animationController;
@property(readonly, nonatomic) __weak id <PopoutAnimationContentProvider> animationSource; // @synthesize animationSource=_animationSource;
// - (void).cxx_destruct;	// IMP=0x000000010018cf4a
- (id)_newToolbarImageForWindow:(id)arg1;	// IMP=0x000000010018caa6
- (void)loadCompleted:(id)arg1;	// IMP=0x000000010018c8e2
- (void)controllerInitialized:(id)arg1;	// IMP=0x000000010018c81d
- (void)presentComposeViewController:(id)arg1 completion:(id)arg2;	// IMP=0x000000010018c517
- (BOOL)isInteractive;	// IMP=0x000000010018c50c
- (id)initWithType:(long long)arg1 targetMessages:(id)arg2 sourceContentProvider:(id)arg3;	// IMP=0x000000010018c346
- (id)initWithType:(long long)arg1 targetMessages:(id)arg2;	// IMP=0x000000010018c331

@end

