//
//     Generated by class-dump 3.5b1 (64 bit) (Debug version compiled Dec  3 2019 19:59:57).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class MCActivityMonitor, NSProgressIndicator, NSString, NSTextField, NSView;
@protocol LoadingOverlayModalDelegate;

@interface LoadingOverlay : NSObject
{
    MCActivityMonitor *_activityMonitor;	// 8 = 0x8
    NSView *_overlayView;	// 16 = 0x10
    NSProgressIndicator *_progressIndicator;	// 24 = 0x18
    NSTextField *_statusMessageField;	// 32 = 0x20
    id <LoadingOverlayModalDelegate> _modalDelegate;	// 40 = 0x28
}

@property(nonatomic) __weak id <LoadingOverlayModalDelegate> modalDelegate; // @synthesize modalDelegate=_modalDelegate;
@property(nonatomic) __weak NSTextField *statusMessageField; // @synthesize statusMessageField=_statusMessageField;
@property(nonatomic) __weak NSProgressIndicator *progressIndicator; // @synthesize progressIndicator=_progressIndicator;
@property(retain, nonatomic) NSView *overlayView; // @synthesize overlayView=_overlayView;
// - (void).cxx_destruct;	// IMP=0x0000000100193fcb
- (void)stop;	// IMP=0x0000000100193ee1
- (void)_activityEnded:(id)arg1;	// IMP=0x00000001000531dc
@property(retain, nonatomic) NSString *statusMessage;
@property(retain, nonatomic) MCActivityMonitor *activityMonitor;
- (void)displayInSuperviewAfterDelay:(id)arg1;	// IMP=0x0000000100193ded
- (void)displayInSuperview:(id)arg1;	// IMP=0x0000000100193b35
- (void)dealloc;	// IMP=0x0000000100053bad
- (id)init;	// IMP=0x0000000100193b21
- (id)initWithModalDelegate:(id)arg1;	// IMP=0x0000000100052d7c

@end

