//
//     Generated by class-dump 3.5b1 (64 bit) (Debug version compiled Dec  3 2019 19:59:57).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface MailUsageStatistics : NSObject
{
}

+ (void)_messageTraceLoadedBundles;	// IMP=0x00000001001d2eb8
+ (void)_messageTracePreferences;	// IMP=0x00000001001d1cdc
+ (void)_messageTraceUILayout;	// IMP=0x00000001001d1bfb
+ (void)_messageTraceUsage;	// IMP=0x00000001001d02bc
+ (BOOL)_imapAccount:(id)arg1 hasCapability:(unsigned long long)arg2;	// IMP=0x00000001001d023d
+ (void)_messageTraceAccounts;	// IMP=0x0000000100043b78
+ (void)_messageTrace:(id)arg1;	// IMP=0x00000001001d00b7
+ (void)startMessageTracing;	// IMP=0x00000001001cfdd0

@end

