//
//     Generated by class-dump 3.5b1 (64 bit) (Debug version compiled Dec  3 2019 19:59:57).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <MailUI/MUIWebAttachment.h>

@class MCAttachment, MCMessage, NSError, NSOperationQueue, NSURL;

@interface MailWebAttachment : MUIWebAttachment
{
    MCMessage *_parentMessage;	// 8 = 0x8
    MCAttachment *_backingAttachment;	// 16 = 0x10
    NSURL *_mailDownloadsFileURL;	// 24 = 0x18
    id _downloadCompletionBlock;	// 32 = 0x20
    NSOperationQueue *_downloadQueue;	// 40 = 0x28
    NSError *_downloadError;	// 48 = 0x30
}

+ (id)keyPathsForValuesAffectingValueForKey:(id)arg1;	// IMP=0x00000001001d3ad2
@property(retain, nonatomic) NSError *downloadError; // @synthesize downloadError=_downloadError;
@property(retain) NSOperationQueue *downloadQueue; // @synthesize downloadQueue=_downloadQueue;
@property(copy) id downloadCompletionBlock; // @synthesize downloadCompletionBlock=_downloadCompletionBlock;
@property(retain) NSURL *mailDownloadsFileURL; // @synthesize mailDownloadsFileURL=_mailDownloadsFileURL;
@property(readonly, nonatomic) MCAttachment *backingAttachment; // @synthesize backingAttachment=_backingAttachment;
@property(nonatomic) __weak MCMessage *parentMessage; // @synthesize parentMessage=_parentMessage;
// - (void).cxx_destruct;	// IMP=0x00000001001d402d
- (BOOL)isAutoArchiveAttachment;	// IMP=0x00000001001d3f75
- (void)_addPrivateAttributes:(id)arg1;	// IMP=0x0000000100091382
- (void)startDownloadingIfNeededWithProgress:(id)arg1 completionBlock:(id)arg2;	// IMP=0x00000001001d3cb1
- (id)downloadProgress;	// IMP=0x00000001001d3c32
- (BOOL)shouldAlwaysAutomaticallyDownload;	// IMP=0x0000000100049e5f
- (BOOL)isDataDownloaded;	// IMP=0x0000000100049deb
- (id)uti;	// IMP=0x00000001001d3b90
- (id)downloadDirectory;	// IMP=0x00000001001d3a7b
- (void)_attachmentDataDidChange;	// IMP=0x00000001001d38f4
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;	// IMP=0x00000001001d3733
- (void)writeToURL:(id)arg1;	// IMP=0x00000001001d3603
- (id)fileURL;	// IMP=0x000000010009101c
- (id)filenameForSaving;	// IMP=0x00000001001d3584
- (id)filename;	// IMP=0x0000000100049ced
- (unsigned long long)fileSize;	// IMP=0x0000000100092a73
- (id)mimeType;	// IMP=0x0000000100049c6e
- (id)iconImage;	// IMP=0x0000000100049d6c
- (id)fileWrapper;	// IMP=0x0000000100049bd7
- (BOOL)conformsToProtocol:(id)arg1;	// IMP=0x000000010009197f
- (void)dealloc;	// IMP=0x000000010004a134
- (void)encodeWithCoder:(id)arg1;	// IMP=0x00000001001d3491
- (id)initWithCoder:(id)arg1;	// IMP=0x00000001001d33c2
- (id)initWithFileWrapper:(id)arg1;	// IMP=0x00000001001d328d
- (id)initWithMCAttachment:(id)arg1;	// IMP=0x0000000100049a9f

@end

