//
//     Generated by class-dump 3.5b1 (64 bit) (Debug version compiled Dec  3 2019 19:59:57).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/__NSInspectorBarItemController.h>

@class NSNumberFormatter, NSPopUpButton;

@interface MailInspectorBarItemController : __NSInspectorBarItemController
{
    NSNumberFormatter *_fontSizeFormatter;	// 128 = 0x80
    NSPopUpButton *_fontSizePopUpButton;	// 136 = 0x88
    NSPopUpButton *_listPopUpButton;	// 144 = 0x90
    NSPopUpButton *_indentationPopUpButton;	// 152 = 0x98
}

+ (id)keyForItemIdentifier:(id)arg1;	// IMP=0x00000001001c1403
+ (id)supportedInspectorItemIdentifiers;	// IMP=0x00000001001c133b
+ (id)nibName;	// IMP=0x00000001001c131c
@property(retain, nonatomic) NSPopUpButton *indentationPopUpButton; // @synthesize indentationPopUpButton=_indentationPopUpButton;
@property(retain, nonatomic) NSPopUpButton *listPopUpButton; // @synthesize listPopUpButton=_listPopUpButton;
@property(retain, nonatomic) NSPopUpButton *fontSizePopUpButton; // @synthesize fontSizePopUpButton=_fontSizePopUpButton;
@property(readonly, nonatomic) NSNumberFormatter *fontSizeFormatter; // @synthesize fontSizeFormatter=_fontSizeFormatter;
// - (void).cxx_destruct;	// IMP=0x00000001001c253d
- (void)updateColorWellColors;	// IMP=0x00000001001c2294
- (void)changeColor:(id)arg1;	// IMP=0x00000001001c2282
- (void)changeFontSize:(id)arg1;	// IMP=0x00000001001c2210
- (void)updateInspectorItemViewsWithIdentifiers:(id)arg1 fontFamilyName:(id)arg2 fontFaceName:(id)arg3 fontPointSize:(double)arg4 foregroundColor:(id)arg5 backgroundColor:(id)arg6 boldTrait:(BOOL)arg7 italicTrait:(BOOL)arg8 underlineStyle:(id)arg9 strikeThrough:(id)arg10 alignment:(long long)arg11 lineSpacingStyle:(id)arg12 textList:(id)arg13;	// IMP=0x00000001001c1d23
- (void)supportedInspectorItemViewsDidLoad;	// IMP=0x00000001001c1580
- (BOOL)inspectorBarItemCanBeDetached:(id)arg1;	// IMP=0x00000001001c14e0
- (id)initWithInspectorBar:(id)arg1;	// IMP=0x00000001001c12b7

@end

