//
//     Generated by class-dump 3.5b1 (64 bit) (Debug version compiled Dec  3 2019 19:59:57).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSViewController.h>

@class ACAccount, NSNumber;

@interface MailboxBehaviorsController : NSViewController
{
    BOOL _accountNeedsSaving;	// 16 = 0x10
}

+ (id)keyPathsForValuesAffectingAccountDeletesMessagesInPlace;	// IMP=0x00000001001aadff
+ (id)keyPathsForValuesAffectingAccountStoresTrashOnServer;	// IMP=0x00000001001aac1d
+ (id)keyPathsForValuesAffectingAccountStoresJunkOnServer;	// IMP=0x00000001001aaa3b
+ (id)keyPathsForValuesAffectingAccountStoresSentMessagesOnServer;	// IMP=0x00000001001aa859
+ (id)keyPathsForValuesAffectingAccountStoresDraftsOnServer;	// IMP=0x00000001001aa677
+ (id)keyPathsForValuesAffectingAccountNumberOfDaysToKeepTrash;	// IMP=0x00000001001aa47a
+ (id)keyPathsForValuesAffectingAccountNumberOfDaysToKeepJunk;	// IMP=0x00000001001aa27d
@property(nonatomic) BOOL accountNeedsSaving; // @synthesize accountNeedsSaving=_accountNeedsSaving;
@property(retain, nonatomic) NSNumber *accountDeletesMessagesInPlace;
@property(nonatomic) BOOL accountStoresTrashOnServer;
@property(nonatomic) BOOL accountStoresJunkOnServer;
@property(nonatomic) BOOL accountStoresSentMessagesOnServer;
@property(nonatomic) BOOL accountStoresDraftsOnServer;
@property(nonatomic) long long accountNumberOfDaysToKeepTrash;
@property(nonatomic) long long accountNumberOfDaysToKeepJunk;
@property(retain) ACAccount *representedObject;

@end

