//
//     Generated by class-dump 3.5b1 (64 bit) (Debug version compiled Dec  3 2019 19:59:57).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "MailboxOutlineItemControllerDelegate-Protocol.h"
#import "MailboxSelectionOwner-Protocol.h"
#import "MailboxesOutlineViewDelegate-Protocol.h"
#import "NSOutlineViewDataSource-Protocol.h"

@class MFMailbox, MailboxesOutlineView, NSArray, NSDictionary, NSMapTable, NSString, NSWindow;
@protocol MailboxesOutlineViewControllerDelegate;

@interface MailboxesOutlineViewController : NSObject <MailboxesOutlineViewDelegate, MailboxSelectionOwner, NSOutlineViewDataSource, MailboxOutlineItemControllerDelegate>
{
    double _idealOutlineViewWidth;	// 8 = 0x8
    id <MailboxesOutlineViewControllerDelegate> _delegate;	// 16 = 0x10
    NSMapTable *_itemControllers;	// 24 = 0x18
    MailboxesOutlineView *_outlineView;	// 32 = 0x20
    MFMailbox *_clickedMailbox;	// 40 = 0x28
    long long _reloadingCount;	// 48 = 0x30
    long long _wantsToEditInlineCount;	// 56 = 0x38
    NSDictionary *_accountsByLegacyAccountURLStrings;	// 64 = 0x40
    MFMailbox *_errorMailbox;	// 72 = 0x48
    NSString *_errorMailboxName;	// 80 = 0x50
}

@property(copy) NSString *errorMailboxName; // @synthesize errorMailboxName=_errorMailboxName;
@property(retain) MFMailbox *errorMailbox; // @synthesize errorMailbox=_errorMailbox;
@property(copy) NSDictionary *accountsByLegacyAccountURLStrings; // @synthesize accountsByLegacyAccountURLStrings=_accountsByLegacyAccountURLStrings;
@property long long wantsToEditInlineCount; // @synthesize wantsToEditInlineCount=_wantsToEditInlineCount;
@property long long reloadingCount; // @synthesize reloadingCount=_reloadingCount;
@property(retain) MFMailbox *clickedMailbox; // @synthesize clickedMailbox=_clickedMailbox;
@property(retain) MailboxesOutlineView *outlineView; // @synthesize outlineView=_outlineView;
// - (void).cxx_destruct;	// IMP=0x00000001001b94e5
- (void)_didPresentErrorWithRecovery:(BOOL)arg1 contextInfo:(void *)arg2;	// IMP=0x00000001001b92a0
- (void)mailbox:(id)arg1 nameUpdated:(id)arg2;	// IMP=0x00000001001b8e35
- (unsigned long long)badgeCountForItem:(id)arg1;	// IMP=0x0000000100017f3b
- (id)mailboxesOutlineView;	// IMP=0x00000001001b8e21
- (void)outlineViewItemDidCollapse:(id)arg1;	// IMP=0x00000001001b8d7f
- (void)outlineViewItemDidExpand:(id)arg1;	// IMP=0x0000000100028675
- (void)didCloseContextMenu:(id)arg1;	// IMP=0x0000000100073dbf
- (void)willShowContextMenu:(id)arg1;	// IMP=0x000000010007124e
- (void)setFirstResponderAfterMouseDownOnOutlineView:(id)arg1;	// IMP=0x000000010004b781
- (void)selectAllInOutlineView:(id)arg1;	// IMP=0x00000001001b8d40
- (void)outlineView:(id)arg1 didAddRowView:(id)arg2 forRow:(long long)arg3;	// IMP=0x0000000100017758
- (void)outlineView:(id)arg1 didRemoveRowView:(id)arg2 forRow:(long long)arg3;	// IMP=0x0000000100028196
- (void)outlineViewSelectionDidChange:(id)arg1;	// IMP=0x000000010002956f
- (id)outlineView:(id)arg1 selectionIndexesForProposedSelection:(id)arg2;	// IMP=0x000000010004b284
- (BOOL)outlineView:(id)arg1 shouldCollapseItem:(id)arg2;	// IMP=0x0000000100017093
- (BOOL)outlineView:(id)arg1 shouldExpandItem:(id)arg2;	// IMP=0x00000001000283f8
- (double)outlineView:(id)arg1 heightOfRowByItem:(id)arg2;	// IMP=0x00000001000158ff
- (BOOL)outlineView:(id)arg1 isGroupItem:(id)arg2;	// IMP=0x0000000100015816
- (id)outlineView:(id)arg1 viewForTableColumn:(id)arg2 item:(id)arg3;	// IMP=0x0000000100015d11
- (id)outlineView:(id)arg1 rowViewForItem:(id)arg2;	// IMP=0x0000000100015c7e
- (unsigned long long)_outlineView:(id)arg1 validateDrop:(id)arg2 proposedItem:(id)arg3 proposedChildIndex:(long long)arg4 allowStoreCreation:(BOOL)arg5;	// IMP=0x000000010008bdb6
- (unsigned long long)outlineView:(id)arg1 validateDrop:(id)arg2 proposedItem:(id)arg3 proposedChildIndex:(long long)arg4;	// IMP=0x000000010008bd35
- (BOOL)outlineView:(id)arg1 acceptDrop:(id)arg2 item:(id)arg3 childIndex:(long long)arg4;	// IMP=0x000000010008cc91
- (void)pasteboard:(id)arg1 provideDataForType:(id)arg2;	// IMP=0x00000001001b87e5
- (void)outlineView:(id)arg1 draggingSession:(id)arg2 endedAtPoint:(struct CGPoint)arg3 operation:(unsigned long long)arg4;	// IMP=0x00000001001b879f
- (BOOL)outlineView:(id)arg1 writeItems:(id)arg2 toPasteboard:(id)arg3;	// IMP=0x00000001001b8337
- (id)outlineView:(id)arg1 persistentObjectForItem:(id)arg2;	// IMP=0x00000001001b828d
- (void)_accountsDidChange:(id)arg1;	// IMP=0x00000001001b8221
- (id)_migrateMailboxPersistentID:(id)arg1;	// IMP=0x00000001001b7bfd
- (id)outlineView:(id)arg1 itemForPersistentObject:(id)arg2;	// IMP=0x0000000100029e43
- (id)_itemControllerForItem:(id)arg1 makeIfNecessary:(BOOL)arg2;	// IMP=0x00000001001b7b44
- (id)outlineView:(id)arg1 objectValueForTableColumn:(id)arg2 byItem:(id)arg3;	// IMP=0x0000000100017106
- (id)outlineView:(id)arg1 child:(long long)arg2 ofItem:(id)arg3;	// IMP=0x0000000100015432
- (BOOL)outlineView:(id)arg1 isItemExpandable:(id)arg2;	// IMP=0x0000000100016f3a
- (long long)outlineView:(id)arg1 numberOfChildrenOfItem:(id)arg2;	// IMP=0x00000001000150f8
@property(readonly, nonatomic) NSWindow *mailboxSelectionWindow;
- (void)_revealMailbox:(id)arg1;	// IMP=0x0000000100027c99
- (void)revealMailbox:(id)arg1;	// IMP=0x00000001001b7a2e
@property(readonly, copy, nonatomic) NSArray *sortedSectionItemsForTimeMachine;
@property(readonly, copy, nonatomic) NSArray *expandedItems;
- (BOOL)sectionIsExpanded:(id)arg1;	// IMP=0x00000001001b787f
- (BOOL)mailboxIsExpanded:(id)arg1;	// IMP=0x00000001001b77c9
- (void)selectPathsToMailboxes:(id)arg1 scrollToVisible:(BOOL)arg2;	// IMP=0x000000010002787a
- (void)selectPathsToMailboxes:(id)arg1;	// IMP=0x000000010002a14b
@property(readonly, nonatomic) BOOL isSelectedMailboxSpecial;
@property(readonly, nonatomic) MFMailbox *selectedMailbox;
@property(readonly, copy, nonatomic) NSArray *selectedMailboxes;
- (void)_mailboxPendingNameDidChange:(id)arg1;	// IMP=0x00000001001b75ae
- (void)_viewerPreferencesChanged:(id)arg1;	// IMP=0x000000010008582e
- (void)_userInfoDidChange:(id)arg1;	// IMP=0x00000001001b73fc
- (void)_displayCountDidChange:(id)arg1;	// IMP=0x00000001000305f0
- (void)_mailboxesActivityDidChange:(id)arg1;	// IMP=0x000000010002fb02
- (void)_sectionListingDidChange:(id)arg1;	// IMP=0x000000010002d1a4
- (void)_mailboxPublicStatusDidChange:(id)arg1;	// IMP=0x00000001001b72e8
- (void)_mailboxListingDidChange:(id)arg1;	// IMP=0x000000010002d8ce
- (void)_accountOfflineStatusDidChange:(id)arg1;	// IMP=0x00000001001b7153
- (void)_accountAdded:(id)arg1;	// IMP=0x00000001001b7017
- (void)rowDoubleClicked:(id)arg1;	// IMP=0x00000001001b6ee1
- (void)rowClicked:(id)arg1;	// IMP=0x000000010004b6a6
- (void)newMailboxClicked:(id)arg1;	// IMP=0x00000001001b6d4e
- (void)alertClicked:(id)arg1;	// IMP=0x00000001001b6cb3
- (id)_mailboxForItem:(id)arg1;	// IMP=0x00000001001b6c0e
- (id)_itemForSenderView:(id)arg1;	// IMP=0x00000001001b6ae2
- (BOOL)_isTopLevelItem:(id)arg1;	// IMP=0x000000010001582e
- (void)_saveSelectionAndReloadItem:(id)arg1;	// IMP=0x000000010002d4cd
- (void)_updateProgressIndicatorForMailbox:(id)arg1;	// IMP=0x00000001001b6a61
- (id)_copyActivityMonitorsForMailbox:(id)arg1 finishedCount:(unsigned long long *)arg2 includingDescendants:(BOOL)arg3;	// IMP=0x00000001001b6948
- (void)_redisplayRowsForItems:(id)arg1;	// IMP=0x000000010002fbf1
- (unsigned long long)_badgeCountForItem:(id)arg1;	// IMP=0x0000000100017f4e
- (id)_firstChildIfCollapsedSpecialMailbox:(id)arg1;	// IMP=0x000000010002bea9
- (void)_endWantsToEditInline;	// IMP=0x00000001001b6844
- (void)_beginWantsToEditInline;	// IMP=0x00000001001b6812
@property(readonly) BOOL wantsToEditInline;
- (void)_endReloading;	// IMP=0x000000010002d638
- (void)_beginReloading;	// IMP=0x000000010002d606
@property(readonly) BOOL isReloading;
- (void)editNameOfMailbox:(id)arg1;	// IMP=0x00000001001b6586
- (void)makeMailboxesListFirstResponder;	// IMP=0x00000001001b6519
@property(nonatomic) double idealOutlineViewWidth;
@property(readonly, nonatomic) double minimumWidthNeededToUseMailboxes;
@property(readonly, nonatomic) double minimizedOutlineViewWidth;
- (void)clearDelegateBecauseWindowIsClosing;	// IMP=0x0000000100094aa5
- (void)dealloc;	// IMP=0x00000001000951f6
- (void)_migrateAutosaveName;	// IMP=0x00000001001b62f0
@property __weak id <MailboxesOutlineViewControllerDelegate> delegate;
- (void)awakeFromNib;	// IMP=0x00000001000159be
- (id)init;	// IMP=0x0000000100014ea0

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

