//
//     Generated by class-dump 3.5b1 (64 bit) (Debug version compiled Dec  3 2019 19:59:57).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface MailPlugInViewFactory : NSObject
{
}

+ (id)plugInViewWithArguments:(id)arg1 forFrame:(id)arg2;	// IMP=0x00000001001c369c

@end

