//
//     Generated by class-dump 3.5b1 (64 bit) (Debug version compiled Dec  3 2019 19:59:57).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableArray, NSMutableIndexSet, NSPredicate;
@protocol ManagedListSortInfo;

@interface ManagedList : NSObject
{
    NSMutableArray *_orderedObjects;	// 8 = 0x8
    NSMutableIndexSet *_unfilteredIndexes;	// 16 = 0x10
    id _comparator;	// 24 = 0x18
    NSPredicate *_filterPredicate;	// 32 = 0x20
    id <ManagedListSortInfo> _sortInfo;	// 40 = 0x28
}

@property(retain, nonatomic) id <ManagedListSortInfo> sortInfo; // @synthesize sortInfo=_sortInfo;
@property(retain, nonatomic) NSPredicate *filterPredicate; // @synthesize filterPredicate=_filterPredicate;
@property(copy, nonatomic) id comparator; // @synthesize comparator=_comparator;
// - (void).cxx_destruct;	// IMP=0x00000001001d5bb7
- (unsigned long long)_removeObjectIfPresent:(id)arg1 fromArray:(id)arg2 inSortedRange:(struct _NSRange)arg3 usingComparator:(id)arg4 didRemove:(char *)arg5;	// IMP=0x00000001001d5a61
- (unsigned long long)_insertObjectIfAbsent:(id)arg1 intoArray:(id)arg2 inSortedRange:(struct _NSRange)arg3 usingComparator:(id)arg4 didInsert:(char *)arg5;	// IMP=0x00000001001d5955
- (unsigned long long)_removeObject:(id)arg1 inSortedRange:(struct _NSRange)arg2 didRemove:(char *)arg3;	// IMP=0x00000001001d587f
- (id)mutableCopyOfOrderedObjects;	// IMP=0x00000001001d5773
- (id)copyOfOrderedObjects;	// IMP=0x00000001001d574d
- (unsigned long long)indexOfOrderedObject:(id)arg1;	// IMP=0x00000001001d566f
- (void)enumerateOrderedObjectsUsingBlock:(id)arg1;	// IMP=0x00000001001d551f
@property(readonly, nonatomic) unsigned long long orderedObjectsCount;
- (unsigned long long)_unadjustedIndexForAdjustedIndex:(unsigned long long)arg1;	// IMP=0x00000001001d53f5
- (id)orderedObjectsAtIndexes:(id)arg1;	// IMP=0x00000001001d52de
- (void)setOrderedObject:(id)arg1 atIndex:(unsigned long long)arg2;	// IMP=0x00000001001d5279
- (id)orderedObjectAtIndex:(unsigned long long)arg1;	// IMP=0x00000001001d5247
- (unsigned long long)removeObject:(id)arg1;	// IMP=0x00000001001d5165
- (id)removeObjects:(id)arg1;	// IMP=0x00000001001d4f06
- (unsigned long long)mergeObject:(id)arg1;	// IMP=0x00000001001d4d74
- (id)mergeObjects:(id)arg1;	// IMP=0x00000001001d488a
- (void)applyFilterReturningAddedIndexes:(id *)arg1 removedIndexes:(id *)arg2;	// IMP=0x00000001001d4655
- (void)invert;	// IMP=0x00000001001d451e
- (void)resort;	// IMP=0x00000001001d4381
- (id)init;	// IMP=0x00000001001d42f4

@end

