//
//     Generated by class-dump 3.5b1 (64 bit) (Debug version compiled Dec  3 2019 19:59:57).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface MessageListContentChangeFactory : NSObject
{
}

+ (id)createChangeMovingFromIndex:(unsigned long long)arg1 toIndex:(unsigned long long)arg2;	// IMP=0x00000001001dc268
+ (id)createChangeFromRemovedIndexes:(id)arg1 withAnimationOptions:(unsigned long long)arg2;	// IMP=0x00000001001dc20c
+ (id)createChangeFromAddedIndexes:(id)arg1 withAnimationOptions:(unsigned long long)arg2;	// IMP=0x00000001001dc1b0

@end

