//
//     Generated by class-dump 3.5b1 (64 bit) (Debug version compiled Dec  3 2019 19:59:57).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Email/EMListUnsubscribeMessageGenerator.h>

@interface MFListUnsubscribeMessageGenerator_macOS : EMListUnsubscribeMessageGenerator
{
}

+ (id)senderForCommand:(id)arg1;	// IMP=0x00000001002263d5
+ (id)messageForCommand:(id)arg1;	// IMP=0x0000000100226241

@end

