//
//     Generated by class-dump 3.5b1 (64 bit) (Debug version compiled Dec  3 2019 19:59:57).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "MTMMessage.h"

@class NSDictionary;

@interface MTMFakeMessage : MTMMessage
{
    NSDictionary *_messageDescription;	// 16 = 0x10
}

// - (void).cxx_destruct;	// IMP=0x00000001002377aa
- (unsigned long long)readFlags;	// IMP=0x0000000100237754
- (unsigned long long)messageFlags;	// IMP=0x00000001002376fe
- (id)valueForKey:(id)arg1;	// IMP=0x00000001002376e1
- (id)init;	// IMP=0x0000000100237612
- (id)initWithDescription:(id)arg1;	// IMP=0x00000001002375a4

@end

