//
//     Generated by class-dump 3.5b1 (64 bit) (Debug version compiled Dec  3 2019 19:59:57).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSWindow.h>

@interface MTMWindow : NSWindow
{
}

- (double)animationResizeTime:(struct CGRect)arg1;	// IMP=0x000000010023ddd9

@end

