//
//     Generated by class-dump 3.5b1 (64 bit) (Debug version compiled Dec  3 2019 19:59:57).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface MVMailBundle : NSObject
{
}

+ (id)composeAccessoryViewOwnerClassName;	// IMP=0x0000000100245438
+ (BOOL)hasComposeAccessoryViewOwner;	// IMP=0x000000010000949e
+ (id)preferencesPanelName;	// IMP=0x00000001002453de
+ (id)preferencesOwnerClassName;	// IMP=0x00000001002453cc
+ (BOOL)hasPreferencesPanel;	// IMP=0x00000001000094a6
+ (id)sharedInstance;	// IMP=0x00000001000094ae
+ (void)registerBundle;	// IMP=0x000000010000929b
+ (id)composeAccessoryViewOwners;	// IMP=0x0000000100245166
+ (id)allBundles;	// IMP=0x000000010024514d
+ (id)pluginSupportedCompatibilityUUIDsKey;	// IMP=0x00000001002450ae
- (void)dealloc;	// IMP=0x0000000100245492

@end

