//
//     Generated by class-dump 3.5b1 (64 bit) (Debug version compiled Dec  3 2019 19:59:57).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSAttributedString.h>

@interface NSAttributedString (MailAttributedStringToHTML)
- (void)_removeQuotingDisplayAttributesFromAttributedString:(id)arg1 inRange:(struct _NSRange)arg2;	// IMP=0x00000001000c46c1
- (id)webArchiveForRange:(struct _NSRange)arg1 signatureID:(id *)arg2;	// IMP=0x00000001000c3a53
@end

