//
//     Generated by class-dump 3.5b1 (64 bit) (Debug version compiled Dec  3 2019 19:59:57).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSToolbar.h>

@interface NSToolbar (MailAdditions)
+ (id)segmentedOrBorderlessItemForItemIdentifier:(id)arg1 withDictionary:(id)arg2;	// IMP=0x000000010001f9f6
+ (id)borderlessItemForItemIdentifier:(id)arg1 withDictionary:(id)arg2;	// IMP=0x0000000100246709
+ (id)segmentedItemForItemIdentifier:(id)arg1 withDictionary:(id)arg2;	// IMP=0x000000010001fb91
+ (void)configureSegmentedItem:(id)arg1 withDictionary:(id)arg2 forSegment:(long long)arg3;	// IMP=0x00000001000206d6
- (id)configureToolbarItems;	// IMP=0x000000010001e676
- (id)itemWithTag:(long long)arg1;	// IMP=0x0000000100053db0
@end

