//
//     Generated by class-dump 3.5b1 (64 bit) (Debug version compiled Dec  3 2019 19:59:57).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSViewController.h>

#import "NSTableViewDataSource-Protocol.h"
#import "NSTableViewDelegate-Protocol.h"
#import "NSUserInterfaceValidations-Protocol.h"
#import "TerminationHandler-Protocol.h"

@class NSArray, NSButton, NSMutableSet, NSProgressIndicator, NSString, NSTableView, NSTextField;

@interface PlugInsViewController : NSViewController <NSTableViewDataSource, NSTableViewDelegate, NSUserInterfaceValidations, TerminationHandler>
{
    NSArray *_bundles;	// 16 = 0x10
    NSMutableSet *_bundlesToUninstall;	// 24 = 0x18
    NSMutableSet *_bundlesToInstall;	// 32 = 0x20
    NSTableView *_tableView;	// 40 = 0x28
    NSButton *_applyButton;	// 48 = 0x30
    NSButton *_cancelButton;	// 56 = 0x38
    NSTextField *_progressLabel;	// 64 = 0x40
    NSProgressIndicator *_progressIndicator;	// 72 = 0x48
}

@property(retain, nonatomic) NSProgressIndicator *progressIndicator; // @synthesize progressIndicator=_progressIndicator;
@property(retain, nonatomic) NSTextField *progressLabel; // @synthesize progressLabel=_progressLabel;
@property(retain, nonatomic) NSButton *cancelButton; // @synthesize cancelButton=_cancelButton;
@property(retain, nonatomic) NSButton *applyButton; // @synthesize applyButton=_applyButton;
@property(retain, nonatomic) NSTableView *tableView; // @synthesize tableView=_tableView;
// - (void).cxx_destruct;	// IMP=0x000000010024bf93
- (void)nowWouldBeAGoodTimeToTerminate:(id)arg1;	// IMP=0x000000010024bbb0
- (id)tableView:(id)arg1 viewForTableColumn:(id)arg2 row:(long long)arg3;	// IMP=0x000000010024b9a5
- (long long)numberOfRowsInTableView:(id)arg1;	// IMP=0x000000010024b988
- (BOOL)validateUserInterfaceItem:(id)arg1;	// IMP=0x000000010024b8d2
- (void)_updateApplyButton;	// IMP=0x000000010024b86d
- (void)_showInFinder:(id)arg1;	// IMP=0x000000010024b74e
- (void)_applyAndReopenMail:(id)arg1;	// IMP=0x000000010024b61a
- (void)setState:(long long)arg1 forBundle:(id)arg2;	// IMP=0x000000010024b578
- (void)viewDidDisappear;	// IMP=0x000000010024b4ff
- (void)viewWillAppear;	// IMP=0x000000010024b2ee

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

