//
//     Generated by class-dump 3.5b1 (64 bit) (Debug version compiled Dec  3 2019 19:59:57).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class CALayer, MailWindowShadowLayer, NSDictionary, NSWindow;

@interface PopoutAnimationController : NSObject
{
    NSDictionary *_sourceSnapshots;	// 8 = 0x8
    NSDictionary *_destinationSnapshots;	// 16 = 0x10
    NSWindow *_animationWindow;	// 24 = 0x18
    CALayer *_backgroundLayer;	// 32 = 0x20
    CALayer *_contentLayer;	// 40 = 0x28
    CALayer *_clipLayer;	// 48 = 0x30
    MailWindowShadowLayer *_shadowLayer;	// 56 = 0x38
    CALayer *_sourceHeaderLayer;	// 64 = 0x40
    CALayer *_sourceBodyLayer;	// 72 = 0x48
    CALayer *_destinationHeaderLayer;	// 80 = 0x50
    CALayer *_destinationBodyLayer;	// 88 = 0x58
    CALayer *_destinationToolbarLayer;	// 96 = 0x60
}

@property(nonatomic) __weak CALayer *destinationToolbarLayer; // @synthesize destinationToolbarLayer=_destinationToolbarLayer;
@property(nonatomic) __weak CALayer *destinationBodyLayer; // @synthesize destinationBodyLayer=_destinationBodyLayer;
@property(nonatomic) __weak CALayer *destinationHeaderLayer; // @synthesize destinationHeaderLayer=_destinationHeaderLayer;
@property(nonatomic) __weak CALayer *sourceBodyLayer; // @synthesize sourceBodyLayer=_sourceBodyLayer;
@property(nonatomic) __weak CALayer *sourceHeaderLayer; // @synthesize sourceHeaderLayer=_sourceHeaderLayer;
@property(nonatomic) __weak MailWindowShadowLayer *shadowLayer; // @synthesize shadowLayer=_shadowLayer;
@property(nonatomic) __weak CALayer *clipLayer; // @synthesize clipLayer=_clipLayer;
@property(nonatomic) __weak CALayer *contentLayer; // @synthesize contentLayer=_contentLayer;
@property(nonatomic) __weak CALayer *backgroundLayer; // @synthesize backgroundLayer=_backgroundLayer;
@property(retain, nonatomic) NSWindow *animationWindow; // @synthesize animationWindow=_animationWindow;
// - (void).cxx_destruct;	// IMP=0x0000000100250a7a
- (void)_updateDestinationSnapshots:(id)arg1;	// IMP=0x0000000100250760
- (void)_updateSourceSnapshots:(id)arg1;	// IMP=0x000000010025052d
- (id)_backgroundAnimation;	// IMP=0x0000000100250444
- (id)_toolbarAnimationWithFinalSize:(struct CGSize)arg1;	// IMP=0x00000001002501d6
- (id)_internalTransitionAnimationWithDestination:(struct CGRect)arg1 fadeOut:(BOOL)arg2;	// IMP=0x000000010024ff8f
- (id)_sizeAnimationWithStartSize:(struct CGSize)arg1 endSize:(struct CGSize)arg2;	// IMP=0x000000010024fe86
- (id)_positionAnimationWithStartPosition:(struct CGPoint)arg1 endPosition:(struct CGPoint)arg2 percentFromStart:(double)arg3;	// IMP=0x000000010024fb67
- (id)_frameAnimationWithStart:(struct CGRect)arg1 destination:(struct CGRect)arg2;	// IMP=0x000000010024f9ea
- (void)_performAnimationWithSourceGeometry:(id)arg1 destionationGeometry:(id)arg2 completion:(id)arg3;	// IMP=0x000000010024f0c5
- (struct CGRect)_commonScreenRectForSource:(struct CGRect)arg1 destination:(struct CGRect)arg2;	// IMP=0x000000010024ee21
- (void)_setupLayer:(id)arg1 withGeometry:(id)arg2;	// IMP=0x000000010024ed2e
- (id)_createContentLayerWithFrame:(struct CGRect)arg1 scale:(double)arg2;	// IMP=0x000000010024e5d5
- (id)_createBackgroundLayer;	// IMP=0x000000010024dfe6
- (id)_createAnimationWindow:(struct CGRect)arg1;	// IMP=0x000000010024de88
- (BOOL)_initializeAnimationWindowComponentsWithSource:(id)arg1 destination:(id)arg2;	// IMP=0x000000010024d6a7
- (void)animateFrom:(id)arg1 to:(id)arg2 withCompletion:(id)arg3;	// IMP=0x000000010024d4f3
@property(copy, nonatomic) NSDictionary *destinationSnapshots;
@property(copy, nonatomic) NSDictionary *sourceSnapshots;

@end

