//
//     Generated by class-dump 3.5b1 (64 bit) (Debug version compiled Dec  3 2019 19:59:57).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSOperation.h>

@class ECAngleBracketIDHash, MCMessage, NSString;

@interface PostUserNotificationOperation : NSOperation
{
    MCMessage *_message;	// 8 = 0x8
    NSString *_identifier;	// 16 = 0x10
    NSString *_snippet;	// 24 = 0x18
    NSString *_messageID;	// 32 = 0x20
    ECAngleBracketIDHash *_messageIDHeaderHash;	// 40 = 0x28
}

@property(readonly, copy, nonatomic) ECAngleBracketIDHash *messageIDHeaderHash; // @synthesize messageIDHeaderHash=_messageIDHeaderHash;
@property(readonly, copy, nonatomic) NSString *messageID; // @synthesize messageID=_messageID;
@property(readonly, copy, nonatomic) NSString *snippet; // @synthesize snippet=_snippet;
@property(readonly, nonatomic) NSString *identifier; // @synthesize identifier=_identifier;
@property(readonly, nonatomic) MCMessage *message; // @synthesize message=_message;
// - (void).cxx_destruct;	// IMP=0x0000000100254ad1
- (void)cancel;	// IMP=0x00000001002549bb
- (unsigned long long)hash;	// IMP=0x0000000100254933
- (BOOL)isEqual:(id)arg1;	// IMP=0x0000000100254817
- (void)main;	// IMP=0x0000000100253f69
- (id)description;	// IMP=0x0000000100253e95
- (id)init;	// IMP=0x0000000100253dc6
- (id)initWithMessage:(id)arg1 snippet:(id)arg2;	// IMP=0x0000000100253c66

@end

