//
//     Generated by class-dump 3.5b1 (64 bit) (Debug version compiled Dec  3 2019 19:59:57).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "PrintingManager.h"

@interface PrintingManagerForPrinting : PrintingManager
{
}

- (void)_print:(id)arg1;	// IMP=0x000000010025b9de
- (void)dispatch;	// IMP=0x000000010025b131
- (id)progressMessage;	// IMP=0x000000010025b0cb
- (void)dealloc;	// IMP=0x000000010025b079

@end

