//
//     Generated by class-dump 3.5b1 (64 bit) (Debug version compiled Dec  3 2019 19:59:57).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class MessageSelection, MessageWebDocumentView, PrintingProgressPanelWindowController;

@interface PrintingManager : NSObject
{
    BOOL _wasCancelled;	// 8 = 0x8
    PrintingManager *_activeDispatcher;	// 16 = 0x10
    MessageSelection *_selection;	// 24 = 0x18
    MessageWebDocumentView *_webDocumentView;	// 32 = 0x20
    PrintingProgressPanelWindowController *_progressPanelController;	// 40 = 0x28
    double _progressMaxValue;	// 48 = 0x30
    double _progressValue;	// 56 = 0x38
    double _progressIncrement;	// 64 = 0x40
    double _pageZoom;	// 72 = 0x48
}

+ (void)exportSelectionAsPDF:(id)arg1 pageZoomFactor:(double)arg2;	// IMP=0x00000001002588e5
+ (void)printSelection:(id)arg1 pageZoomFactor:(double)arg2;	// IMP=0x000000010025885c
@property(nonatomic) double pageZoom; // @synthesize pageZoom=_pageZoom;
@property(nonatomic) BOOL wasCancelled; // @synthesize wasCancelled=_wasCancelled;
@property(nonatomic) double progressIncrement; // @synthesize progressIncrement=_progressIncrement;
@property double progressValue; // @synthesize progressValue=_progressValue;
@property(nonatomic) double progressMaxValue; // @synthesize progressMaxValue=_progressMaxValue;
@property(retain, nonatomic) PrintingProgressPanelWindowController *progressPanelController; // @synthesize progressPanelController=_progressPanelController;
@property(retain, nonatomic) MessageWebDocumentView *webDocumentView; // @synthesize webDocumentView=_webDocumentView;
@property(retain, nonatomic) MessageSelection *selection; // @synthesize selection=_selection;
@property(retain, nonatomic) PrintingManager *activeDispatcher; // @synthesize activeDispatcher=_activeDispatcher;
// - (void).cxx_destruct;	// IMP=0x000000010025935c
- (void)_showProgressPanel;	// IMP=0x000000010025909c
- (void)_generatePrintingHTMLForEnumeratedConversationMembers:(id)arg1 HTMLStorage:(id)arg2 attachmentStorage:(id)arg3 completionHandler:(id)arg4;	// IMP=0x0000000100258c99
- (id)init;	// IMP=0x0000000100258bca
- (id)initWithSelection:(id)arg1;	// IMP=0x000000010025896e

@end

