//
//     Generated by class-dump 3.5b1 (64 bit) (Debug version compiled Dec  3 2019 19:59:57).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSWindowDelegate-Protocol.h"

@class MUIWebDocumentView, NSMutableArray, NSPrintInfo, NSString;

@interface PrintingHTMLPrinter : NSObject <NSWindowDelegate>
{
    BOOL _hasPrinted;	// 8 = 0x8
    NSString *_printingHTML;	// 16 = 0x10
    NSMutableArray *_attachments;	// 24 = 0x18
    NSPrintInfo *_printInfo;	// 32 = 0x20
    NSString *_jobTitle;	// 40 = 0x28
    MUIWebDocumentView *_printView;	// 48 = 0x30
    long long _messageContentTypeToBlock;	// 56 = 0x38
    PrintingHTMLPrinter *_activePrinter;	// 64 = 0x40
    id _finishedPrintingCompletionBlock;	// 72 = 0x48
}

@property(copy, nonatomic) id finishedPrintingCompletionBlock; // @synthesize finishedPrintingCompletionBlock=_finishedPrintingCompletionBlock;
@property(retain, nonatomic) PrintingHTMLPrinter *activePrinter; // @synthesize activePrinter=_activePrinter;
@property(nonatomic) long long messageContentTypeToBlock; // @synthesize messageContentTypeToBlock=_messageContentTypeToBlock;
@property(nonatomic) BOOL hasPrinted; // @synthesize hasPrinted=_hasPrinted;
@property(retain, nonatomic) MUIWebDocumentView *printView; // @synthesize printView=_printView;
@property(retain, nonatomic) NSString *jobTitle; // @synthesize jobTitle=_jobTitle;
@property(retain, nonatomic) NSPrintInfo *printInfo; // @synthesize printInfo=_printInfo;
@property(retain, nonatomic) NSMutableArray *attachments; // @synthesize attachments=_attachments;
@property(retain, nonatomic) NSString *printingHTML; // @synthesize printingHTML=_printingHTML;
// - (void).cxx_destruct;	// IMP=0x00000001002584e0
- (void)printOperationDidRun:(id)arg1 success:(BOOL)arg2 contextInfo:(void *)arg3;	// IMP=0x00000001002582f1
- (void)_runPrintOperation;	// IMP=0x000000010025808f
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;	// IMP=0x0000000100257f12
- (void)run:(id)arg1;	// IMP=0x0000000100257c14
- (void)dealloc;	// IMP=0x0000000100257bc1
- (id)init;	// IMP=0x0000000100257af2
- (id)initWithPrintingHTML:(id)arg1 attachments:(id)arg2 printInfo:(id)arg3 jobTitle:(id)arg4 messageContentTypeToBlock:(long long)arg5;	// IMP=0x0000000100257985

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

