//
//     Generated by class-dump 3.5b1 (64 bit) (Debug version compiled Dec  3 2019 19:59:57).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSViewController.h>

@class MCProgressEntry, NSProgressIndicator, NSString, NSTextField;

@interface ProgressViewController : NSViewController
{
    NSProgressIndicator *_progressIndicator;	// 16 = 0x10
    NSTextField *_secondaryTextField;	// 24 = 0x18
}

+ (id)keyPathsForValuesAffectingSecondaryText;	// IMP=0x000000010025cf3b
+ (id)keyPathsForValuesAffectingShouldShowOverrideButton;	// IMP=0x000000010025ceae
@property(retain, nonatomic) NSTextField *secondaryTextField; // @synthesize secondaryTextField=_secondaryTextField;
@property(retain, nonatomic) NSProgressIndicator *progressIndicator; // @synthesize progressIndicator=_progressIndicator;
// - (void).cxx_destruct;	// IMP=0x000000010025d061
@property(readonly, copy, nonatomic) NSString *secondaryText;
@property(readonly, nonatomic) BOOL shouldShowOverrideButton;
- (void)_transitionToEntry:(id)arg1;	// IMP=0x000000010025cd07
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;	// IMP=0x000000010025cae5
@property(retain) MCProgressEntry *representedObject;
- (void)viewDidLoad;	// IMP=0x000000010025c7a7
- (void)awakeFromNib;	// IMP=0x000000010025c6be
- (void)dealloc;	// IMP=0x000000010025c5f4
- (void)_progressViewControllerCommonInit;	// IMP=0x000000010025c55a
- (id)initWithCoder:(id)arg1;	// IMP=0x000000010025c513
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;	// IMP=0x000000010025c4a2

@end

