//
//     Generated by class-dump 3.5b1 (64 bit) (Debug version compiled Dec  3 2019 19:59:57).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSOperationQueue;

@interface RedundantContentIdentificationManager : NSObject
{
    NSOperationQueue *_workQueue;	// 8 = 0x8
}

+ (id)sharedInstance;	// IMP=0x00000001000064d6
+ (id)allocWithZone:(struct _NSZone *)arg1;	// IMP=0x000000010025e531
@property(retain) NSOperationQueue *workQueue; // @synthesize workQueue=_workQueue;
// - (void).cxx_destruct;	// IMP=0x000000010025f188
- (id)_messageWithMessageIDHeaderString:(id)arg1 inConversation:(id)arg2;	// IMP=0x0000000100047c81
- (id)mostRecentAncestorForRedundantTextComparisonForMessage:(id)arg1 inConversation:(id)arg2 fetchingHeaders:(BOOL)arg3;	// IMP=0x000000010025e6cb
- (id)redundantContentMarkupForMessage:(id)arg1 inConversation:(id)arg2;	// IMP=0x000000010003ab2b
- (void)dealloc;	// IMP=0x000000010025e5ea
- (id)init;	// IMP=0x000000010000658f

@end

