//
//     Generated by class-dump 3.5b1 (64 bit) (Debug version compiled Dec  3 2019 19:59:57).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSToolbarItemGroup.h>

@class NSSegmentedControl;

@interface SegmentedToolbarItem : NSToolbarItemGroup
{
    BOOL _disableWidthCalculation;	// 8 = 0x8
    double _fixedWidth;	// 16 = 0x10
}

@property(nonatomic) double fixedWidth; // @synthesize fixedWidth=_fixedWidth;
@property(nonatomic) BOOL disableWidthCalculation; // @synthesize disableWidthCalculation=_disableWidthCalculation;
- (void)setMenu:(id)arg1 forSegment:(long long)arg2;	// IMP=0x00000001002706e9
- (void)setToolTip:(id)arg1 forSegment:(long long)arg2;	// IMP=0x0000000100020d0d
- (void)setTag:(long long)arg1 forSegment:(long long)arg2;	// IMP=0x00000001000211e8
- (void)setTarget:(id)arg1 forSegment:(long long)arg2;	// IMP=0x000000010002142a
- (id)targetForSegment:(long long)arg1;	// IMP=0x0000000100270660
- (void)setAction:(SEL)arg1 forSegment:(long long)arg2;	// IMP=0x0000000100020c92
- (SEL)actionForSegment:(long long)arg1;	// IMP=0x00000001002705e4
- (void)setPaletteLabel:(id)arg1 forSegment:(long long)arg2;	// IMP=0x000000010002108a
- (id)paletteLabelForSegment:(long long)arg1;	// IMP=0x000000010027054d
- (void)setInsideLabel:(id)arg1 forSegment:(long long)arg2;	// IMP=0x00000001002704d5
- (id)insideLabelForSegment:(long long)arg1;	// IMP=0x0000000100270476
- (void)setAlternateLabel:(id)arg1 forSegment:(long long)arg2;	// IMP=0x0000000100020eda
- (void)setLabel:(id)arg1 forSegment:(long long)arg2;	// IMP=0x0000000100020e3a
- (id)labelForSegment:(long long)arg1;	// IMP=0x0000000100020ff3
- (id)forwardingTargetForSelector:(SEL)arg1;	// IMP=0x000000010002112a
@property(nonatomic) long long segmentCount;
- (void)_controlAction:(id)arg1;	// IMP=0x000000010006118f
@property(readonly, nonatomic) NSSegmentedControl *control;
- (void)validate;	// IMP=0x0000000100022f42
- (void)configureForDisplayMode:(unsigned long long)arg1 andSizeMode:(unsigned long long)arg2;	// IMP=0x0000000100022767
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x0000000100270390
- (id)initWithItemIdentifier:(id)arg1;	// IMP=0x000000010002028f

@end

