//
//     Generated by class-dump 3.5b1 (64 bit) (Debug version compiled Dec  3 2019 19:59:57).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSViewController.h>

#import "AccountStatusDataSourceDelegate-Protocol.h"

@class ACAccount, AccountStatusDataSource, NSError, NSMutableSet, NSNumber, NSPopUpButton, NSStackView, NSString, NSView, VerifyingServerSettingsController;

@interface ServerSettingsController : NSViewController <AccountStatusDataSourceDelegate>
{
    NSMutableSet *_accountsBeingVerified;	// 16 = 0x10
    NSError *_lastVerificationError;	// 24 = 0x18
    ACAccount *_lastAccountWithError;	// 32 = 0x20
    BOOL _accountNeedsSaving;	// 40 = 0x28
    BOOL _accountNeedsVerification;	// 41 = 0x29
    NSStackView *_serverSettings;	// 48 = 0x30
    NSView *_dynamicallyManagedProperties;	// 56 = 0x38
    AccountStatusDataSource *_outgoingAccountDataSource;	// 64 = 0x40
    NSPopUpButton *_outgoingAccountPopUp;	// 72 = 0x48
    VerifyingServerSettingsController *_verifyingServerSettingsController;	// 80 = 0x50
}

+ (id)keyPathsForValuesAffectingAccountDisablesDynamicConfiguration;	// IMP=0x00000001002716c6
+ (id)keyPathsForValuesAffectingAccountPassword;	// IMP=0x000000010027153c
+ (id)keyPathsForValuesAffectingAccountUsername;	// IMP=0x0000000100271448
@property(retain, nonatomic) VerifyingServerSettingsController *verifyingServerSettingsController; // @synthesize verifyingServerSettingsController=_verifyingServerSettingsController;
@property(nonatomic) BOOL accountNeedsVerification; // @synthesize accountNeedsVerification=_accountNeedsVerification;
@property(nonatomic) BOOL accountNeedsSaving; // @synthesize accountNeedsSaving=_accountNeedsSaving;
@property(nonatomic) __weak NSPopUpButton *outgoingAccountPopUp; // @synthesize outgoingAccountPopUp=_outgoingAccountPopUp;
@property(retain, nonatomic) AccountStatusDataSource *outgoingAccountDataSource; // @synthesize outgoingAccountDataSource=_outgoingAccountDataSource;
@property(nonatomic) __weak NSView *dynamicallyManagedProperties; // @synthesize dynamicallyManagedProperties=_dynamicallyManagedProperties;
@property(nonatomic) __weak NSStackView *serverSettings; // @synthesize serverSettings=_serverSettings;
// - (void).cxx_destruct;	// IMP=0x00000001002726ca
- (void)editServerList:(id)arg1 selectedAccount:(id)arg2;	// IMP=0x0000000100272507
@property(readonly, copy, nonatomic) NSString *advancedSettingsControllerIdentifier;
@property(readonly, copy, nonatomic) NSString *advancedSettingsSegueIdentifier;
- (void)accountDidFailToVerify:(id)arg1;	// IMP=0x0000000100272481
- (id)getAccountsNeedingVerification;	// IMP=0x00000001002723f4
- (void)_verifyAndSaveAccounts:(id)arg1 completionHandler:(id)arg2;	// IMP=0x0000000100271994
- (void)verifyAndSaveAccounts:(id)arg1;	// IMP=0x000000010027197d
- (void)saveAccounts:(id)arg1;	// IMP=0x0000000100271969
- (void)outgoingAccountDidChange:(id)arg1;	// IMP=0x000000010027186f
@property(retain, nonatomic) NSNumber *accountDisablesDynamicConfiguration;
@property(copy, nonatomic) NSString *accountPassword;
@property(copy, nonatomic) NSString *accountUsername;
- (void)setUpUIForAccount:(id)arg1;	// IMP=0x0000000100271275
- (void)dismissViewController:(id)arg1;	// IMP=0x00000001002710a2
- (void)prepareForSegue:(id)arg1 sender:(id)arg2;	// IMP=0x0000000100270eff
@property(retain) ACAccount *representedObject;
- (void)viewDidLoad;	// IMP=0x0000000100270c48
- (id)willPresentError:(id)arg1;	// IMP=0x0000000100270a92
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;	// IMP=0x000000010027094a
- (void)dealloc;	// IMP=0x00000001002708f0
- (void)_serverSettingsControllerCommonInit;	// IMP=0x00000001002708b8
- (id)initWithCoder:(id)arg1;	// IMP=0x0000000100270871
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;	// IMP=0x0000000100270800

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

