//
//     Generated by class-dump 3.5b1 (64 bit) (Debug version compiled Dec  3 2019 19:59:57).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSValueTransformer.h>

@interface SignTooTipValueTransformer : NSValueTransformer
{
}

+ (Class)transformedValueClass;	// IMP=0x000000010016764f
- (id)transformedValue:(id)arg1;	// IMP=0x0000000100167668

@end

