//
//     Generated by class-dump 3.5b1 (64 bit) (Debug version compiled Dec  3 2019 19:59:57).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableDictionary;
@protocol SlidingAnimationDelegate;

@interface SlidingAnimation : NSObject
{
    NSMutableDictionary *_views;	// 8 = 0x8
    BOOL _isSliding;	// 16 = 0x10
    BOOL _isPaused;	// 17 = 0x11
    id <SlidingAnimationDelegate> _delegate;	// 24 = 0x18
}

@property(nonatomic) BOOL isPaused; // @synthesize isPaused=_isPaused;
@property(nonatomic) BOOL isSliding; // @synthesize isSliding=_isSliding;
@property(nonatomic) __weak id <SlidingAnimationDelegate> delegate; // @synthesize delegate=_delegate;
// - (void).cxx_destruct;	// IMP=0x000000010028014f
- (id)_runLoopModesForAnimation;	// IMP=0x00000001002800aa
- (void)resume;	// IMP=0x000000010028007a
- (void)pause;	// IMP=0x0000000100280047
- (void)stop;	// IMP=0x000000010000fcaf
- (void)stopView:(id)arg1;	// IMP=0x000000010027ffd6
- (struct CGRect)destinationForView:(id)arg1;	// IMP=0x000000010027ff99
- (void)_sendViewToDestination:(id)arg1;	// IMP=0x000000010027fefd
- (void)setDestinationForView:(id)arg1 to:(struct CGRect)arg2 duration:(double)arg3;	// IMP=0x000000010027fcf7
- (void)_showNextFrame;	// IMP=0x000000010027fb3c
- (void)_updateTimer;	// IMP=0x000000010000fdfd
- (void)_updateViewPosition:(id)arg1 forTime:(double)arg2;	// IMP=0x000000010027fa1f
- (void)dealloc;	// IMP=0x000000010027f9e1
- (id)init;	// IMP=0x000000010000b9f1

@end

