//
//     Generated by class-dump 3.5b1 (64 bit) (Debug version compiled Dec  3 2019 19:59:57).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSImageTextFieldCell.h>

@interface StatusCell : NSImageTextFieldCell
{
    long long _statusType;	// 40 = 0x28
}

@property(nonatomic) long long statusType; // @synthesize statusType=_statusType;
- (id)accessibilityRoleDescription;	// IMP=0x0000000100295cc4
- (id)accessibilityValue;	// IMP=0x0000000100295ba0

@end

