//
//     Generated by class-dump 3.5b1 (64 bit) (Debug version compiled Dec  3 2019 19:59:57).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface TestController : NSObject
{
    NSString *_currentTopLevelTest;	// 8 = 0x8
}

+ (id)sharedController;	// IMP=0x00000001001a8410
@property(copy) NSString *currentTopLevelTest; // @synthesize currentTopLevelTest=_currentTopLevelTest;
// - (void).cxx_destruct;	// IMP=0x00000001001a851a
- (void)doScrollTestWithTestName:(id)arg1 options:(id)arg2;	// IMP=0x00000001001a846d

@end

