//
//     Generated by class-dump 3.5b1 (64 bit) (Debug version compiled Dec  3 2019 19:59:57).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSTextField.h>

@class NSImage;

@interface ThreadDisclosureTextField : NSTextField
{
    NSImage *_disclosureImage;	// 120 = 0x78
}

+ (id)closedThreadImage;	// IMP=0x00000001002a5b71
+ (id)openThreadImage;	// IMP=0x00000001002a5a63
@property(retain, nonatomic) NSImage *disclosureImage; // @synthesize disclosureImage=_disclosureImage;
// - (void).cxx_destruct;	// IMP=0x00000001002a6474
- (void)mouseDown:(id)arg1;	// IMP=0x00000001002a6239
- (void)drawRect:(struct CGRect)arg1;	// IMP=0x00000001002a5f62
@property(nonatomic) BOOL isOpen;
- (id)_foregroundColor;	// IMP=0x00000001002a5e83
- (id)_backgroundColor;	// IMP=0x00000001002a5ddf
- (void)_commonInit;	// IMP=0x00000001002a5c24
- (id)initWithCoder:(id)arg1;	// IMP=0x00000001002a5bdd

@end

