//
//     Generated by class-dump 3.5b1 (64 bit) (Debug version compiled Dec  3 2019 19:59:57).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSOperation.h>

@interface WebViewLoadOperation : NSOperation
{
    BOOL _isExecuting;	// 8 = 0x8
    BOOL _isFinished;	// 9 = 0x9
}

+ (BOOL)automaticallyNotifiesObserversOfIsFinished;	// IMP=0x00000001002c3ae9
+ (BOOL)automaticallyNotifiesObserversOfIsExecuting;	// IMP=0x00000001002c3ae1
- (void)_stopObservingWebView;	// IMP=0x00000001002c3b6d
- (void)_end;	// IMP=0x0000000100053c34
- (void)cancel;	// IMP=0x00000001002c3b03
- (void)_stopLoading;	// IMP=0x00000001002c3afa
- (void)_startLoading;	// IMP=0x00000001002c3af1
- (void)main;	// IMP=0x0000000100053c22
- (void)start;	// IMP=0x0000000100053332
- (BOOL)isFinished;	// IMP=0x0000000100053663
- (void)_setIsExecuting:(BOOL)arg1;	// IMP=0x00000001000536ac
- (BOOL)isExecuting;	// IMP=0x000000010005361a
- (BOOL)isConcurrent;	// IMP=0x00000001002c3ad6
- (void)dealloc;	// IMP=0x00000001000590f4
- (id)_init;	// IMP=0x00000001002c3aa7

@end

