//
//     Generated by class-dump 3.5b1 (64 bit) (Debug version compiled Dec  3 2019 19:59:57).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <EmailCore/ECHTMLStringAndMIMECharset.h>

#import <MailUIFW/NSSecureCoding-Protocol.h>

@interface ECHTMLStringAndMIMECharset (MailUIAdditions) <NSSecureCoding>
+ (BOOL)supportsSecureCoding;	// IMP=0x0000000000019de2
- (id)initWithCoder:(id)arg1;	// IMP=0x0000000000019ea0
- (void)encodeWithCoder:(id)arg1;	// IMP=0x0000000000019ded
@end

