//
//     Generated by class-dump 3.5b1 (64 bit) (Debug version compiled Dec  3 2019 19:59:57).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

//#import <AppKit/NSTokenAttachmentCell.h>

@class NSColor;

@interface MUIAddressTokenAttachmentCell //: NSTokenAttachmentCell
{
    BOOL _neverShowSeparator;	// 52 = 0x34
    BOOL _displayAsExternal;	// 53 = 0x35
    NSColor *_foregroundColor;	// 56 = 0x38
}

+ (id)colorForExternalDomain;	// IMP=0x000000000000db28
@property(retain, nonatomic) NSColor *foregroundColor; // @synthesize foregroundColor=_foregroundColor;
@property(nonatomic) BOOL displayAsExternal; // @synthesize displayAsExternal=_displayAsExternal;
@property BOOL neverShowSeparator; // @synthesize neverShowSeparator=_neverShowSeparator;
// - (void).cxx_destruct;	// IMP=0x0000000000017546
- (id)_textAttributes;	// IMP=0x0000000000017463
- (BOOL)_finalizeStyleTextOptions:(id)arg1;	// IMP=0x000000000001745b
- (id)tokenTintColor;	// IMP=0x0000000000010156

@end

