//
//     Generated by class-dump 3.5b1 (64 bit) (Debug version compiled Dec  3 2019 19:59:57).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <WebKit/WKWebView.h>

#import <MailUIFW/NSDraggingSource-Protocol.h>
#import <MailUIFW/QLPreviewPanelDataSource-Protocol.h>
#import <MailUIFW/QLPreviewPanelDelegate-Protocol.h>
#import <MailUIFW/QLSeamlessCloserDelegate-Protocol.h>
#import <MailUIFW/QLSeamlessOpenerDelegate-Protocol.h>

@class MUISelectionAndClickInformation, MUIWKWebViewController, NSArray, NSDraggingSession, NSEvent, NSResponder, NSString;

@interface MUIWKWebView : WKWebView <NSDraggingSource, QLPreviewPanelDataSource, QLPreviewPanelDelegate, QLSeamlessCloserDelegate, QLSeamlessOpenerDelegate>
{
    BOOL _acceptsScrollWheelChangedPhase;	// 108 = 0x6c
    BOOL _isDragging;	// 109 = 0x6d
    BOOL _isDraggingAttachments;	// 110 = 0x6e
    MUIWKWebViewController *_controller;	// 112 = 0x70
    NSDraggingSession *_dragSession;	// 120 = 0x78
    NSArray *_attachmentControllersToQuicklook;	// 128 = 0x80
    NSEvent *_attachmentMouseDownEvent;	// 136 = 0x88
    MUISelectionAndClickInformation *_selectionAndClickInformation;	// 144 = 0x90
    NSResponder *_oldFirstResponder;	// 152 = 0x98
}

@property(retain, nonatomic) NSResponder *oldFirstResponder; // @synthesize oldFirstResponder=_oldFirstResponder;
@property(retain, nonatomic) MUISelectionAndClickInformation *selectionAndClickInformation; // @synthesize selectionAndClickInformation=_selectionAndClickInformation;
@property(retain, nonatomic) NSEvent *attachmentMouseDownEvent; // @synthesize attachmentMouseDownEvent=_attachmentMouseDownEvent;
@property(retain, nonatomic) NSArray *attachmentControllersToQuicklook; // @synthesize attachmentControllersToQuicklook=_attachmentControllersToQuicklook;
@property(retain, nonatomic) NSDraggingSession *dragSession; // @synthesize dragSession=_dragSession;
@property(nonatomic) BOOL isDraggingAttachments; // @synthesize isDraggingAttachments=_isDraggingAttachments;
@property(nonatomic) BOOL isDragging; // @synthesize isDragging=_isDragging;
@property(nonatomic) __weak MUIWKWebViewController *controller; // @synthesize controller=_controller;
// - (void).cxx_destruct;	// IMP=0x000000000002cff2
- (id)seamlessCloserTransitionImageForPreviewItem:(id)arg1 contentRect:(struct CGRect *)arg2;	// IMP=0x000000000002ceb0
- (struct CGRect)seamlessCloserSourceFrameOnScreenForPreviewItem:(id)arg1;	// IMP=0x000000000002ce8c
- (void)seamlessOpener:(id)arg1 failedToOpenItems:(id)arg2 withError:(id)arg3;	// IMP=0x000000000002ccd2
- (id)seamlessOpener:(id)arg1 transitionImageForPreviewItem:(id)arg2 contentRect:(struct CGRect *)arg3 windowLevel:(long long *)arg4;	// IMP=0x000000000002ccbe
- (struct CGRect)seamlessOpener:(id)arg1 sourceFrameOnScreenForPreviewItem:(id)arg2;	// IMP=0x000000000002cc9d
- (id)previewPanel:(id)arg1 transitionImageForPreviewItem:(id)arg2 contentRect:(struct CGRect *)arg3;	// IMP=0x000000000002cc88
- (struct CGRect)previewPanel:(id)arg1 sourceFrameOnScreenForPreviewItem:(id)arg2;	// IMP=0x000000000002cb51
- (id)previewPanel:(id)arg1 previewItemAtIndex:(long long)arg2;	// IMP=0x000000000002cae9
- (long long)numberOfPreviewItemsInPreviewPanel:(id)arg1;	// IMP=0x000000000002ca96
- (void)endPreviewPanelControl:(id)arg1;	// IMP=0x000000000002c9c2
- (void)beginPreviewPanelControl:(id)arg1;	// IMP=0x000000000002c961
- (BOOL)acceptsPreviewPanelControl:(id)arg1;	// IMP=0x000000000002c956
- (void)keyDown:(id)arg1;	// IMP=0x000000000002c860
- (BOOL)performKeyEquivalent:(id)arg1;	// IMP=0x000000000002c794
- (void)quickLookWithEvent:(id)arg1;	// IMP=0x000000000002c6ae
- (BOOL)quickLookAttachmentControllers:(id)arg1;	// IMP=0x000000000002c355
- (void)_displayAlertForUndownloadedAttachments:(id)arg1;	// IMP=0x000000000002bf1e
- (void)mouseDragged:(id)arg1;	// IMP=0x000000000002b71a
- (void)mouseExited:(id)arg1;	// IMP=0x000000000002b6b9
- (void)mouseMoved:(id)arg1;	// IMP=0x000000000002b658
- (void)draggingSession:(id)arg1 endedAtPoint:(struct CGPoint)arg2 operation:(unsigned long long)arg3;	// IMP=0x000000000002b59a
- (unsigned long long)draggingSession:(id)arg1 sourceOperationMaskForDraggingContext:(long long)arg2;	// IMP=0x000000000002b584
- (void)mouseUp:(id)arg1;	// IMP=0x000000000002b4c7
- (BOOL)shouldDelayWindowOrderingForEvent:(id)arg1;	// IMP=0x000000000002b440
- (BOOL)acceptsFirstMouse:(id)arg1;	// IMP=0x000000000002b3b9
- (BOOL)_point:(struct CGPoint)arg1 inAttachment:(id)arg2;	// IMP=0x000000000002b2e1
- (void)mouseDown:(id)arg1;	// IMP=0x000000000002ae96
- (id)printOperationWithPrintInfo:(id)arg1;	// IMP=0x000000000002ae84
- (id)selectionAndClickInformationForClickAtPoint:(struct CGPoint)arg1;	// IMP=0x000000000002ade4
@property(readonly, copy, nonatomic) NSArray *selectedAttachmentControllers;
- (id)attachmentControllerForAttachmentInfo:(id)arg1;	// IMP=0x000000000002a9c8
- (id)selectionAndClickInformationFromSelectionContextDictionary:(id)arg1;	// IMP=0x000000000002a1b0
- (struct CGSize)intrinsicContentSize;	// IMP=0x000000000002a119
- (void)invalidateIntrinsicContentSize;	// IMP=0x000000000002a005
- (void)viewDidMoveToSuperview;	// IMP=0x0000000000029fc4
- (BOOL)autoscroll:(id)arg1;	// IMP=0x0000000000029ee0
- (void)updateLayer;	// IMP=0x0000000000029dda
- (BOOL)resignFirstResponder;	// IMP=0x0000000000029d58
- (BOOL)canBecomeKeyView;	// IMP=0x0000000000029d50
- (id)defaultStringForToolTip:(long long)arg1 view:(id)arg2 point:(struct CGPoint)arg3 userData:(void *)arg4;	// IMP=0x0000000000029cdb
- (id)view:(id)arg1 stringForToolTip:(long long)arg2 point:(struct CGPoint)arg3 userData:(void *)arg4;	// IMP=0x0000000000029c41
- (void)unhandledScrollWheel:(id)arg1;	// IMP=0x0000000000029bb3
- (void)scrollWheel:(id)arg1;	// IMP=0x0000000000029ad6
- (id)supplementalTargetForAction:(SEL)arg1 sender:(id)arg2;	// IMP=0x0000000000029a19
- (void)awakeFromNib;	// IMP=0x000000000002996b
- (void)dealloc;	// IMP=0x0000000000029923
- (void)_saveAttachmentToDownloadsFolder:(id)arg1;	// IMP=0x0000000000029851
- (void)quicklookAttachment:(id)arg1;	// IMP=0x00000000000297a5
- (id)_clickedAttachmentControllerForUserData:(id)arg1;	// IMP=0x0000000000029580
- (id)_immediateActionAnimationControllerForHitTestResult:(id)arg1 withType:(long long)arg2 userData:(id)arg3;	// IMP=0x0000000000029434

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

