//
//     Generated by class-dump 3.5b1 (64 bit) (Debug version compiled Dec  3 2019 19:59:57).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <MailUIFW/NSPasteboardReading-Protocol.h>
#import <MailUIFW/NSPasteboardWriting-Protocol.h>
#import <MailUIFW/NSSecureCoding-Protocol.h>

@class MCFileWrapper, NSImage, NSString, NSURL;

@interface MUIWebAttachment : NSObject <NSPasteboardReading, NSPasteboardWriting, NSSecureCoding>
{
    NSString *_inlineTagName;	// 8 = 0x8
    NSString *_mimeType;	// 16 = 0x10
    NSString *_uti;	// 24 = 0x18
    NSURL *_fileURL;	// 32 = 0x20
    MCFileWrapper *_fileWrapper;	// 40 = 0x28
    NSString *_contentID;	// 48 = 0x30
    NSURL *_remoteURL;	// 56 = 0x38
    NSURL *_cidURL;	// 64 = 0x40
}

+ (id)readableTypesForPasteboard:(id)arg1;	// IMP=0x0000000000025046
+ (BOOL)supportsSecureCoding;	// IMP=0x00000000000241d0
@property(retain, nonatomic) NSURL *cidURL; // @synthesize cidURL=_cidURL;
@property(retain, nonatomic) NSURL *remoteURL; // @synthesize remoteURL=_remoteURL;
@property(copy, nonatomic) NSString *contentID; // @synthesize contentID=_contentID;
@property(readonly, nonatomic) MCFileWrapper *fileWrapper; // @synthesize fileWrapper=_fileWrapper;
// - (void).cxx_destruct;	// IMP=0x00000000000251b0
- (id)initWithPasteboardPropertyList:(id)arg1 ofType:(id)arg2;	// IMP=0x00000000000250a1
- (id)pasteboardPropertyListForType:(id)arg1;	// IMP=0x0000000000024fb7
- (id)writableTypesForPasteboard:(id)arg1;	// IMP=0x0000000000024f5c
- (id)_mimeTypeForFilename:(id)arg1;	// IMP=0x0000000000024ead
@property(readonly, nonatomic) BOOL shouldAlwaysAutomaticallyDownload;
@property(readonly, nonatomic) BOOL isDataDownloaded;
@property(readonly, nonatomic) __weak NSURL *downloadDirectory;
@property(readonly, nonatomic) BOOL isAutoArchiveAttachment;
@property(readonly, nonatomic) NSString *filenameForSaving;
@property(readonly, nonatomic) NSString *filename;
@property(readonly, nonatomic) NSImage *iconImage;
@property(readonly, nonatomic) unsigned long long fileSize;
@property(readonly, copy, nonatomic) NSString *inlineTagName;
@property(readonly, copy, nonatomic) NSString *uti;
@property(readonly, copy, nonatomic) NSString *mimeTypeForAttachmentTag;
@property(readonly, copy, nonatomic) NSString *mimeType;
- (id)_fileURLIfAvailable;	// IMP=0x00000000000246d2
@property(readonly, nonatomic) NSURL *fileURL;
- (void)encodeWithCoder:(id)arg1;	// IMP=0x00000000000243db
- (id)initWithCoder:(id)arg1;	// IMP=0x00000000000242aa
- (id)initWithFileWrapper:(id)arg1;	// IMP=0x0000000000002e49
- (id)init;	// IMP=0x00000000000241db

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

