github: apparition47
ko_fi: apparition47
custom: ['https://paypal.me/iOSguy', 'https://btcscan.org/address/3H5NJhYusExQfKusWggJxMdkfAg5VmPhYd', 'https://etherscan.io/address/0x1dee3868D0f77f2dB5F7465D89Ce51295106F223']
