//
//     Generated by class-dump 3.5b1 (64 bit) (Debug version compiled Dec  3 2019 19:59:57).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <MailFW/MFMessageSortingValue.h>

@interface _MFMessageSortingValueDateReceived : MFMessageSortingValue
{
    double _dateReceivedAsTimeIntervalSince1970;	// 8 = 0x8
}

@property(nonatomic) double dateReceivedAsTimeIntervalSince1970; // @synthesize dateReceivedAsTimeIntervalSince1970=_dateReceivedAsTimeIntervalSince1970;
- (id)description;	// IMP=0x000000000019e96f

@end

