//
//     Generated by class-dump 3.5b1 (64 bit) (Debug version compiled Dec  3 2019 19:59:57).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <MailFW/MFMessageSortingValue.h>

@interface _MFMessageSortingValueDateLastViewed : MFMessageSortingValue
{
    double _dateLastViewedAsTimeIntervalSince1970;	// 8 = 0x8
}

@property(nonatomic) double dateLastViewedAsTimeIntervalSince1970; // @synthesize dateLastViewedAsTimeIntervalSince1970=_dateLastViewedAsTimeIntervalSince1970;
- (id)description;	// IMP=0x000000000019e529

@end

