//
//     Generated by class-dump 3.5b1 (64 bit) (Debug version compiled Dec  3 2019 19:59:57).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <MailFW/MFMessageConsumer-Protocol.h>
#import <MailFW/MFQueryProgressMonitor-Protocol.h>

@class NSArray, NSMutableArray, NSString;

@interface _MFMessageCollector : NSObject <MFMessageConsumer, MFQueryProgressMonitor>
{
    NSMutableArray *_messages;	// 8 = 0x8
    BOOL _didCancel;	// 16 = 0x10
}

@property(nonatomic) BOOL didCancel; // @synthesize didCancel=_didCancel;
// - (void).cxx_destruct;	// IMP=0x0000000000109c27
- (void)finishedSendingMessages;	// IMP=0x0000000000109c0e
@property(readonly) BOOL shouldCancel;
- (void)newMessagesAvailable:(id)arg1 secondaryMessages:(id)arg2 fromUpdate:(BOOL)arg3;	// IMP=0x0000000000109b8a
@property(readonly, copy, nonatomic) NSArray *messages;
- (id)init;	// IMP=0x0000000000109b1e

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

