//
//     Generated by class-dump 3.5b1 (64 bit) (Debug version compiled Dec  3 2019 19:59:57).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableArray;
@protocol MFMessageConsumer;

@interface _MFMessageLoadingContext : NSObject
{
    unsigned int _options;	// 8 = 0x8
    NSMutableArray *_messages;	// 16 = 0x10
    id <MFMessageConsumer> _target;	// 24 = 0x18
    unsigned long long _chunkSize;	// 32 = 0x20
    double _chunkInterval;	// 40 = 0x28
    double _lastChunkSentTime;	// 48 = 0x30
    unsigned long long _messagesLoaded;	// 56 = 0x38
    struct sqlite3 *_database;	// 64 = 0x40
    long long _countOfMessagesProcessed;	// 72 = 0x48
}

@property(nonatomic) long long countOfMessagesProcessed; // @synthesize countOfMessagesProcessed=_countOfMessagesProcessed;
@property(nonatomic) struct sqlite3 *database; // @synthesize database=_database;
@property(nonatomic) unsigned int options; // @synthesize options=_options;
@property(nonatomic) unsigned long long messagesLoaded; // @synthesize messagesLoaded=_messagesLoaded;
@property(nonatomic) double lastChunkSentTime; // @synthesize lastChunkSentTime=_lastChunkSentTime;
@property(nonatomic) double chunkInterval; // @synthesize chunkInterval=_chunkInterval;
@property(nonatomic) unsigned long long chunkSize; // @synthesize chunkSize=_chunkSize;
@property(retain, nonatomic) id <MFMessageConsumer> target; // @synthesize target=_target;
@property(retain, nonatomic) NSMutableArray *messages; // @synthesize messages=_messages;
// - (void).cxx_destruct;	// IMP=0x0000000000109af6
- (id)description;	// IMP=0x0000000000109902

@end

