//
//     Generated by class-dump 3.5b1 (64 bit) (Debug version compiled Dec  3 2019 19:59:57).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDictionary;

@interface _MFRedundantTextIdentifierSolutionGenerator : NSObject
{
    CDStruct_f9502b4c *_replyBuffer;	// 8 = 0x8
    CDStruct_f9502b4c *_originalBuffer;	// 16 = 0x10
    long long _replyLength;	// 24 = 0x18
    long long _originalLength;	// 32 = 0x20
    NSDictionary *_originalAttachmentContextsByURL;	// 40 = 0x28
    NSDictionary *_replyAttachmentContextsByURL;	// 48 = 0x30
}

@property(readonly, copy, nonatomic) NSDictionary *replyAttachmentContextsByURL; // @synthesize replyAttachmentContextsByURL=_replyAttachmentContextsByURL;
@property(readonly, copy, nonatomic) NSDictionary *originalAttachmentContextsByURL; // @synthesize originalAttachmentContextsByURL=_originalAttachmentContextsByURL;
@property(readonly, nonatomic) long long originalLength; // @synthesize originalLength=_originalLength;
@property(readonly, nonatomic) long long replyLength; // @synthesize replyLength=_replyLength;
@property(readonly, nonatomic) CDStruct_f9502b4c *originalBuffer; // @synthesize originalBuffer=_originalBuffer;
@property(readonly, nonatomic) CDStruct_f9502b4c *replyBuffer; // @synthesize replyBuffer=_replyBuffer;
// - (void).cxx_destruct;	// IMP=0x00000000001efe81
- (id)generateBestSolutionInForwardDirection:(BOOL)arg1 replyStartIndex:(long long)arg2 originalStartIndex:(long long)arg3;	// IMP=0x00000000001ef64a
- (id)generateBestSolution;	// IMP=0x00000000001ef135
- (id)init;	// IMP=0x00000000001ef066
- (id)initWithReply:(CDStruct_f9502b4c *)arg1 replyLength:(long long)arg2 replyAttachmentContextsByURL:(id)arg3 original:(CDStruct_f9502b4c *)arg4 originalLength:(long long)arg5 originalAttachmentContextsByURL:(id)arg6;	// IMP=0x00000000001eef85

@end

