//
//     Generated by class-dump 3.5b1 (64 bit) (Debug version compiled Dec  3 2019 19:59:57).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSEntityDescription, NSPersistentStoreCoordinator, NSString;

@interface _MFSeenMessagesStore : NSObject
{
    NSPersistentStoreCoordinator *_persistentStoreCoordinator;	// 8 = 0x8
    NSString *_persistentStorePath;	// 16 = 0x10
    NSEntityDescription *_accountEntity;	// 24 = 0x18
    NSEntityDescription *_seenMessageEntity;	// 32 = 0x20
}

@property(retain, nonatomic) NSEntityDescription *seenMessageEntity; // @synthesize seenMessageEntity=_seenMessageEntity;
@property(retain, nonatomic) NSEntityDescription *accountEntity; // @synthesize accountEntity=_accountEntity;
@property(readonly, copy, nonatomic) NSString *persistentStorePath; // @synthesize persistentStorePath=_persistentStorePath;
@property(readonly, nonatomic) NSPersistentStoreCoordinator *persistentStoreCoordinator; // @synthesize persistentStoreCoordinator=_persistentStoreCoordinator;
// - (void).cxx_destruct;	// IMP=0x0000000000204584
- (id)_managedObjectModel;	// IMP=0x0000000000203fab
- (id)init;	// IMP=0x0000000000203e08

@end

