//
//     Generated by class-dump 3.5b1 (64 bit) (Debug version compiled Dec  3 2019 19:59:57).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <MailFW/NSCopying-Protocol.h>
#import <MailFW/NSObject-Protocol.h>

@class ACAccount, NSArray, NSString;

@protocol ECMailAccount <NSObject, NSCopying>
@property(readonly, copy) NSString *identifier;
@property(copy) NSString *password;
@property(copy) NSString *hostname;
@property(readonly, copy) NSArray *emailAddressStrings;
- (ACAccount *)systemAccount;
@end

