//
//     Generated by class-dump 3.5b1 (64 bit) (Debug version compiled Dec  3 2019 19:59:57).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <MailFW/IMAPMessage-Protocol.h>
#import <MailFW/MCChanging-Protocol.h>

@class NSData, NSString;

@protocol IMAPPersistedMessage <IMAPMessage, MCChanging>
@property(readonly, nonatomic) long long libraryID;
@property(copy) NSString *remoteID;
- (void)appendMimeData:(NSData *)arg1 partNumber:(NSString *)arg2;
- (void)setData:(NSData *)arg1 isPartial:(BOOL)arg2;
@end

