//
//     Generated by class-dump 3.5b1 (64 bit) (Debug version compiled Dec  3 2019 19:59:57).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <MailFW/ECMailbox-Protocol.h>
#import <MailFW/NSCopying-Protocol.h>

@class NSString;

@protocol MCMailbox <ECMailbox, NSCopying>
@property(readonly, nonatomic) BOOL useTotalInsteadOfUnread;
@property BOOL useStatusCounts;
@property(readonly) BOOL unseenCountIsKnown;
@property(readonly) unsigned long long unseenCount;
@property(readonly, copy, nonatomic) NSString *URLString;
@property(readonly, copy, nonatomic) NSString *extendedDisplayNameWithoutPII;
@property(readonly, copy, nonatomic) NSString *extendedDisplayName;
@property(readonly, copy, nonatomic) NSString *displayNameWithoutPII;
@property(readonly, copy, nonatomic) NSString *displayName;
- (void)setUserInfoObject:(id)arg1 forKey:(NSString *)arg2;
- (id)userInfoObjectForKey:(NSString *)arg1;
- (void)setUserInfoBool:(BOOL)arg1 forKey:(NSString *)arg2;
- (BOOL)userInfoBoolForKey:(NSString *)arg1;
- (void)queueUpdateDisplayCountFromStatus:(unsigned long long)arg1;
@end

