//
//     Generated by class-dump 3.5b1 (64 bit) (Debug version compiled Dec  3 2019 19:59:57).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <MailFW/EDAccountsProvider-Protocol.h>

@class NSArray;

@interface MFAccountProvider : NSObject <EDAccountsProvider>
{
}

@property(readonly, copy, nonatomic) NSArray *receivingAddresses;
- (id)mailAccounts;	// IMP=0x0000000000013443

@end

