//
//     Generated by class-dump 3.5b1 (64 bit) (Debug version compiled Dec  3 2019 19:59:57).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <MailFW/EDAccountFactory-Protocol.h>

@interface MFAccountFactory_macOS : NSObject <EDAccountFactory>
{
}

- (id)accountWithSystemAccount:(id)arg1;	// IMP=0x000000000000b43e
- (id)accountWithIdentifier:(id)arg1;	// IMP=0x000000000000b425

@end

