//
//     Generated by class-dump 3.5b1 (64 bit) (Debug version compiled Dec  3 2019 19:59:57).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <MailFW/MFMessageRule.h>

@class EMBlockedSenderManager, MFMailbox, NSColor, NSString;

@interface MFBlockedSenderRule : MFMessageRule
{
    BOOL _shouldTransferMessage;	// 8 = 0x8
    BOOL _shouldNotifyUser;	// 9 = 0x9
    BOOL _shouldSendNotification;	// 10 = 0xa
    BOOL _isDefaultRule;	// 11 = 0xb
    int _autoResponseType;	// 12 = 0xc
    NSString *_ruleName;	// 16 = 0x10
    long long _flagsToApply;	// 24 = 0x18
    NSString *_appleScriptPath;	// 32 = 0x20
    NSColor *_color;	// 40 = 0x28
    NSString *_playSound;	// 48 = 0x30
    MFMailbox *_destinationMailbox;	// 56 = 0x38
    EMBlockedSenderManager *_blockedSenderManager;	// 64 = 0x40
}

@property(retain, nonatomic) EMBlockedSenderManager *blockedSenderManager; // @synthesize blockedSenderManager=_blockedSenderManager;
- (void)setIsDefaultRule:(BOOL)arg1;	// IMP=0x000000000002b466
- (BOOL)isDefaultRule;	// IMP=0x000000000002b455
- (void)setDestinationMailbox:(id)arg1;	// IMP=0x000000000002b441
- (id)destinationMailbox;	// IMP=0x000000000002b430
- (void)setShouldSendNotification:(BOOL)arg1;	// IMP=0x000000000002b420
- (BOOL)shouldSendNotification;	// IMP=0x000000000002b40f
- (void)setShouldNotifyUser:(BOOL)arg1;	// IMP=0x000000000002b3ff
- (BOOL)shouldNotifyUser;	// IMP=0x000000000002b3ee
- (void)setShouldTransferMessage:(BOOL)arg1;	// IMP=0x000000000002b3de
- (BOOL)shouldTransferMessage;	// IMP=0x000000000002b3cd
- (void)setPlaySound:(id)arg1;	// IMP=0x000000000002b3bc
- (id)playSound;	// IMP=0x000000000002b3a9
- (void)setAutoResponseType:(int)arg1;	// IMP=0x000000000002b399
- (int)autoResponseType;	// IMP=0x000000000002b389
- (void)setColor:(id)arg1;	// IMP=0x000000000002b375
- (id)color;	// IMP=0x000000000002b364
- (void)setAppleScriptPath:(id)arg1;	// IMP=0x000000000002b353
- (id)appleScriptPath;	// IMP=0x000000000002b340
- (void)setFlagsToApply:(long long)arg1;	// IMP=0x000000000002b32f
- (long long)flagsToApply;	// IMP=0x000000000002b31e
- (void)setRuleName:(id)arg1;	// IMP=0x000000000002b30d
- (id)ruleName;	// IMP=0x000000000002b2fa
// - (void).cxx_destruct;	// IMP=0x000000000002b49b
- (id)description;	// IMP=0x000000000002b28e
- (void)setIsActive:(BOOL)arg1;	// IMP=0x000000000002b242
- (BOOL)isActive;	// IMP=0x000000000002b1fd
- (BOOL)doesMessageSatisfyCriteria:(id)arg1 fetchBody:(BOOL)arg2 needsBody:(char *)arg3 successfullyEvaluated:(char *)arg4;	// IMP=0x000000000002b0ed
- (id)initWithBlockedSenderManager:(id)arg1;	// IMP=0x000000000002af9b

@end

