//
//     Generated by class-dump 3.5b1 (64 bit) (Debug version compiled Dec  3 2019 19:59:57).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface MFCriteriaUpgrader : NSObject
{
}

+ (id)upgradeCriteriaFromUbiquitousVersion3To4:(id)arg1;	// IMP=0x000000000003fbc5

@end

