//
//     Generated by class-dump 3.5b1 (64 bit) (Debug version compiled Dec  3 2019 19:59:57).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSCondition, NSString;

@interface MFDatabaseRecoverer : NSObject
{
    NSCondition *_analysisCondition;	// 8 = 0x8
    NSString *_path;	// 16 = 0x10
    long long _type;	// 24 = 0x18
    long long _analysisResult;	// 32 = 0x20
}

+ (BOOL)moveDatabaseFromPath:(id)arg1 toPath:(id)arg2;	// IMP=0x000000000004d67a
+ (id)moveDatabaseToUniquePath:(id)arg1;	// IMP=0x000000000004d4fe
@property long long analysisResult; // @synthesize analysisResult=_analysisResult;
@property long long type; // @synthesize type=_type;
@property(copy) NSString *path; // @synthesize path=_path;
// - (void).cxx_destruct;	// IMP=0x000000000004d993
- (void)_moveToOriginalPath:(id)arg1;	// IMP=0x000000000004d482
- (id)_moveToUniquePath;	// IMP=0x000000000004d41f
- (void)_removeLocks;	// IMP=0x000000000004d300
- (void)recover;	// IMP=0x000000000004d174
- (void)removeLockFile;	// IMP=0x000000000004d0d1
@property(readonly) BOOL lockFileFound;
@property(readonly) BOOL aRemoteApplicationIsAccessingTheDatabase;
@property(readonly) BOOL fileLocked;
- (void)analyzeBusyCondition;	// IMP=0x000000000004ce25
- (void)_analyzeBusyCondition;	// IMP=0x000000000004cd64
- (id)init;	// IMP=0x000000000004cd4e
- (id)initWithPath:(id)arg1 type:(long long)arg2;	// IMP=0x000000000004cc9c

@end

