//
//     Generated by class-dump 3.5b1 (64 bit) (Debug version compiled Dec  3 2019 19:59:57).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class ECAngleBracketIDHash, ECSubject, MCMessageHeaders, MFMessageWritePreparedStatements, NSArray, NSString, NSUUID;

@interface MFDatabaseWritableMessage : NSObject
{
    char *_color;	// 8 = 0x8
    BOOL _messageType;	// 16 = 0x10
    int _automatedConversationType;	// 20 = 0x14
    int _rootStatus;	// 24 = 0x18
    int _conversationPosition;	// 28 = 0x1c
    int _dateReceived;	// 32 = 0x20
    int _dateSent;	// 36 = 0x24
    int _dateViewed;	// 40 = 0x28
    long long _subjectID;	// 48 = 0x30
    long long _senderID;	// 56 = 0x38
    long long _conversationID;	// 64 = 0x40
    long long _mailboxID;	// 72 = 0x48
    long long _fuzzyAncestor;	// 80 = 0x50
    unsigned long long _conversationFlags;	// 88 = 0x58
    unsigned long long _size;	// 96 = 0x60
    long long _flags;	// 104 = 0x68
    NSString *_sender;	// 112 = 0x70
    ECSubject *_subject;	// 120 = 0x78
    ECAngleBracketIDHash *_messageIDHeaderHash;	// 128 = 0x80
    NSString *_remoteMailboxIDString;	// 136 = 0x88
    NSArray *_toRecipients;	// 144 = 0x90
    NSUUID *_documentID;	// 152 = 0x98
    MCMessageHeaders *_headers;	// 160 = 0xa0
    NSArray *_referencesHashes;	// 168 = 0xa8
    ECAngleBracketIDHash *_listIDHash;	// 176 = 0xb0
    MFMessageWritePreparedStatements *_preparedStatements;	// 184 = 0xb8
}

@property(readonly, nonatomic) MFMessageWritePreparedStatements *preparedStatements; // @synthesize preparedStatements=_preparedStatements;
@property(retain, nonatomic) ECAngleBracketIDHash *listIDHash; // @synthesize listIDHash=_listIDHash;
@property(copy, nonatomic) NSArray *referencesHashes; // @synthesize referencesHashes=_referencesHashes;
@property(retain, nonatomic) MCMessageHeaders *headers; // @synthesize headers=_headers;
@property(retain, nonatomic) NSUUID *documentID; // @synthesize documentID=_documentID;
@property(copy, nonatomic) NSArray *toRecipients; // @synthesize toRecipients=_toRecipients;
@property(copy, nonatomic) NSString *remoteMailboxIDString; // @synthesize remoteMailboxIDString=_remoteMailboxIDString;
@property(copy, nonatomic) ECAngleBracketIDHash *messageIDHeaderHash; // @synthesize messageIDHeaderHash=_messageIDHeaderHash;
@property(copy, nonatomic) ECSubject *subject; // @synthesize subject=_subject;
@property(copy, nonatomic) NSString *sender; // @synthesize sender=_sender;
@property(nonatomic) long long flags; // @synthesize flags=_flags;
@property(nonatomic) unsigned long long size; // @synthesize size=_size;
@property(nonatomic) BOOL messageType; // @synthesize messageType=_messageType;
@property(nonatomic) int dateViewed; // @synthesize dateViewed=_dateViewed;
@property(nonatomic) int dateSent; // @synthesize dateSent=_dateSent;
@property(nonatomic) int dateReceived; // @synthesize dateReceived=_dateReceived;
@property(nonatomic) unsigned long long conversationFlags; // @synthesize conversationFlags=_conversationFlags;
@property(nonatomic) int conversationPosition; // @synthesize conversationPosition=_conversationPosition;
@property(nonatomic) int rootStatus; // @synthesize rootStatus=_rootStatus;
@property(nonatomic) int automatedConversationType; // @synthesize automatedConversationType=_automatedConversationType;
@property(nonatomic) long long fuzzyAncestor; // @synthesize fuzzyAncestor=_fuzzyAncestor;
@property(nonatomic) long long mailboxID; // @synthesize mailboxID=_mailboxID;
@property(nonatomic) long long conversationID; // @synthesize conversationID=_conversationID;
@property(nonatomic) long long senderID; // @synthesize senderID=_senderID;
@property(nonatomic) long long subjectID; // @synthesize subjectID=_subjectID;
// - (void).cxx_destruct;	// IMP=0x0000000000051e7f
- (long long)_rowIDForSubject:(id)arg1 subjectRowIDsCache:(id)arg2 cacheIsExhaustive:(BOOL)arg3;	// IMP=0x0000000000051831
- (id)propertyListFromMessage:(id)arg1 remoteID:(id)arg2 gmailLabels:(id)arg3;	// IMP=0x000000000005158a
- (void)setupLibraryMessage:(id)arg1 fromMessage:(id)arg2;	// IMP=0x00000000000510f6
- (void)bindFieldsToPreparedStatement:(id)arg1 isUpdate:(BOOL)arg2;	// IMP=0x0000000000050891
- (BOOL)updateFieldsFromMessage:(id)arg1 subjectRowIDsCache:(id)arg2 addressRowIDsCache:(id)arg3 cacheIsExhaustive:(BOOL)arg4;	// IMP=0x000000000004fe58
- (long long)_rowIDForAddress:(id)arg1 comment:(id)arg2;	// IMP=0x000000000004fc34
- (long long)_rowIDForAddressText:(id)arg1 cache:(id)arg2 cacheIsExhaustive:(BOOL)arg3;	// IMP=0x000000000004f601
- (BOOL)_insertRecipientsWithMessageID:(long long)arg1 recipients:(id)arg2 recipientType:(BOOL)arg3 position:(unsigned long long)arg4 addressRowIDsCache:(id)arg5 cacheIsExhaustive:(BOOL)arg6;	// IMP=0x000000000004f221
- (BOOL)insertRecpientsWithMessageID:(long long)arg1 fromMessage:(id)arg2 addressRowIDsCache:(id)arg3 cacheIsExhaustive:(BOOL)arg4;	// IMP=0x000000000004ee8a
- (void)insertCalendarEvent:(id)arg1 withMessageID:(long long)arg2;	// IMP=0x000000000004ed89
- (void)insertAttachmentsWithMessageID:(long long)arg1 fromMessage:(id)arg2;	// IMP=0x000000000004e929
- (BOOL)insertReferencesWithMessageID:(long long)arg1;	// IMP=0x000000000004e5d1
- (void)updateFieldsFromLibraryWithMessageRowID:(long long)arg1;	// IMP=0x000000000004dbdf
@property(nonatomic) char *color;
- (void)dealloc;	// IMP=0x000000000004db2c
- (id)init;	// IMP=0x000000000004da5d
- (id)initWithPreparedStatements:(id)arg1;	// IMP=0x000000000004d9bb

@end

