//
//     Generated by class-dump 3.5b1 (64 bit) (Debug version compiled Dec  3 2019 19:59:57).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <MailFW/NSObject-Protocol.h>

@class MFEWSGetMessagesNeedingBodiesOperation, MFMailbox, NSArray;

@protocol MFEWSGetMessagesNeedingBodiesOperationDelegate <NSObject>
- (void)getMessagesNeedingBodiesOperation:(MFEWSGetMessagesNeedingBodiesOperation *)arg1 didGetMessagesNeedingBodies:(NSArray *)arg2 forMailbox:(MFMailbox *)arg3;
@end

