//
//     Generated by class-dump 3.5b1 (64 bit) (Debug version compiled Dec  3 2019 19:59:57).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <MailFW/MCBodyFetchContext-Protocol.h>

@class MFEWSAccountTaskManager, MFEWSVisibleBodyFetchTask, NSString;

@interface MFEWSBodyFetchContext : NSObject <MCBodyFetchContext>
{
    MFEWSVisibleBodyFetchTask *_bodyFetchTask;	// 8 = 0x8
    MFEWSAccountTaskManager *_manager;	// 16 = 0x10
}

@property(readonly, nonatomic) MFEWSAccountTaskManager *manager; // @synthesize manager=_manager;
// - (void).cxx_destruct;	// IMP=0x00000000000677a7
- (void)cacheBodiesForMessages:(id)arg1;	// IMP=0x0000000000067574
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;	// IMP=0x0000000000067415
- (void)setBodyFetchTask:(id)arg1;	// IMP=0x000000000006737f
@property(readonly, nonatomic) MFEWSVisibleBodyFetchTask *bodyFetchTask;
- (void)dealloc;	// IMP=0x0000000000067249
- (id)init;	// IMP=0x000000000006717a
- (id)initWithTaskManager:(id)arg1;	// IMP=0x000000000006710f

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

