//
//     Generated by class-dump 3.5b1 (64 bit) (Debug version compiled Dec  3 2019 19:59:57).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <MailFW/MFRemoteStoreAccount.h>

@class ECExchangeAccount, MFEWSAccountTaskManager, MFEWSConnection, MFEWSDeliveryAccount, MFEWSGateway, NSDate, NSDictionary, NSMutableDictionary, NSOperationQueue, NSString, NSTimer, NSURL, NSUUID;

@interface MFEWSAccount : MFRemoteStoreAccount
{
    MFEWSConnection *_connection;	// 8 = 0x8
    NSMutableDictionary *_folderIdsToMailboxes;	// 16 = 0x10
    id _connectionLock;	// 24 = 0x18
    id _folderHierarchySyncLock;	// 32 = 0x20
    NSOperationQueue *_remoteTaskQueue;	// 40 = 0x28
    NSOperationQueue *_remoteFetchQueue;	// 48 = 0x30
    MFEWSGateway *_gateway;	// 56 = 0x38
    NSDictionary *_distinguishedFolderIdsAndMailboxTypes;	// 64 = 0x40
    NSString *_lastOpenedFolderID;	// 72 = 0x48
    long long _externalAudienceType;	// 80 = 0x50
    NSUUID *_messageTracerUUID;	// 88 = 0x58
    NSOperationQueue *_requestResponseQueue;	// 96 = 0x60
    NSOperationQueue *_bodyFetchQueue;	// 104 = 0x68
    double _lastFullFetchDuration;	// 112 = 0x70
    double _lastFullFetchTime;	// 120 = 0x78
    NSString *_syncIssuesEntryID;	// 128 = 0x80
    NSTimer *_autodiscoveryTimer;	// 136 = 0x88
    NSOperationQueue *_autodiscoverQueue;	// 144 = 0x90
    MFEWSDeliveryAccount *_ewsDeliveryAccount;	// 152 = 0x98
}

+ (void)resetAllFolderHierarchySyncStates;	// IMP=0x0000000000060199
+ (id)standardSSLPorts;	// IMP=0x00000000000593c8
+ (id)standardPorts;	// IMP=0x00000000000593af
+ (id)csAccountTypeString;	// IMP=0x000000000005939b
+ (id)accountTypeString;	// IMP=0x0000000000059387
@property(readonly, nonatomic) MFEWSDeliveryAccount *ewsDeliveryAccount; // @synthesize ewsDeliveryAccount=_ewsDeliveryAccount;
@property(readonly, nonatomic) NSOperationQueue *autodiscoverQueue; // @synthesize autodiscoverQueue=_autodiscoverQueue;
@property(readonly, nonatomic) NSTimer *autodiscoveryTimer; // @synthesize autodiscoveryTimer=_autodiscoveryTimer;
@property(retain) NSString *syncIssuesEntryID; // @synthesize syncIssuesEntryID=_syncIssuesEntryID;
@property double lastFullFetchTime; // @synthesize lastFullFetchTime=_lastFullFetchTime;
@property double lastFullFetchDuration; // @synthesize lastFullFetchDuration=_lastFullFetchDuration;
@property(retain) MFEWSConnection *connection; // @synthesize connection=_connection;
@property(readonly, nonatomic) NSOperationQueue *bodyFetchQueue; // @synthesize bodyFetchQueue=_bodyFetchQueue;
@property(readonly, nonatomic) NSOperationQueue *requestResponseQueue; // @synthesize requestResponseQueue=_requestResponseQueue;
@property(retain) NSUUID *messageTracerUUID; // @synthesize messageTracerUUID=_messageTracerUUID;
@property long long externalAudienceType; // @synthesize externalAudienceType=_externalAudienceType;
@property(retain) NSString *lastOpenedFolderID; // @synthesize lastOpenedFolderID=_lastOpenedFolderID;
@property(retain) NSDictionary *distinguishedFolderIdsAndMailboxTypes; // @synthesize distinguishedFolderIdsAndMailboxTypes=_distinguishedFolderIdsAndMailboxTypes;
@property(retain, nonatomic) MFEWSGateway *gateway; // @synthesize gateway=_gateway;
- (id)remoteFetchQueue;	// IMP=0x000000000006095d
- (id)remoteTaskQueue;	// IMP=0x000000000006094c
// - (void).cxx_destruct;	// IMP=0x0000000000060b25
- (void)syncMailbox:(id)arg1;	// IMP=0x00000000000608da
- (void)messageTraceEWSParameters;	// IMP=0x000000000006068d
- (BOOL)_setEWSError:(id)arg1;	// IMP=0x000000000005ffe6
- (void)mailboxWasOpened:(id)arg1;	// IMP=0x000000000005fecf
- (id)loadFolderIdForMailbox:(id)arg1;	// IMP=0x000000000005fcfa
- (void)_clearFolderId:(id)arg1 forMailbox:(id)arg2;	// IMP=0x000000000005fc08
- (void)_saveFolderId:(id)arg1 forMailbox:(id)arg2;	// IMP=0x000000000005faf3
- (void)_setMailbox:(id)arg1 forFolderId:(id)arg2;	// IMP=0x000000000005fa3a
- (id)mailboxForFolderIdString:(id)arg1;	// IMP=0x000000000005f9a5
- (void)_setupMailbox:(id)arg1 forFolderId:(id)arg2;	// IMP=0x000000000005f5e3
- (void)updateEWSOfflineIdsToRealIds:(id)arg1 forFolders:(BOOL)arg2;	// IMP=0x000000000005f384
- (id)deletedEWSIdStringsFromStrings:(id)arg1 inFolderWithIdString:(id)arg2;	// IMP=0x000000000005ef61
- (void)undeleteMessagesWithEWSItemIdStrings:(id)arg1 fromFolderWithIdString:(id)arg2;	// IMP=0x000000000005eda0
- (void)deleteEWSItemsWithIdStrings:(id)arg1 fromFolderWithIdString:(id)arg2;	// IMP=0x000000000005ea90
- (void)deleteMailboxForEWSFolderIdString:(id)arg1;	// IMP=0x000000000005ea47
- (void)updateMailboxForEWSFolder:(id)arg1;	// IMP=0x000000000005e7b3
- (BOOL)_isSyncIssuesFolder:(id)arg1;	// IMP=0x000000000005e507
- (void)createMailboxFromEWSFolder:(id)arg1;	// IMP=0x000000000005e053
- (id)mailboxNameForFolderIdString:(id)arg1;	// IMP=0x000000000005df3b
- (void)messageDeliveryDidFinish:(id)arg1;	// IMP=0x000000000005ddc8
@property(retain) NSDate *lastSyncDate;
- (BOOL)_shouldHideMailbox:(id)arg1 withType:(int)arg2;	// IMP=0x000000000005dc4a
- (void)setUserOofSettingsState:(long long)arg1 internalReply:(id)arg2 externalReply:(id)arg3 startTime:(id)arg4 endTime:(id)arg5;	// IMP=0x000000000005db63
- (void)getUserOofSettings;	// IMP=0x000000000005db26
@property __weak NSURL *externalConnectionURL;
- (void)_setInternalConnectionURL:(id)arg1 releasingConnections:(BOOL)arg2;	// IMP=0x000000000005d8fc
@property __weak NSURL *internalConnectionURL;
@property(retain) NSURL *lastUsedAutodiscoverURL;
@property(retain) NSString *rootFolderId;
@property(retain) NSString *folderHierarchySyncState;
- (id)_connectionURLBySettingServerPath:(id)arg1 inConnectionURL:(id)arg2;	// IMP=0x000000000005d2a4
@property(copy) NSString *externalServerPath;
@property(copy) NSString *internalServerPath;
- (id)_connectionURLBySettingUsesSSL:(BOOL)arg1 inConnectionURL:(id)arg2;	// IMP=0x000000000005d01b
- (BOOL)_usesSSLFromConnectionURL:(id)arg1;	// IMP=0x000000000005cfcb
@property BOOL externalUsesSSL;
- (id)_connectionURLBySettingPortNumber:(long long)arg1 inConnectionURL:(id)arg2;	// IMP=0x000000000005cd78
- (long long)_portNumberFromConnectionURL:(id)arg1;	// IMP=0x000000000005cc84
@property long long externalPortNumber;
- (id)_connectionURLBySettingHostname:(id)arg1 inConnectionURL:(id)arg2;	// IMP=0x000000000005ca8a
- (void)setExternalHostname:(id)arg1;	// IMP=0x000000000005c9f3
- (id)externalHostname;	// IMP=0x000000000005c9a3
- (id)_specialMailboxWithType:(int)arg1 create:(BOOL)arg2 isLocal:(BOOL)arg3;	// IMP=0x000000000005c671
- (id)dynamicDeliveryAccount;	// IMP=0x000000000005c65f
- (void)setDeliveryAccount:(id)arg1;	// IMP=0x000000000005c490
- (id)deliveryAccount;	// IMP=0x000000000005c3cf
- (id)_folderNameForMailboxDisplayName:(id)arg1;	// IMP=0x000000000005c3ba
- (id)_mailboxDisplayNameForFolderName:(id)arg1;	// IMP=0x000000000005c3a5
- (id)validNameForMailbox:(id)arg1 fromDisplayName:(id)arg2 error:(id *)arg3;	// IMP=0x000000000005c304
- (BOOL)supportsSlashesInMailboxName;	// IMP=0x000000000005c2f9
- (BOOL)_deleteMailbox:(id)arg1 reflectToServer:(BOOL)arg2;	// IMP=0x000000000005c1bd
- (BOOL)canMailboxBeDeleted:(id)arg1;	// IMP=0x000000000005c127
- (BOOL)renameMailbox:(id)arg1 newDisplayName:(id)arg2 parent:(id)arg3;	// IMP=0x000000000005bdbd
- (BOOL)canMailboxBeRenamed:(id)arg1;	// IMP=0x000000000005bd27
- (id)_createMailboxWithParent:(id)arg1 displayName:(id)arg2 localizedDisplayName:(id)arg3 type:(int)arg4;	// IMP=0x000000000005b65c
- (id)createMailboxWithParent:(id)arg1 displayName:(id)arg2 localizedDisplayName:(id)arg3;	// IMP=0x000000000005b5dc
- (void)setEmailAddressStrings:(id)arg1;	// IMP=0x000000000005b4f8
- (BOOL)_readMailboxCache;	// IMP=0x000000000005b461
- (void)_setSpecialMailboxRelativePath:(id)arg1 forType:(int)arg2;	// IMP=0x000000000005b3ca
- (id)_specialMailboxRelativePathForType:(int)arg1;	// IMP=0x000000000005b318
- (id)_defaultSpecialMailboxRelativePathForType:(int)arg1;	// IMP=0x000000000005b256
- (BOOL)_setChildren:(id)arg1 forMailbox:(id)arg2;	// IMP=0x000000000005b0cc
- (void)_synchronouslyLoadListingForParent:(id)arg1;	// IMP=0x000000000005b0c6
- (BOOL)_supportsMailboxListInitialization;	// IMP=0x000000000005b0bb
@property(readonly) long long maximumConcurrentSyncFolderOperationCount;
- (void)_synchronizeMailboxesSynchronously;	// IMP=0x000000000005af1b
- (BOOL)_shouldSynchronizeMailbox:(id)arg1;	// IMP=0x000000000005aea7
- (void)stopAccountActivity;	// IMP=0x000000000005ae6a
- (void)fetchAsynchronouslyIsAuto:(BOOL)arg1;	// IMP=0x000000000005adf7
- (void)respondToHostBecomingReachable;	// IMP=0x000000000005ad79
- (id)primaryMailbox;	// IMP=0x000000000005ad62
- (void)setShouldMoveDeletedMessagesToTrash:(BOOL)arg1;	// IMP=0x000000000005ad5c
- (BOOL)shouldMoveDeletedMessagesToTrash;	// IMP=0x000000000005ad51
- (id)mailboxPathExtension;	// IMP=0x000000000005ace2
- (BOOL)defaultShouldShowNotesInInbox;	// IMP=0x000000000005acda
- (BOOL)supportsRichTextNotes;	// IMP=0x000000000005acd2
- (Class)storeClassForMailbox:(id)arg1;	// IMP=0x000000000005acb9
- (id)URLPersistenceScheme;	// IMP=0x000000000005aca5
- (void)setIsOffline:(BOOL)arg1;	// IMP=0x000000000005ac29
- (void)releaseAllConnections;	// IMP=0x000000000005abe9
- (BOOL)canAuthenticateWithScheme:(id)arg1;	// IMP=0x000000000005aad9
- (BOOL)connectAndAuthenticate:(id)arg1;	// IMP=0x0000000000059dbe
- (id)authenticatedConnection;	// IMP=0x0000000000059a30
- (id)newConnectedConnectionDiscoveringBestSettings:(BOOL)arg1 withConnectTimeout:(double)arg2 readWriteTimeout:(double)arg3;	// IMP=0x0000000000059993
- (BOOL)_systemAccountDidUpdateProperties:(id)arg1 fromPropertyDiscovery:(BOOL)arg2;	// IMP=0x00000000000597d8
- (BOOL)discoverConnectionPropertiesAndWait;	// IMP=0x000000000005977b
- (void)discoverConnectionProperties;	// IMP=0x0000000000059725
- (void)setConfigureDynamically:(BOOL)arg1;	// IMP=0x00000000000596b1
- (void)_setPortNumber:(long long)arg1 releasingConnections:(BOOL)arg2;	// IMP=0x000000000005962a
- (long long)portNumber;	// IMP=0x00000000000595d7
- (void)_setUsesSSL:(BOOL)arg1 releasingConnections:(BOOL)arg2;	// IMP=0x0000000000059550
- (BOOL)usesSSL;	// IMP=0x00000000000594fc
- (void)setHostname:(id)arg1;	// IMP=0x0000000000059465
- (id)hostname;	// IMP=0x0000000000059415
- (void)setAuthenticationScheme:(id)arg1;	// IMP=0x000000000005940f
- (void)setSecurityLayerType:(long long)arg1;	// IMP=0x0000000000059409
- (long long)securityLayerType;	// IMP=0x00000000000593ec
- (BOOL)requiresAuthentication;	// IMP=0x00000000000593e1
- (void)dealloc;	// IMP=0x00000000000592f0
- (id)_newTaskManager;	// IMP=0x0000000000059294
- (id)init;	// IMP=0x0000000000059206
- (id)initWithSystemAccount:(id)arg1;	// IMP=0x0000000000058d04

// Remaining properties
@property(readonly) ECExchangeAccount *baseAccount; // @dynamic baseAccount;
@property(readonly, nonatomic) MFEWSAccountTaskManager *taskManager; // @dynamic taskManager;

@end

