//
//     Generated by class-dump 3.5b1 (64 bit) (Debug version compiled Dec  3 2019 19:59:57).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <MailFW/MFEWSTask.h>

#import <MailFW/MFEWSPersistFolderHierarchyTaskOperationDelegate-Protocol.h>
#import <MailFW/MFEWSSyncFolderHierarchyTaskOperationDelegate-Protocol.h>

@class MFEWSPersistFolderHierarchyTaskOperation, MFEWSPruneFolderHierarchyTaskOperation, MFEWSSyncFolderHierarchyTaskOperation, NSMutableArray, NSMutableSet, NSString;

@interface MFEWSFolderHierarchyReconcileTask : MFEWSTask <MFEWSSyncFolderHierarchyTaskOperationDelegate, MFEWSPersistFolderHierarchyTaskOperationDelegate>
{
    MFEWSSyncFolderHierarchyTaskOperation *_syncFolderHierarchyTaskOperation;	// 8 = 0x8
    MFEWSPersistFolderHierarchyTaskOperation *_persistFolderHierarchyTaskOperation;	// 16 = 0x10
    NSMutableArray *_pendingBatchesToPersist;	// 24 = 0x18
    NSMutableSet *_foundFolderIdStrings;	// 32 = 0x20
    NSString *_syncStateToReconcile;	// 40 = 0x28
    MFEWSPruneFolderHierarchyTaskOperation *_pruneFolderHierarchyTaskOperation;	// 48 = 0x30
}

@property(retain, nonatomic) MFEWSPruneFolderHierarchyTaskOperation *pruneFolderHierarchyTaskOperation; // @synthesize pruneFolderHierarchyTaskOperation=_pruneFolderHierarchyTaskOperation;
@property(copy, nonatomic) NSString *syncStateToReconcile; // @synthesize syncStateToReconcile=_syncStateToReconcile;
// - (void).cxx_destruct;	// IMP=0x000000000007f859
- (void)recalculatePriorities;	// IMP=0x000000000007f69a
- (void)operationFinished:(id)arg1;	// IMP=0x000000000007f55f
- (void)persistFolderHierarchyOperation:(id)arg1 completedBatch:(id)arg2;	// IMP=0x000000000007f024
- (void)syncFolderHierarchyTaskOperation:(id)arg1 completedBatch:(id)arg2;	// IMP=0x000000000007eb83
- (id)nextPersistenceOperation;	// IMP=0x000000000007e998
- (id)nextNetworkOperation;	// IMP=0x000000000007e8d2
@property(retain, nonatomic) MFEWSPersistFolderHierarchyTaskOperation *persistFolderHierarchyTaskOperation;
@property(retain, nonatomic) MFEWSSyncFolderHierarchyTaskOperation *syncFolderHierarchyTaskOperation;
- (id)init;	// IMP=0x000000000007e6e9
- (id)initWithInitialSyncState:(id)arg1 accountName:(id)arg2;	// IMP=0x000000000007e573

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

