//
//     Generated by class-dump 3.5b1 (64 bit) (Debug version compiled Dec  3 2019 19:59:57).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSDictionary, NSMapTable, NSString;

@interface MFEWSMailboxItemsBatch : NSObject
{
    BOOL _isFinalBatch;	// 8 = 0x8
    NSString *_initialSyncState;	// 16 = 0x10
    NSString *_finalSyncState;	// 24 = 0x18
    NSMapTable *_createdOrUpdatedItemIDsByType;	// 32 = 0x20
    NSArray *_deletedItemIDs;	// 40 = 0x28
    NSDictionary *_readFlagChangesByItemID;	// 48 = 0x30
    NSDictionary *_fetchedItemsByID;	// 56 = 0x38
    NSArray *_addedMessages;	// 64 = 0x40
}

@property(copy, nonatomic) NSArray *addedMessages; // @synthesize addedMessages=_addedMessages;
@property(copy, nonatomic) NSDictionary *fetchedItemsByID; // @synthesize fetchedItemsByID=_fetchedItemsByID;
@property(copy, nonatomic) NSDictionary *readFlagChangesByItemID; // @synthesize readFlagChangesByItemID=_readFlagChangesByItemID;
@property(copy, nonatomic) NSArray *deletedItemIDs; // @synthesize deletedItemIDs=_deletedItemIDs;
@property(copy, nonatomic) NSMapTable *createdOrUpdatedItemIDsByType; // @synthesize createdOrUpdatedItemIDsByType=_createdOrUpdatedItemIDsByType;
@property(nonatomic) BOOL isFinalBatch; // @synthesize isFinalBatch=_isFinalBatch;
@property(copy, nonatomic) NSString *finalSyncState; // @synthesize finalSyncState=_finalSyncState;
@property(copy, nonatomic) NSString *initialSyncState; // @synthesize initialSyncState=_initialSyncState;
// - (void).cxx_destruct;	// IMP=0x000000000008b556
- (id)description;	// IMP=0x000000000008b126

@end

