//
//     Generated by class-dump 3.5b1 (64 bit) (Debug version compiled Dec  3 2019 19:59:57).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <MailCore/MCTaskHandlerOperation.h>

@class NSArray;
@protocol MFEWSRetrievePersistedFolderDataDelegate;

@interface MFEWSRetrievePersistedFolderDataOperation : MCTaskHandlerOperation
{
    id <MFEWSRetrievePersistedFolderDataDelegate> _delegate;	// 8 = 0x8
    NSArray *_mailboxURLs;	// 16 = 0x10
}

@property(readonly, copy, nonatomic) NSArray *mailboxURLs; // @synthesize mailboxURLs=_mailboxURLs;
@property(nonatomic) __weak id <MFEWSRetrievePersistedFolderDataDelegate> delegate; // @synthesize delegate=_delegate;
// - (void).cxx_destruct;	// IMP=0x000000000009fa59
- (void)main;	// IMP=0x000000000009f6ea
- (id)init;	// IMP=0x000000000009f61b
- (id)initWithMailboxURLs:(id)arg1;	// IMP=0x000000000009f5a1

@end

