//
//     Generated by class-dump 3.5b1 (64 bit) (Debug version compiled Dec  3 2019 19:59:57).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface MFEWSActivityFactory : NSObject
{
}

+ (id)newRetrievePersistedFolderDataTaskWithMailboxDataCache:(id)arg1 accountName:(id)arg2;	// IMP=0x0000000000064c9a
+ (id)newFolderHierarchyReconcileTaskWithInitialSyncState:(id)arg1 accountName:(id)arg2;	// IMP=0x0000000000064c2e
+ (id)newMailboxSyncTaskForMailbox:(id)arg1;	// IMP=0x0000000000064be5
+ (id)newVisibleBodyFetchTaskWithAccountName:(id)arg1;	// IMP=0x0000000000064b9c
+ (id)newBackgroundBodyFetchTaskWithAccountName:(id)arg1;	// IMP=0x0000000000064b53

@end

