//
//     Generated by class-dump 3.5b1 (64 bit) (Debug version compiled Dec  3 2019 19:59:57).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <MailFW/MFEWSRequestOperation.h>

@class MFEWSSyncFolderHierarchyResponseOperation, NSString;

@interface MFEWSSyncFolderHierarchyRequestOperation : MFEWSRequestOperation
{
    NSString *_syncState;	// 8 = 0x8
}

@property(readonly, copy, nonatomic) NSString *syncState; // @synthesize syncState=_syncState;
// - (void).cxx_destruct;	// IMP=0x00000000000a4855
- (id)newResponseOperationWithGateway:(id)arg1 errorHandler:(id)arg2;	// IMP=0x00000000000a47d6
@property(retain, nonatomic) MFEWSSyncFolderHierarchyResponseOperation *responseOperation;
- (id)prepareRequest;	// IMP=0x00000000000a44ca
- (id)activityString;	// IMP=0x00000000000a445d
- (id)initWithGateway:(id)arg1 errorHandler:(id)arg2;	// IMP=0x00000000000a438e
- (id)initWithSyncState:(id)arg1 createBlock:(id)arg2 updateBlock:(id)arg3 deleteBlock:(id)arg4 gateway:(id)arg5;	// IMP=0x00000000000a4271

@end

