//
//     Generated by class-dump 3.5b1 (64 bit) (Debug version compiled Dec  3 2019 19:59:57).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <MailFW/MFEWSRequestOperation.h>

#import <MailFW/NSSecureCoding-Protocol.h>

@class MFEWSGetFolderResponseOperation, NSArray, NSString;

@interface MFEWSMoveFolderRequestOperation : MFEWSRequestOperation <NSSecureCoding>
{
    NSString *_destinationEWSFolderIdString;	// 8 = 0x8
    NSArray *_originEWSFolderIdStrings;	// 16 = 0x10
    MFEWSGetFolderResponseOperation *_changeKeysResponse;	// 24 = 0x18
}

+ (BOOL)supportsSecureCoding;	// IMP=0x0000000000096df7
@property(readonly, nonatomic) MFEWSGetFolderResponseOperation *changeKeysResponse; // @synthesize changeKeysResponse=_changeKeysResponse;
@property(readonly, copy, nonatomic) NSArray *originEWSFolderIdStrings; // @synthesize originEWSFolderIdStrings=_originEWSFolderIdStrings;
@property(readonly, copy, nonatomic) NSString *destinationEWSFolderIdString; // @synthesize destinationEWSFolderIdString=_destinationEWSFolderIdString;
// - (void).cxx_destruct;	// IMP=0x000000000009747f
- (void)setupOfflineResponse;	// IMP=0x00000000000973d7
- (id)prepareRequest;	// IMP=0x0000000000096f48
- (BOOL)isFolderRequest;	// IMP=0x0000000000096f3d
- (id)activityString;	// IMP=0x0000000000096ed1
- (id)initWithGateway:(id)arg1 errorHandler:(id)arg2;	// IMP=0x0000000000096e02
- (void)encodeWithCoder:(id)arg1;	// IMP=0x0000000000096d40
- (id)initWithCoder:(id)arg1;	// IMP=0x0000000000096a2e
- (void)_ewsMoveFolderRequestCommonInitWithEWSFolderIdString:(id)arg1 originEWSFolderIdStrings:(id)arg2 gateway:(id)arg3;	// IMP=0x0000000000096709
- (id)initWithEWSFolderIdString:(id)arg1 originEWSFolderIdStrings:(id)arg2 gateway:(id)arg3;	// IMP=0x00000000000964d0

@end

