//
//     Generated by class-dump 3.5b1 (64 bit) (Debug version compiled Dec  3 2019 19:59:57).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <MailFW/MFEWSRequestOperation.h>

#import <MailFW/NSSecureCoding-Protocol.h>

@class MFEWSGetItemsResponseOperation, MFEWSSuppressReadReceiptsRequestOperation, NSArray, NSDictionary;

@interface MFEWSUpdateItemRequestOperation : MFEWSRequestOperation <NSSecureCoding>
{
    BOOL _messageType;	// 8 = 0x8
    NSArray *_EWSItemIds;	// 16 = 0x10
    NSDictionary *_flags;	// 24 = 0x18
    MFEWSGetItemsResponseOperation *_getItemsResponse;	// 32 = 0x20
    MFEWSSuppressReadReceiptsRequestOperation *_suppressReadReceiptsRequest;	// 40 = 0x28
}

+ (BOOL)supportsSecureCoding;	// IMP=0x00000000000a9547
@property(readonly, nonatomic) MFEWSSuppressReadReceiptsRequestOperation *suppressReadReceiptsRequest; // @synthesize suppressReadReceiptsRequest=_suppressReadReceiptsRequest;
@property(readonly, nonatomic) MFEWSGetItemsResponseOperation *getItemsResponse; // @synthesize getItemsResponse=_getItemsResponse;
@property(readonly, nonatomic) BOOL messageType; // @synthesize messageType=_messageType;
@property(readonly, copy, nonatomic) NSDictionary *flags; // @synthesize flags=_flags;
@property(readonly, copy, nonatomic) NSArray *EWSItemIds; // @synthesize EWSItemIds=_EWSItemIds;
// - (void).cxx_destruct;	// IMP=0x00000000000aa379
@property(readonly, copy, nonatomic) NSArray *itemsPriorToUpdate;
- (id)prepareRequest;	// IMP=0x00000000000a9bc0
- (id)activityString;	// IMP=0x00000000000a9b53
- (void)setupOfflineResponse;	// IMP=0x00000000000a9ae2
- (id)description;	// IMP=0x00000000000a9a22
- (void)_ewsUpdateItemRequestOperationCommonInitWithEWSItemIds:(id)arg1 messageType:(BOOL)arg2 flags:(id)arg3 errorHandler:(id)arg4;	// IMP=0x00000000000a9621
- (id)initWithGateway:(id)arg1 errorHandler:(id)arg2;	// IMP=0x00000000000a9552
- (void)encodeWithCoder:(id)arg1;	// IMP=0x00000000000a9443
- (id)initWithCoder:(id)arg1;	// IMP=0x00000000000a91db
- (id)initWithEWSItemIds:(id)arg1 messageType:(BOOL)arg2 flags:(id)arg3 gateway:(id)arg4 errorHandler:(id)arg5;	// IMP=0x00000000000a90ba

@end

