//
//     Generated by class-dump 3.5b1 (64 bit) (Debug version compiled Dec  3 2019 19:59:57).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <MailFW/MFEWSResponseOperation.h>

@class EWSSetUserOofSettingsResponseType;

@interface MFEWSSetUserOofSettingsResponseOperation : MFEWSResponseOperation
{
}

- (void)executeOperation;	// IMP=0x00000000000a1086
- (void)prepareToExecuteWithResponse:(id)arg1 forRequestOperation:(id)arg2;	// IMP=0x00000000000a0e60
@property(retain) EWSSetUserOofSettingsResponseType *response;

@end

