//
//     Generated by class-dump 3.5b1 (64 bit) (Debug version compiled Dec  3 2019 19:59:57).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <MailFW/MFEWSResponseOperation.h>

@class EWSGetItemResponseType, NSArray;

@interface MFEWSGetItemDataResponseOperation : MFEWSResponseOperation
{
    CDUnknownBlockType _dataHandler;	// 8 = 0x8
    NSArray *_itemIdTypes;	// 16 = 0x10
}

@property(retain, nonatomic) NSArray *itemIdTypes; // @synthesize itemIdTypes=_itemIdTypes;
@property(copy, nonatomic) CDUnknownBlockType dataHandler; // @synthesize dataHandler=_dataHandler;
// - (void).cxx_destruct;	// IMP=0x0000000000087f2f
- (void)executeOperation;	// IMP=0x000000000008774d
- (void)prepareToExecuteWithResponse:(id)arg1 forRequestOperation:(id)arg2;	// IMP=0x00000000000874f0
@property(retain) EWSGetItemResponseType *response;

@end

