//
//     Generated by class-dump 3.5b1 (64 bit) (Debug version compiled Dec  3 2019 19:59:57).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <MailFW/MFDeliveryAccount.h>

@class MFEWSAccount;

@interface MFEWSDeliveryAccount : MFDeliveryAccount
{
    MFEWSAccount *_ewsAccount;	// 8 = 0x8
    BOOL _stripsFromHeaderWhenSending;	// 16 = 0x10
}

+ (id)keyPathsForValuesAffectingValueForKey:(id)arg1;	// IMP=0x0000000000076e5f
@property BOOL stripsFromHeaderWhenSending; // @synthesize stripsFromHeaderWhenSending=_stripsFromHeaderWhenSending;
// - (void).cxx_destruct;	// IMP=0x0000000000078774
- (id)remoteMailAccountsEmployedBy;	// IMP=0x0000000000078686
- (void)setShouldUseAuthentication:(BOOL)arg1;	// IMP=0x0000000000078680
- (BOOL)shouldUseAuthentication;	// IMP=0x0000000000078675
@property __weak MFEWSAccount *associatedAccount;
- (BOOL)isDynamic;	// IMP=0x00000000000784d5
- (id)newDelivererWithMessage:(id)arg1;	// IMP=0x000000000007848c
- (id)deliveryIdentifier;	// IMP=0x0000000000078412
- (void)setValidationRequired:(BOOL)arg1;	// IMP=0x000000000007840c
- (BOOL)validationRequired;	// IMP=0x0000000000078404
- (BOOL)connectAndAuthenticate:(id)arg1;	// IMP=0x000000000007838c
- (id)authenticatedConnection;	// IMP=0x000000000007833c
- (id)newConnectedConnectionDiscoveringBestSettings:(BOOL)arg1 withConnectTimeout:(double)arg2 readWriteTimeout:(double)arg3;	// IMP=0x00000000000782d2
- (void)validateConnections;	// IMP=0x0000000000078295
- (id)accountTypeString;	// IMP=0x0000000000078245
- (BOOL)canGoOffline;	// IMP=0x0000000000078200
- (void)setIsWillingToGoOnline:(BOOL)arg1;	// IMP=0x00000000000781b4
- (BOOL)isWillingToGoOnline;	// IMP=0x000000000007816f
- (void)setIsOffline:(BOOL)arg1;	// IMP=0x0000000000078123
- (BOOL)isOffline;	// IMP=0x00000000000780de
- (long long)defaultSecurePortNumber;	// IMP=0x000000000007809a
- (long long)defaultPortNumber;	// IMP=0x0000000000078056
- (id)standardSSLPorts;	// IMP=0x0000000000078006
- (id)standardPorts;	// IMP=0x0000000000077fb6
- (BOOL)requiresAuthentication;	// IMP=0x0000000000077f71
- (id)saslProfileName;	// IMP=0x0000000000077f21
- (id)identifier;	// IMP=0x0000000000077ed1
- (void)setPreferredAuthScheme:(id)arg1;	// IMP=0x0000000000077e5f
- (id)preferredAuthScheme;	// IMP=0x0000000000077e0f
- (void)setAuthenticationScheme:(id)arg1;	// IMP=0x0000000000077d9d
- (id)authenticationScheme;	// IMP=0x0000000000077d4d
- (void)_setSecurityLayerType:(long long)arg1 releasingConnections:(BOOL)arg2;	// IMP=0x0000000000077ccc
- (long long)securityLayerType;	// IMP=0x0000000000077c88
- (void)setHostname:(id)arg1;	// IMP=0x0000000000077c16
- (id)hostname;	// IMP=0x0000000000077bc6
- (void)_setUsesSSL:(BOOL)arg1 releasingConnections:(BOOL)arg2;	// IMP=0x0000000000077b75
- (BOOL)usesSSL;	// IMP=0x0000000000077b30
- (void)_setPortNumber:(long long)arg1 releasingConnections:(BOOL)arg2;	// IMP=0x0000000000077aaf
- (void)setPortNumber:(long long)arg1;	// IMP=0x0000000000077a63
- (long long)portNumber;	// IMP=0x0000000000077a1f
- (id)appleAuthenticationToken;	// IMP=0x00000000000779cf
- (id)applePersonID;	// IMP=0x000000000007797f
- (void)setTLSIdentity:(struct __SecIdentity *)arg1;	// IMP=0x0000000000077933
- (struct __SecIdentity *)copyTLSIdentity;	// IMP=0x00000000000778ef
- (void)setPassword:(id)arg1;	// IMP=0x000000000007787d
- (id)password;	// IMP=0x000000000007782d
- (void)setUsername:(id)arg1;	// IMP=0x00000000000777bb
- (id)username;	// IMP=0x000000000007776b
- (BOOL)discoverConnectionPropertiesAndWait;	// IMP=0x0000000000077726
- (void)discoverConnectionProperties;	// IMP=0x00000000000776e9
- (void)setCanonicalEmailAddress:(id)arg1;	// IMP=0x0000000000077677
- (id)canonicalEmailAddress;	// IMP=0x0000000000077627
- (void)releaseAllConnections;	// IMP=0x0000000000077621
- (id)offlineDisplayName;	// IMP=0x0000000000077534
- (void)setDisplayName;	// IMP=0x000000000007752e
- (id)displayName;	// IMP=0x0000000000077441
- (void)setStoredDisplayName;	// IMP=0x000000000007743b
- (id)storedDisplayName;	// IMP=0x000000000007734e
- (void)dealloc;	// IMP=0x0000000000077306
- (id)initWithAccountInfo:(id)arg1;	// IMP=0x0000000000077237
- (id)initWithSystemAccount:(id)arg1;	// IMP=0x0000000000077168
- (id)initWithAccount:(id)arg1;	// IMP=0x00000000000770e8

@end

