//
//     Generated by class-dump 3.5b1 (64 bit) (Debug version compiled Dec  3 2019 19:59:57).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <MailFW/MFRemoteStoreSizeEngine.h>

@class MFIMAPAccount, NSArray, NSMutableDictionary, NSMutableSet;

@interface MFIMAPSizeEngine : MFRemoteStoreSizeEngine
{
    unsigned long long _workerThreadCount;	// 8 = 0x8
    NSMutableDictionary *_mailboxesByQuotaRoot;	// 16 = 0x10
    NSMutableSet *_quotasToFetch;	// 24 = 0x18
    NSMutableSet *_observedIMAPMailboxes;	// 32 = 0x20
    NSMutableSet *_observedIMAPQuotaRoots;	// 40 = 0x28
    long long _quotaStatus;	// 48 = 0x30
}

@property(nonatomic) long long quotaStatus; // @synthesize quotaStatus=_quotaStatus;
// - (void).cxx_destruct;	// IMP=0x00000000000cca24
- (BOOL)mailbox:(id)arg1 usesQuotaName:(id)arg2;	// IMP=0x00000000000cc910
- (id)copyMailboxesForQuotaName:(id)arg1;	// IMP=0x00000000000cc81d
- (id)usageForQuotaName:(id)arg1;	// IMP=0x00000000000cc710
@property(readonly, copy) NSArray *quotaNames;
- (BOOL)shouldStartWorkerThread;	// IMP=0x00000000000cc611
- (void)_runWorkerThread;	// IMP=0x00000000000cb88a
- (void)_getSizeForMailbox:(id)arg1;	// IMP=0x00000000000cb617
- (void)_mailboxBecameInvalid:(id)arg1;	// IMP=0x00000000000cb37f
- (void)_changeQuotaRoots:(id)arg1 forMailbox:(id)arg2;	// IMP=0x00000000000cae96
- (BOOL)_changeUsageInfo:(CDStruct_1dee9796 *)arg1 forMailbox:(id)arg2 refetchQuotas:(BOOL)arg3;	// IMP=0x00000000000cab86
- (void)_addQuotaRootsFromMailbox:(id)arg1;	// IMP=0x00000000000ca712
- (void)_addUsageInfoFromMailbox:(id)arg1;	// IMP=0x00000000000ca621
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;	// IMP=0x00000000000ca442
- (void)dealloc;	// IMP=0x00000000000ca39a
- (id)initWithAccount:(id)arg1;	// IMP=0x00000000000ca1af

// Remaining properties
@property(readonly, nonatomic) MFIMAPAccount *account; // @dynamic account;

@end

