//
//     Generated by class-dump 3.5b1 (64 bit) (Debug version compiled Dec  3 2019 19:59:57).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <MailFW/MFIMAPOperation.h>

@interface MFIMAPCreateOperation : MFIMAPOperation
{
}

- (id)description;	// IMP=0x00000000000d53f1
- (unsigned char)operationType;	// IMP=0x00000000000d53e6
- (id)initWithMailboxToCreate:(id)arg1;	// IMP=0x00000000000d53d4

@end

