//
//     Generated by class-dump 3.5b1 (64 bit) (Debug version compiled Dec  3 2019 19:59:57).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <MailFW/MFRemoteStoreAccount.h>

#import <MailFW/IMAPAccount-Protocol.h>

@class ACAccount, ECAuthScheme, ECIMAPAccount, IMAPTaskManager, MFLibraryIMAPStore, MFMailbox, NSArray, NSDate, NSDictionary, NSError, NSLock, NSMutableDictionary, NSMutableSet, NSOperationQueue, NSString;

@interface MFIMAPAccount : MFRemoteStoreAccount <IMAPAccount>
{
    NSArray *_lastKnownCapabilities;	// 8 = 0x8
    NSMutableSet *_namespacePrivatePrefixes;	// 16 = 0x10
    NSMutableSet *_namespacePublicPrefixes;	// 24 = 0x18
    NSMutableSet *_namespaceSharedPrefixes;	// 32 = 0x20
    NSString *_separatorChar;	// 40 = 0x28
    NSString *_serverPathPrefixWithFilesystemSeparator;	// 48 = 0x30
    NSString *_serverPathPrefixAsFilesystemPath;	// 56 = 0x38
    NSLock *_fsPrefixLock;	// 64 = 0x40
    NSLock *_mailboxListingLock;	// 72 = 0x48
    NSMutableSet *_mailboxURLsToSynchronize;	// 80 = 0x50
    NSMutableDictionary *_IMAPMailboxes;	// 88 = 0x58
    NSMutableDictionary *_IMAPQuotaRoots;	// 96 = 0x60
    id _allMailLock;	// 104 = 0x68
    MFMailbox *_allMailMailbox;	// 112 = 0x70
    MFMailbox *_serverDefinedArchiveMailbox;	// 120 = 0x78
    id _serverDefinedArchiveMailboxLock;	// 128 = 0x80
    MFMailbox *_serverDefinedDraftsMailbox;	// 136 = 0x88
    id _serverDefinedDraftsMailboxLock;	// 144 = 0x90
    MFMailbox *_serverDefinedJunkMailbox;	// 152 = 0x98
    id _serverDefinedJunkMailboxLock;	// 160 = 0xa0
    MFMailbox *_serverDefinedSentMailbox;	// 168 = 0xa8
    id _serverDefinedSentMailboxLock;	// 176 = 0xb0
    MFMailbox *_serverDefinedTrashMailbox;	// 184 = 0xb8
    id _serverDefinedTrashMailboxLock;	// 192 = 0xc0
    id _propertyDiscoveryLock;	// 200 = 0xc8
    BOOL _currentlySynchronizingMailboxList;	// 208 = 0xd0
    id _synchronizeMailboxListingLock;	// 216 = 0xd8
    NSMutableSet *_labelsBeingCleanedUp;	// 224 = 0xe0
    BOOL _supportsQuickResynchronization;	// 232 = 0xe8
    BOOL _lastConnectionFailed;	// 233 = 0xe9
    BOOL _shouldIncludePrefixInPath;	// 234 = 0xea
    NSOperationQueue *_remoteTaskQueue;	// 240 = 0xf0
    NSOperationQueue *_remoteFetchQueue;	// 248 = 0xf8
    NSDictionary *_serverID;	// 256 = 0x100
    MFLibraryIMAPStore *_idleStore;	// 264 = 0x108
    double _lastMailboxListFetchTime;	// 272 = 0x110
}

+ (id)_mailboxNameForPathComponent:(id)arg1;	// IMP=0x00000000000c3608
+ (id)_pathComponentForMailboxName:(id)arg1;	// IMP=0x00000000000c3497
+ (void)_deleteQueuedMailboxes:(id)arg1;	// IMP=0x00000000000c1d7a
+ (id)csAccountTypeString;	// IMP=0x00000000000b6494
+ (id)accountTypeString;	// IMP=0x00000000000b6480
+ (id)standardSSLPorts;	// IMP=0x00000000000b5756
+ (id)standardPorts;	// IMP=0x00000000000b573d
+ (id)backgroundQueue;	// IMP=0x00000000000b3792
+ (id)invocationQueue;	// IMP=0x00000000000b3728
@property(nonatomic) BOOL shouldIncludePrefixInPath; // @synthesize shouldIncludePrefixInPath=_shouldIncludePrefixInPath;
@property(nonatomic) BOOL lastConnectionFailed; // @synthesize lastConnectionFailed=_lastConnectionFailed;
@property double lastMailboxListFetchTime; // @synthesize lastMailboxListFetchTime=_lastMailboxListFetchTime;
@property(retain) MFLibraryIMAPStore *idleStore; // @synthesize idleStore=_idleStore;
@property BOOL supportsQuickResynchronization; // @synthesize supportsQuickResynchronization=_supportsQuickResynchronization;
@property(copy) NSDictionary *serverID; // @synthesize serverID=_serverID;
@property(readonly, nonatomic) NSOperationQueue *remoteFetchQueue; // @synthesize remoteFetchQueue=_remoteFetchQueue;
@property(readonly, nonatomic) NSOperationQueue *remoteTaskQueue; // @synthesize remoteTaskQueue=_remoteTaskQueue;
// - (void).cxx_destruct;	// IMP=0x00000000000c62db
- (void)_performDiagnostics:(id)arg1;	// IMP=0x00000000000c5ef2
- (void)messageDeliveryWillBegin:(id)arg1;	// IMP=0x00000000000c5e93
- (BOOL)storesUnseenCount;	// IMP=0x00000000000c5e88
- (id)_infoForMatchingURL:(id)arg1;	// IMP=0x00000000000c5cdf
- (id)URLPersistenceScheme;	// IMP=0x00000000000c5ccb
- (id)mailboxForRelativePath:(id)arg1 isFilesystemPath:(BOOL)arg2 create:(BOOL)arg3;	// IMP=0x00000000000c5acb
- (void)_loadEntriesFromFileSystemPath:(id)arg1 parent:(id)arg2;	// IMP=0x00000000000c58d8
- (id)_mailboxPathPrefix:(BOOL)arg1;	// IMP=0x00000000000c5870
- (void)syncFileSystemWithServerPathPrefix;	// IMP=0x00000000000c4c62
- (void)_setFileSystemServerPathPrefix;	// IMP=0x00000000000c45d1
- (id)_fileSystemServerPathPrefix:(BOOL)arg1;	// IMP=0x00000000000c455d
@property(copy) NSString *serverPathPrefix;
- (BOOL)canMailboxBeDeleted:(id)arg1;	// IMP=0x00000000000c41b8
- (id)mailboxForName:(id)arg1;	// IMP=0x00000000000c3f08
- (id)nameForMailbox:(id)arg1;	// IMP=0x00000000000c3ba9
- (id)_fullIMAPPathForPath:(id)arg1 relativeToMailbox:(id)arg2;	// IMP=0x00000000000c3880
- (void)insertInMailboxes:(id)arg1 atIndex:(unsigned long long)arg2;	// IMP=0x00000000000c2c88
- (BOOL)renameMailbox:(id)arg1 newDisplayName:(id)arg2 parent:(id)arg3;	// IMP=0x00000000000c2529
- (void)_recursivelyModifySubscriptions:(BOOL)arg1 forMailbox:(id)arg2 children:(id)arg3 withSyncHandler:(id)arg4;	// IMP=0x00000000000c21f4
- (void)_mailboxesWereRemovedFromTree:(id)arg1 withFileSystemPaths:(id)arg2;	// IMP=0x00000000000c1af5
- (void)_waitForMailboxListingLoadToComplete;	// IMP=0x00000000000c1ab2
- (void)_loadMailboxListingIntoCache:(id)arg1 parent:(id)arg2 addedMailboxes:(id)arg3 removedMailboxes:(id)arg4 updatingSourceMailbox:(BOOL)arg5;	// IMP=0x00000000000c1479
- (void)_loadMailboxListingIntoCache:(id)arg1 parent:(id)arg2 addedMailboxes:(id)arg3 removedMailboxes:(id)arg4;	// IMP=0x00000000000c13ea
- (void)refreshMailboxListingRootedAtMailbox:(id)arg1;	// IMP=0x00000000000c127b
- (void)_synchronouslyLoadListingForParent:(id)arg1;	// IMP=0x00000000000c11fb
- (id)_copyMailboxWithParent:(id)arg1 name:(id)arg2 pathComponent:(id)arg3 attributes:(unsigned long long)arg4 existingMailbox:(id)arg5;	// IMP=0x00000000000c0ed8
- (id)_specialMailboxWithType:(int)arg1 create:(BOOL)arg2 isLocal:(BOOL)arg3;	// IMP=0x00000000000c0588
- (BOOL)_deleteMailbox:(id)arg1 reflectToServer:(BOOL)arg2;	// IMP=0x00000000000c014e
- (BOOL)deleteMailbox:(id)arg1 reflectToServer:(BOOL)arg2;	// IMP=0x00000000000c0062
- (BOOL)_askToChangePathPrefixToCreateMailbox:(id)arg1 displayName:(id)arg2 withSyncHandler:(id)arg3;	// IMP=0x00000000000bf96c
- (id)validNameForMailbox:(id)arg1 fromDisplayName:(id)arg2 error:(id *)arg3;	// IMP=0x00000000000bf38c
- (id)createMailboxWithParent:(id)arg1 displayName:(id)arg2 localizedDisplayName:(id)arg3;	// IMP=0x00000000000be975
- (BOOL)_createMailbox:(id)arg1 withSyncHandler:(id)arg2;	// IMP=0x00000000000be841
- (id)_listingForMailbox:(id)arg1 listAllChildren:(BOOL)arg2;	// IMP=0x00000000000be0b9
- (id)_recursivelyFilterMailboxList:(id)arg1 accordingToList:(id)arg2;	// IMP=0x00000000000bdc58
- (id)_namespacePrefixesForPrivate:(BOOL)arg1 public:(BOOL)arg2 shared:(BOOL)arg3;	// IMP=0x00000000000bd4c8
- (id)_listingForMailbox:(id)arg1 listAllChildren:(BOOL)arg2 onlySubscribed:(BOOL)arg3;	// IMP=0x00000000000bce50
- (void)_synchronizeMailboxListDuringMailCheck;	// IMP=0x00000000000bccd1
- (void)_updateSpecialMailboxes;	// IMP=0x00000000000bc233
- (BOOL)_synchronizeMailboxList;	// IMP=0x00000000000bc036
@property(readonly, nonatomic) BOOL supportsMove;
@property(readonly) BOOL supportsIDLE;
@property(readonly, copy) NSArray *lastKnownCapabilities;
- (id)separatorCharFetchIfNeeded:(BOOL)arg1;	// IMP=0x00000000000bbcb4
- (void)unselectConnectionForMailbox:(id)arg1;	// IMP=0x00000000000bbc42
- (id)storeForMailbox:(id)arg1;	// IMP=0x00000000000bbb11
- (void)doCommandBlockForMailbox:(id)arg1 synchronously:(BOOL)arg2 priority:(long long)arg3 description:(id)arg4 block:(id)arg5;	// IMP=0x00000000000bba26
- (void)stopAccountActivity;	// IMP=0x00000000000bb9e9
- (void)fetchAsynchronouslyIsAuto:(BOOL)arg1;	// IMP=0x00000000000bb636
- (BOOL)shouldFetch;	// IMP=0x00000000000bb5ff
- (void)setIsOffline:(BOOL)arg1;	// IMP=0x00000000000bb49e
- (void)clearQuotaRoots;	// IMP=0x00000000000bb264
- (id)quotaRootForName:(id)arg1 createIfNeeded:(BOOL)arg2;	// IMP=0x00000000000bb175
- (void)_startObserving:(BOOL)arg1 IMAPMailbox:(id)arg2;	// IMP=0x00000000000bb0ad
- (void)_removeIMAPMailboxWithName:(id)arg1;	// IMP=0x00000000000bafe2
- (void)_renameIMAPMailboxWithMailbox:(id)arg1 fromName:(id)arg2 toName:(id)arg3;	// IMP=0x00000000000bab24
- (BOOL)resetSpecialMailboxes;	// IMP=0x00000000000ba979
- (id)_serverDefinedMailboxWithAttribute:(unsigned long long)arg1;	// IMP=0x00000000000ba7d1
@property(readonly) MFMailbox *serverDefinedTrashMailbox;
@property(readonly) MFMailbox *serverDefinedSentMailbox;
@property(readonly) MFMailbox *serverDefinedJunkMailbox;
@property(readonly) MFMailbox *serverDefinedDraftsMailbox;
@property(readonly) MFMailbox *serverDefinedArchiveMailbox;
- (id)_mailboxNameForLabelName:(id)arg1;	// IMP=0x00000000000ba27a
- (id)gmailLabelWithName:(id)arg1;	// IMP=0x00000000000b9ea0
- (id)_addIMAPMailboxForMailbox:(id)arg1 name:(id)arg2;	// IMP=0x00000000000b9a93
- (id)IMAPMailboxForMailbox:(id)arg1 name:(id)arg2 createIfNeeded:(BOOL)arg3;	// IMP=0x00000000000b97fc
- (id)IMAPMailboxForMailboxName:(id)arg1 createIfNeeded:(BOOL)arg2;	// IMP=0x00000000000b97e2
- (id)IMAPMailboxForMailbox:(id)arg1 createIfNeeded:(BOOL)arg2;	// IMP=0x00000000000b9737
- (void)_allegedHighestModificationSequenceDidChangeForIMAPMailbox:(id)arg1;	// IMP=0x00000000000b965d
- (void)_unseenCount:(unsigned int)arg1 didChangeForIMAPMailbox:(id)arg2;	// IMP=0x00000000000b9549
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;	// IMP=0x00000000000b93c2
- (void)validateConnections;	// IMP=0x00000000000b925a
- (void)_validateConnections;	// IMP=0x00000000000b919b
- (void)releaseAllConnections;	// IMP=0x00000000000b917f
- (void)_releaseAllConnectionsAndCallSuper:(BOOL)arg1 saveOfflineCache:(BOOL)arg2;	// IMP=0x00000000000b8f97
- (void)didConnectToServerWithServerInterface:(id)arg1;	// IMP=0x00000000000b8d10
- (void)setSeparatorChar:(id)arg1;	// IMP=0x00000000000b8bb7
- (void)expungeMailboxWithName:(id)arg1 URLStringToCompact:(id)arg2 ifSelected:(BOOL)arg3;	// IMP=0x00000000000b8a17
- (void)invalidateMailboxWithName:(id)arg1 expunge:(BOOL)arg2 URLStringToCompact:(id)arg3;	// IMP=0x00000000000b8876
- (void)handleOpenMailboxError:(id)arg1;	// IMP=0x00000000000b8870
- (BOOL)connectAndAuthenticate:(id)arg1;	// IMP=0x00000000000b7b09
- (void)detectAllMailMailboxWithConnection:(id)arg1;	// IMP=0x00000000000b77a7
@property(readonly, copy, nonatomic) NSArray *allBackgroundMailboxNames;
- (void)setStoreTrashOnServer:(BOOL)arg1;	// IMP=0x00000000000b7485
- (void)setStoreSentMessagesOnServer:(BOOL)arg1;	// IMP=0x00000000000b7432
- (void)setStoreJunkOnServer:(BOOL)arg1;	// IMP=0x00000000000b73df
- (void)setStoreDraftsOnServer:(BOOL)arg1;	// IMP=0x00000000000b738c
@property BOOL ignoreServerDefinedTrashMailbox;
@property BOOL ignoreServerDefinedSentMailbox;
@property BOOL ignoreServerDefinedJunkMailbox;
@property BOOL ignoreServerDefinedDraftsMailbox;
@property BOOL ignoreServerDefinedArchiveMailbox;
@property BOOL hasServerDefinedTrashMailbox;
@property BOOL hasServerDefinedSentMailbox;
@property BOOL hasServerDefinedJunkMailbox;
@property BOOL hasServerDefinedDraftsMailbox;
@property BOOL hasServerDefinedArchiveMailbox;
@property BOOL hasServerDefinedAllMailMailbox;
- (void)_clearAllPathBasedCachesAndDelete:(BOOL)arg1;	// IMP=0x00000000000b6bdf
@property(readonly) BOOL allowsPartialDownloads;
- (void)didSynchronizeMailboxCachesAndFoundChanges:(BOOL)arg1;	// IMP=0x00000000000b6a72
- (void)resetNeedToSynchronizeMailboxCaches;	// IMP=0x00000000000b6a35
- (BOOL)needToSynchronizeMailboxCaches;	// IMP=0x00000000000b6894
- (void)handleAlertResponse:(id)arg1;	// IMP=0x00000000000b6595
- (BOOL)handleResponseCodeFromResponse:(id)arg1;	// IMP=0x00000000000b64a8
- (void)_updateIdleMailbox;	// IMP=0x00000000000b630a
- (id)allMailMailbox;	// IMP=0x00000000000b6013
- (id)primaryMailbox;	// IMP=0x00000000000b5e85
- (BOOL)_setChildren:(id)arg1 forMailbox:(id)arg2;	// IMP=0x00000000000b5de3
@property BOOL compactWhenClosingMailboxes;
- (id)authenticatedConnection;	// IMP=0x00000000000b5c0b
- (id)newConnectedConnectionDiscoveringBestSettings:(BOOL)arg1 withConnectTimeout:(double)arg2 readWriteTimeout:(double)arg3;	// IMP=0x00000000000b5b65
@property(readonly, nonatomic) BOOL requiresAuthentication;
@property(readonly, copy, nonatomic) NSString *saslProfileName;
- (BOOL)_parentSystemAccountDidUpdateProperties:(id)arg1 changedSystemAccount:(char *)arg2;	// IMP=0x00000000000b576f
- (id)mailboxPathExtension;	// IMP=0x00000000000b56ce
- (Class)storeClassForMailbox:(id)arg1;	// IMP=0x00000000000b5608
- (long long)defaultSecurePortNumber;	// IMP=0x00000000000b55fd
- (long long)defaultPortNumber;	// IMP=0x00000000000b55f2
- (id)messageActionsAfterActionID:(long long)arg1;	// IMP=0x00000000000b551e
- (BOOL)discoverSettings;	// IMP=0x00000000000b53c9
- (BOOL)needsToDiscoverSettings;	// IMP=0x00000000000b5348
- (void)setSupportsModificationSequences:(BOOL)arg1 forMailboxName:(id)arg2;	// IMP=0x00000000000b52f4
- (id)dataSourceForMailboxURL:(id)arg1 createIfNeeded:(BOOL)arg2;	// IMP=0x00000000000b5253
- (id)dataSourceForMailbox:(id)arg1 createIfNeeded:(BOOL)arg2;	// IMP=0x00000000000b50e2
- (id)dataSourceForMailboxName:(id)arg1 createIfNeeded:(BOOL)arg2;	// IMP=0x00000000000b507e
- (void)doRoutineCleanup;	// IMP=0x00000000000b4e35
- (void)_writeCustomInfoToMailboxCache:(id)arg1;	// IMP=0x00000000000b4d5a
- (void)_readCustomInfoFromMailboxCache:(id)arg1;	// IMP=0x00000000000b4bf6
- (BOOL)_cleanUpMessagesInGmailLabel:(id)arg1;	// IMP=0x00000000000b46d7
- (void)cleanUpMessagesInGmailLabel:(id)arg1;	// IMP=0x00000000000b45fc
- (void)_cleanUpMessagesInGmailLabels;	// IMP=0x00000000000b4409
- (id)_colorByMessageFromColorByMessageDigest:(id)arg1;	// IMP=0x00000000000b4058
- (void)_migrateColorsForGmail;	// IMP=0x00000000000b3b46
@property BOOL needsGmailLabelsCleanup;
@property(readonly) BOOL shouldUseGmailLabelStoresIsSet;
@property BOOL shouldUseGmailLabelStores;
- (BOOL)needsServerMessages;	// IMP=0x00000000000b397a
- (void)completeDeferredInitialization;	// IMP=0x00000000000b383e
- (void)dealloc;	// IMP=0x00000000000b358a
- (id)_newTaskManager;	// IMP=0x00000000000b355c
- (id)init;	// IMP=0x00000000000b34ce
- (id)initWithSystemAccount:(id)arg1;	// IMP=0x00000000000b30d0
- (void)setMessageCaching:(unsigned int)arg1;	// IMP=0x00000000000c6523
- (unsigned int)messageCaching;	// IMP=0x00000000000c64f9

// Remaining properties
@property(readonly, copy) NSString *accountTypeString;
@property BOOL allowInsecureAuthentication;
@property(readonly, copy) NSString *appleAuthenticationToken;
@property(readonly, copy) NSString *applePersonID;
@property(copy) NSString *authenticationScheme;
@property(readonly) ECIMAPAccount *baseAccount; // @dynamic baseAccount;
@property long long cachePolicy;
@property(copy) NSString *canonicalEmailAddress;
@property(readonly, copy) NSString *clientInfo;
@property BOOL configureDynamically;
@property(retain) NSError *connectionError;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(copy) NSString *displayName;
@property(readonly, copy) NSArray *emailAddressStrings;
@property(readonly, copy, nonatomic) NSDate *expiryDate;
@property(copy) NSString *externalHostname;
@property(readonly) unsigned long long hash;
@property(readonly, copy) NSString *hostname;
@property(readonly, copy) NSString *identifier;
@property(readonly, nonatomic) BOOL isGmailAccount;
@property(readonly) BOOL isYahooAccount;
@property(readonly, copy) NSString *machineID;
@property(readonly, nonatomic, getter=isManaged) BOOL managed;
@property(readonly, copy) NSString *oauthToken;
@property(readonly, copy) NSString *oneTimePassword;
@property(readonly, copy) NSString *password;
@property long long portNumber;
@property(retain) ECAuthScheme *preferredAuthScheme;
@property(readonly) BOOL primaryiCloudAccount;
@property long long securityLayerType;
@property(readonly) BOOL shouldMoveDeletedMessagesToTrash;
@property BOOL shouldUseAuthentication;
@property(readonly, copy, nonatomic) NSArray *standardPorts;
@property(readonly, copy, nonatomic) NSArray *standardSSLPorts;
@property(readonly, copy, nonatomic) NSString *statisticsKind;
@property(readonly) Class superclass;
@property(readonly, copy) ACAccount *systemAccount;
@property(readonly, nonatomic) IMAPTaskManager *taskManager; // @dynamic taskManager;
@property(readonly, copy) NSString *username;
@property BOOL usesSSL;

@end

