//
//     Generated by class-dump 3.5b1 (64 bit) (Debug version compiled Dec  3 2019 19:59:57).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface MFIMAPOperation : NSObject
{
    BOOL _usesRealUids;	// 8 = 0x8
    NSString *_mailboxName;	// 16 = 0x10
}

+ (id)newOperationWithSerializedData:(id)arg1 cursor:(unsigned long long *)arg2;	// IMP=0x00000000000d4bf9
@property(nonatomic) BOOL usesRealUids; // @synthesize usesRealUids=_usesRealUids;
@property(readonly, copy, nonatomic) NSString *mailboxName; // @synthesize mailboxName=_mailboxName;
// - (void).cxx_destruct;	// IMP=0x00000000000d53c4
@property(readonly, nonatomic) unsigned char operationType;
- (id)init;	// IMP=0x00000000000d52c9
- (id)_initWithMailboxName:(id)arg1;	// IMP=0x00000000000d5183
- (void)serializeIntoData:(id)arg1;	// IMP=0x00000000000d5003
- (void)_deserializeOpSpecificValuesFromData:(id)arg1 cursor:(unsigned long long *)arg2;	// IMP=0x00000000000d4ffd
- (unsigned char)_magic;	// IMP=0x00000000000d4ff5

@end

