//
//     Generated by class-dump 3.5b1 (64 bit) (Debug version compiled Dec  3 2019 19:59:57).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface MFLibraryQueries : NSObject
{
}

+ (int)bindInsertEventStatement:(id)arg1 withEvent:(id)arg2 messageID:(long long)arg3;	// IMP=0x00000000001237a5
+ (id)checkOutStatementToInsertEvent:(id)arg1;	// IMP=0x0000000000123780
+ (id)checkOutStatementForEventWithMessageID:(long long)arg1 connection:(id)arg2;	// IMP=0x000000000012371a
+ (id)fromClauseForTables:(unsigned long long)arg1 startingFromTableExpression:(id)arg2;	// IMP=0x00000000001235d7
+ (id)checkOutStatementToCompletelyUpdateMessage:(id)arg1;	// IMP=0x00000000001235b2
+ (id)checkOutStatementToInsertMessage:(id)arg1;	// IMP=0x000000000012358d

@end

