//
//     Generated by class-dump 3.5b1 (64 bit) (Debug version compiled Dec  3 2019 19:59:57).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class EDPersistenceDatabaseConnection, NSProgress;

@interface MFLibraryUpgradeStep : NSObject
{
    NSProgress *_progress;	// 8 = 0x8
    EDPersistenceDatabaseConnection *_connection;	// 16 = 0x10
}

+ (BOOL)needToPerformFromMinorVersion:(unsigned long long)arg1 initialLastWriteMinorVersion:(unsigned long long)arg2;	// IMP=0x000000000013c3b1
+ (BOOL)recalculateAllConversations;	// IMP=0x000000000013c3a9
@property(readonly, nonatomic) EDPersistenceDatabaseConnection *connection; // @synthesize connection=_connection;
@property(readonly, nonatomic) NSProgress *progress; // @synthesize progress=_progress;
// - (void).cxx_destruct;	// IMP=0x000000000013cc7d
- (id)adjustSmartMailboxCriterion:(id)arg1 adjustmentBlock:(id)arg2;	// IMP=0x000000000013c8db
- (id)_urlStringForMailboxDirectory:(id)arg1 account:(id)arg2 levelFromAccountDirectory:(unsigned long long)arg3;	// IMP=0x000000000013c704
- (id)mailboxFileSystemPathsByDatabaseURLForAccounts:(id)arg1;	// IMP=0x000000000013c3e0
@property(readonly, nonatomic) BOOL shouldRecalculateMessageCounts;
- (void)dealloc;	// IMP=0x000000000013c32c
- (id)init;	// IMP=0x000000000013c25d
- (id)initWithDatabaseConnection:(id)arg1;	// IMP=0x000000000013c11c

@end

