//
//     Generated by class-dump 3.5b1 (64 bit) (Debug version compiled Dec  3 2019 19:59:57).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <MailFW/MFMailAccount.h>

@class MFMailbox;

@interface MFLocalAccount : MFMailAccount
{
}

+ (id)csAccountTypeString;	// IMP=0x000000000013dbe0
+ (id)accountTypeString;	// IMP=0x000000000013db74
+ (id)outboxPathRelativeToLegacyAccountPath:(id)arg1 legacyOutboxPath:(id)arg2;	// IMP=0x000000000013d7a1
+ (id)localAccount;	// IMP=0x000000000013cd5e
+ (id)allocWithZone:(struct _NSZone *)arg1;	// IMP=0x000000000013cca5
- (BOOL)supportsAppleScript;	// IMP=0x000000000013f522
- (BOOL)hasTrashMailbox;	// IMP=0x000000000013f51a
- (BOOL)isRemoteAccount;	// IMP=0x000000000013f512
- (BOOL)isZeroConfiguration;	// IMP=0x000000000013f507
- (BOOL)providesAccountInformation;	// IMP=0x000000000013f4ff
- (BOOL)canParticipateInRules;	// IMP=0x000000000013f4f7
- (BOOL)isEditableByUser;	// IMP=0x000000000013f4ef
- (id)_defaultSpecialMailboxRelativePathForType:(int)arg1;	// IMP=0x000000000013f4a0
- (BOOL)synchronizesDataWithServer;	// IMP=0x000000000013f498
- (id)URLPersistenceScheme;	// IMP=0x000000000013f484
- (id)rootlessMailboxForFileSystemPath:(id)arg1;	// IMP=0x000000000013f21b
- (void)insertInMailboxes:(id)arg1 atIndex:(unsigned long long)arg2;	// IMP=0x000000000013f019
- (BOOL)renameMailbox:(id)arg1 newDisplayName:(id)arg2 parent:(id)arg3;	// IMP=0x000000000013ecc2
- (id)createMailboxWithParent:(id)arg1 displayName:(id)arg2 error:(id *)arg3;	// IMP=0x000000000013e4f6
- (id)createMailboxWithParent:(id)arg1 displayName:(id)arg2 localizedDisplayName:(id)arg3;	// IMP=0x000000000013e485
- (id)pathForMailboxWithParent:(id)arg1 displayName:(id)arg2;	// IMP=0x000000000013e223
- (BOOL)supportsNormalContainerOnlyMailboxes;	// IMP=0x000000000013e1fe
- (BOOL)_setChildren:(id)arg1 forMailbox:(id)arg2;	// IMP=0x000000000013e134
- (id)_copyMailboxWithParent:(id)arg1 name:(id)arg2 pathComponent:(id)arg3 attributes:(unsigned long long)arg4 existingMailbox:(id)arg5 uuid:(id)arg6;	// IMP=0x000000000013df7c
- (void)_synchronouslyLoadListingForParent:(id)arg1;	// IMP=0x000000000013ddbc
- (BOOL)shouldMoveDeletedMessagesToTrash;	// IMP=0x000000000013dd1b
- (long long)emptyTrashFrequency;	// IMP=0x000000000013dd02
- (void)_readCustomInfoFromMailboxCache:(id)arg1;	// IMP=0x000000000013dca5
- (void)setIsWillingToGoOnline:(BOOL)arg1;	// IMP=0x000000000013dc9f
- (BOOL)isWillingToGoOnline;	// IMP=0x000000000013dc94
- (void)setIsOffline:(BOOL)arg1;	// IMP=0x000000000013dc59
- (BOOL)isOffline;	// IMP=0x000000000013dc51
- (BOOL)isLocalAccount;	// IMP=0x000000000013dc46
- (BOOL)shouldAutoFetch;	// IMP=0x000000000013dc3e
- (BOOL)canFetch;	// IMP=0x000000000013dc36
- (void)setPassword:(id)arg1;	// IMP=0x000000000013dc30
- (id)password;	// IMP=0x000000000013dc11
- (void)setUsername:(id)arg1;	// IMP=0x000000000013dc0b
- (void)setHostname:(id)arg1;	// IMP=0x000000000013dc05
- (void)setConfigureDynamically:(BOOL)arg1;	// IMP=0x000000000013dbff
- (BOOL)configureDynamically;	// IMP=0x000000000013dbf4
- (id)primaryMailbox;	// IMP=0x000000000013db60
- (id)mailboxPathExtension;	// IMP=0x000000000013daf1
- (Class)storeClassForMailbox:(id)arg1;	// IMP=0x000000000013dad8
- (id)_outboxMailboxCreateIfNeeded:(BOOL)arg1;	// IMP=0x000000000013d2df
@property(readonly, nonatomic) MFMailbox *outboxMailbox;
- (void)dealloc;	// IMP=0x000000000013d218

@end

