//
//     Generated by class-dump 3.5b1 (64 bit) (Debug version compiled Dec  3 2019 19:59:57).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <MailCore/MCMessage.h>

@interface MFMboxMessage : MCMessage
{
    struct _NSRange _mboxRange;	// 104 = 0x68
}

@property(readonly, nonatomic) struct _NSRange mboxRange; // @synthesize mboxRange=_mboxRange;
- (void)setDataSource:(id)arg1;	// IMP=0x0000000000174a6c
- (id)dataSource;	// IMP=0x0000000000174a3d
- (id)initWithMboxRange:(struct _NSRange)arg1;	// IMP=0x00000000001749ed
- (id)init;	// IMP=0x000000000017491e

@end

