//
//     Generated by class-dump 3.5b1 (64 bit) (Debug version compiled Dec  3 2019 19:59:57).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class MFMailboxProvider;

@interface MFMessageTransformer : NSObject
{
    MFMailboxProvider *_mailboxProvider;	// 8 = 0x8
}

@property(retain, nonatomic) MFMailboxProvider *mailboxProvider; // @synthesize mailboxProvider=_mailboxProvider;
// - (void).cxx_destruct;	// IMP=0x00000000001b5140
- (id)_transformLibraryMessage:(id)arg1 mailboxScope:(id)arg2 mailboxObjectIDs:(id)arg3;	// IMP=0x00000000001b4ab8
- (id)transformECMessages:(id)arg1 mailboxScope:(id)arg2;	// IMP=0x00000000001b44fc
- (id)transformLibraryMessage:(id)arg1 mailboxScope:(id)arg2;	// IMP=0x00000000001b44a1
- (id)initWithMailboxProvider:(id)arg1;	// IMP=0x00000000001b4472

@end

