//
//     Generated by class-dump 3.5b1 (64 bit) (Debug version compiled Dec  3 2019 19:59:57).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <MailFW/MCActivityTarget-Protocol.h>

@class MCMessage, MCMessageHeaders, MFDeliveryAccount, NSString;
@protocol MCMessageDataSource, MFMessageDelivererDelegate;

@interface MFMessageDeliverer : NSObject <MCActivityTarget>
{
    MFDeliveryAccount *_account;	// 8 = 0x8
    id <MCMessageDataSource> _messageStore;	// 16 = 0x10
    BOOL _askForReadReceipt;	// 24 = 0x18
    id <MFMessageDelivererDelegate> _delegate;	// 32 = 0x20
    MCMessage *_message;	// 40 = 0x28
    long long _deliveryStatus;	// 48 = 0x30
}

+ (BOOL)deliverMessage:(id)arg1;	// IMP=0x00000000001834fe
+ (BOOL)deliverMessage:(id)arg1 askForReadReceipt:(BOOL)arg2;	// IMP=0x000000000018349b
+ (id)newWithMessage:(id)arg1;	// IMP=0x0000000000183396
@property(nonatomic) long long deliveryStatus; // @synthesize deliveryStatus=_deliveryStatus;
@property(retain, nonatomic) MCMessage *message; // @synthesize message=_message;
@property(nonatomic) BOOL askForReadReceipt; // @synthesize askForReadReceipt=_askForReadReceipt;
@property(nonatomic) __weak id <MFMessageDelivererDelegate> delegate; // @synthesize delegate=_delegate;
// - (void).cxx_destruct;	// IMP=0x000000000018423e
- (long long)deliverMessageHeaderData:(id)arg1 bodyData:(id)arg2 toRecipients:(id)arg3;	// IMP=0x00000000001841cd
- (long long)deliverSynchronously;	// IMP=0x0000000000183b08
- (void)deliverAsynchronously;	// IMP=0x00000000001838d1
@property(readonly, nonatomic) MCMessageHeaders *headersForDelivery;
@property(retain, nonatomic) MFDeliveryAccount *account;
- (id)init;	// IMP=0x00000000001835a4
- (id)initWithMessage:(id)arg1;	// IMP=0x0000000000183512

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly, copy, nonatomic) NSString *displayName;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

