//
//     Generated by class-dump 3.5b1 (64 bit) (Debug version compiled Dec  3 2019 19:59:57).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <MailFW/MFMutedMessageAction.h>

@interface MFMutedMessageActionMarkAsRead : MFMutedMessageAction
{
}

- (void)performActionWithChangeManager:(id)arg1;	// IMP=0x00000000001b6090
- (void)performActionWithStore:(id)arg1;	// IMP=0x00000000001b5f77

@end

