//
//     Generated by class-dump 3.5b1 (64 bit) (Debug version compiled Dec  3 2019 19:59:57).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <EmailDaemon/EDPersistence.h>

@class EDConversationPersistence, EDGmailLabelPersistence, EDLocalActionPersistence, EDMailboxPersistence, EDMessageChangeManager, EDMessagePersistence, EDPersistenceDatabase, EDSearchableIndexManager, EDServerMessagePersistenceFactory;
@protocol EDAccountsProvider;

@interface MFPersistence_macOS : EDPersistence
{
    id <EDAccountsProvider> _accountsProvider;	// 8 = 0x8
    EDConversationPersistence *_conversationPersistence;	// 16 = 0x10
    EDPersistenceDatabase *_database;	// 24 = 0x18
    EDGmailLabelPersistence *_gmailLabelPersistence;	// 32 = 0x20
    EDLocalActionPersistence *_localActionPersistence;	// 40 = 0x28
    EDMailboxPersistence *_mailboxPersistence;	// 48 = 0x30
    EDMessageChangeManager *_messageChangeManager;	// 56 = 0x38
    EDMessagePersistence *_messagePersistence;	// 64 = 0x40
    EDSearchableIndexManager *_searchableIndexManager;	// 72 = 0x48
    EDServerMessagePersistenceFactory *_serverMessagePersistenceFactory;	// 80 = 0x50
}

- (id)serverMessagePersistenceFactory;	// IMP=0x00000000001c423a
- (id)searchableIndexManager;	// IMP=0x00000000001c4224
- (id)messagePersistence;	// IMP=0x00000000001c420e
- (id)messageChangeManager;	// IMP=0x00000000001c41f8
- (id)mailboxPersistence;	// IMP=0x00000000001c41e7
- (id)localActionPersistence;	// IMP=0x00000000001c41d1
- (id)gmailLabelPersistence;	// IMP=0x00000000001c41bb
- (id)database;	// IMP=0x00000000001c41a5
- (id)conversationPersistence;	// IMP=0x00000000001c418f
- (void)setAccountsProvider:(id)arg1;	// IMP=0x00000000001c417b
- (id)accountsProvider;	// IMP=0x00000000001c416a
// - (void).cxx_destruct;	// IMP=0x00000000001c4250
- (void)_configureSearchableIndexManagerIfNecessary;	// IMP=0x00000000001c400d
- (id)threadPersistence;	// IMP=0x00000000001c4005
- (id)initWithPropertyMapper:(id)arg1;	// IMP=0x00000000001c3b30

@end

