//
//     Generated by class-dump 3.5b1 (64 bit) (Debug version compiled Dec  3 2019 19:59:57).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <MailFW/MFSizeEngine.h>

@class MFPOPAccount, NSArray, NSMutableDictionary;

@interface MFPOPSizeEngine : MFSizeEngine
{
    NSMutableDictionary *_infoByMessageID;	// 8 = 0x8
}

// - (void).cxx_destruct;	// IMP=0x00000000001df524
- (void)_messageFlagsChanged:(id)arg1;	// IMP=0x00000000001deddc
- (void)_deleteServerMessagesCompleted:(id)arg1;	// IMP=0x00000000001dedca
- (void)_fetchCompleted:(id)arg1;	// IMP=0x00000000001ded54
- (BOOL)_prepareToRefresh;	// IMP=0x00000000001ded49
- (void)_runWorkerThread;	// IMP=0x00000000001dd1e3
- (id)_remoteMailboxURL;	// IMP=0x00000000001dd193
- (id)_newMessageInfoFromMessageHeaders:(id)arg1;	// IMP=0x00000000001dcdd0
- (id)infoWithKey:(id)arg1 forMessageWithID:(id)arg2;	// IMP=0x00000000001dccdf
@property(readonly, copy) NSArray *allMessageIDs;
- (void)dealloc;	// IMP=0x00000000001dcbfd
- (id)initWithAccount:(id)arg1;	// IMP=0x00000000001dc9ac

// Remaining properties
@property(readonly, nonatomic) MFPOPAccount *account; // @dynamic account;

@end

