//
//     Generated by class-dump 3.5b1 (64 bit) (Debug version compiled Dec  3 2019 19:59:57).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <MailFW/MCRemoteAttachmentDataSource-Protocol.h>

@class MFLibraryMessage, NSLock, NSMutableDictionary, NSOperationQueue, NSProgress, NSString;

@interface MFRemoteAttachmentDataSource : NSObject <MCRemoteAttachmentDataSource>
{
    NSLock *_attachmentFetchLock;	// 8 = 0x8
    NSMutableDictionary *_completionBlocksByMimePartNumber;	// 16 = 0x10
    NSProgress *_downloadProgress;	// 24 = 0x18
    MFLibraryMessage *_message;	// 32 = 0x20
    NSOperationQueue *_attachmentFetchCompletionQueue;	// 40 = 0x28
}

+ (id)remoteAttachmentDataSourceForMessage:(id)arg1;	// IMP=0x00000000001f0059
@property(readonly, nonatomic) NSOperationQueue *attachmentFetchCompletionQueue; // @synthesize attachmentFetchCompletionQueue=_attachmentFetchCompletionQueue;
@property(readonly, nonatomic) MFLibraryMessage *message; // @synthesize message=_message;
@property(readonly, nonatomic) NSProgress *downloadProgress; // @synthesize downloadProgress=_downloadProgress;
// - (void).cxx_destruct;	// IMP=0x00000000001f0d39
- (void)fetchAttachmentForAccessLevel:(long long)arg1 mimePartNumber:(id)arg2 withCompletionBlock:(id)arg3;	// IMP=0x00000000001f09e5
- (void)_attachmentBecameAvailable:(id)arg1;	// IMP=0x00000000001f0632
@property(readonly, copy) NSString *description;
- (void)dealloc;	// IMP=0x00000000001f050e
- (id)init;	// IMP=0x00000000001f043f
- (id)initWithMessage:(id)arg1;	// IMP=0x00000000001f017e

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

