//
//     Generated by class-dump 3.5b1 (64 bit) (Debug version compiled Dec  3 2019 19:59:57).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <MailFW/MFMessageStore.h>

@class NSArray;

@interface MFRecoveredStore : MFMessageStore
{
    NSArray *_pathsToImport;	// 16 = 0x10
}

@property(readonly, copy, nonatomic) NSArray *pathsToImport; // @synthesize pathsToImport=_pathsToImport;
// - (void).cxx_destruct;	// IMP=0x00000000001e8c34
@property(readonly, nonatomic) unsigned long long approximateMessageCount;
- (BOOL)importMessagesWithBlock:(id)arg1;	// IMP=0x00000000001e839e
@property(readonly, copy, nonatomic) NSArray *messagesForImporter;
- (void)_invalidate;	// IMP=0x00000000001e825a
- (void)saveChanges;	// IMP=0x00000000001e8254
- (void)queueSaveChangesInvocation;	// IMP=0x00000000001e824e
- (void)_cancelAutosave;	// IMP=0x00000000001e8248
- (void)_setNeedsAutosave;	// IMP=0x00000000001e8242
- (void)updateMetadata;	// IMP=0x00000000001e823c
- (void)writeUpdatedMessageDataToDisk;	// IMP=0x00000000001e8236
- (id)initWithAccount:(id)arg1;	// IMP=0x00000000001e8167
- (id)initWithMailbox:(id)arg1 readOnly:(BOOL)arg2 createEmptyStore:(BOOL)arg3;	// IMP=0x00000000001e8098
- (id)init;	// IMP=0x00000000001e7fc9
- (id)initWithMailbox:(id)arg1 readOnly:(BOOL)arg2 pathsToImport:(id)arg3;	// IMP=0x00000000001e7f1b

@end

