//
//     Generated by class-dump 3.5b1 (64 bit) (Debug version compiled Dec  3 2019 19:59:57).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <EmailDaemon/EDServerMessagePersistenceFactory.h>

@interface MFServerMessagePersistenceFactory_macOS : EDServerMessagePersistenceFactory
{
}

- (long long)mailboxIDForMailboxURL:(id)arg1 useNumericSearch:(char *)arg2 supportsLabels:(char *)arg3;	// IMP=0x00000000002045c2

@end

