//
//     Generated by class-dump 3.5b1 (64 bit) (Debug version compiled Dec  3 2019 19:59:57).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <MailFW/NSObject-Protocol.h>

@class MFMessageCriterion, NSString;
@protocol MFMessageConsumer;

@protocol MFSearchableIndexQueryResultProviderBuilder <NSObject>
@property(copy, nonatomic) NSString *logIdentifier;
@property(nonatomic) unsigned int options;
@property(retain, nonatomic) MFMessageCriterion *criterion;
@property(retain, nonatomic) id <MFMessageConsumer> target;
@end

