//
//     Generated by class-dump 3.5b1 (64 bit) (Debug version compiled Dec  3 2019 19:59:57).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <MailFW/EFCancelable-Protocol.h>

@class NSArray, NSSet;
@protocol MFSearchableIndexQueryResultProcessorDelegate, MFSearchableIndexQueryResultProvider;

@protocol MFSearchableIndexQueryResultProcessor <EFCancelable>
@property(nonatomic) __weak id <MFSearchableIndexQueryResultProcessorDelegate> delegate;
- (void)provider:(id <MFSearchableIndexQueryResultProvider>)arg1 foundResults:(NSArray *)arg2;

@optional
- (void)provider:(id <MFSearchableIndexQueryResultProvider>)arg1 removedPersistentIDs:(NSSet *)arg2;
@end

