//
//     Generated by class-dump 3.5b1 (64 bit) (Debug version compiled Dec  3 2019 19:59:57).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <EmailDaemon/EDSearchableIndex.h>

#import <MailFW/EFLoggable-Protocol.h>

@class NSString;

@interface MFSearchableIndex_macOS : EDSearchableIndex <EFLoggable>
{
}

+ (id)log;	// IMP=0x00000000001f9bc1
- (void)markMessagesAsPrinted:(id)arg1;	// IMP=0x00000000001fa4ed
- (void)indexMessages:(id)arg1 includeBody:(BOOL)arg2 indexingType:(long long)arg3;	// IMP=0x00000000001fa4db
- (void)removeSearchQueryCancelable:(id)arg1;	// IMP=0x00000000001fa465
- (void)addSearchQueryCancelable:(id)arg1;	// IMP=0x00000000001fa3ef
- (BOOL)shouldCancelSearchQuery;	// IMP=0x00000000001fa3a3
- (BOOL)isPluggedIn;	// IMP=0x00000000001fa357
- (id)powerObservable;	// IMP=0x00000000001fa300
- (void)deleteMailboxWithURL:(id)arg1 databaseID:(long long)arg2;	// IMP=0x00000000001fa23b
- (BOOL)canIndexAttachments;	// IMP=0x00000000001fa230
- (void)_attachmentBecameAvailable:(id)arg1;	// IMP=0x00000000001fa19a
- (void)_messageFlagsChanged:(id)arg1;	// IMP=0x00000000001fa0a1
- (void)_indexMessages:(id)arg1 includeBody:(BOOL)arg2 indexingType:(long long)arg3;	// IMP=0x00000000001f9ed6
- (void)dealloc;	// IMP=0x00000000001f9de4
- (id)initWithName:(id)arg1 dataSource:(id)arg2 reasonProvider:(id)arg3;	// IMP=0x00000000001f9c8a

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

