//
//     Generated by class-dump 3.5b1 (64 bit) (Debug version compiled Dec  3 2019 19:59:57).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <CoreData/NSManagedObject.h>

@class NSDate, NSString;

@interface MFSeenMessage : NSManagedObject
{
}

+ (BOOL)automaticallyNotifiesObserversOfIsOnServer;	// IMP=0x00000000002022f2
+ (BOOL)automaticallyNotifiesObserversOfShouldDeleteFromServer;	// IMP=0x00000000002021ca
+ (BOOL)automaticallyNotifiesObserversOfMessageID;	// IMP=0x00000000002020e4
+ (BOOL)automaticallyNotifiesObserversOfDateSeen;	// IMP=0x0000000000201ffe
+ (BOOL)automaticallyNotifiesObserversOfAccount;	// IMP=0x0000000000201f7c
@property(nonatomic) BOOL isOnServer;
@property(nonatomic) BOOL shouldDeleteFromServer;
@property(copy, nonatomic) NSString *messageID;
@property(retain, nonatomic) NSDate *dateSeen;
- (void)setAccount:(id)arg1;	// IMP=0x0000000000201f84

@end

