//
//     Generated by class-dump 3.5b1 (64 bit) (Debug version compiled Dec  3 2019 19:59:57).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <MailFW/MFSnippetCalculatorDelegate-Protocol.h>

@class MFSnippetCalculator, NSMutableDictionary, NSMutableSet, NSOperationQueue, NSString;

@interface MFSnippetManager : NSObject <MFSnippetCalculatorDelegate>
{
    NSMutableSet *_messagesNeedingBodies;	// 8 = 0x8
    id _pendingSnippetsLock;	// 16 = 0x10
    NSMutableDictionary *_pendingSnippetDictionariesByStore;	// 24 = 0x18
    BOOL _queuedUpdate;	// 32 = 0x20
    MFSnippetCalculator *_snippetCalculator;	// 40 = 0x28
    NSOperationQueue *_snippetCommitQueue;	// 48 = 0x30
}

+ (id)sharedInstance;	// IMP=0x0000000000220a19
+ (id)allocWithZone:(struct _NSZone *)arg1;	// IMP=0x0000000000220960
+ (id)log;	// IMP=0x0000000000220903
@property(readonly, nonatomic) NSOperationQueue *snippetCommitQueue; // @synthesize snippetCommitQueue=_snippetCommitQueue;
@property(readonly, nonatomic) MFSnippetCalculator *snippetCalculator; // @synthesize snippetCalculator=_snippetCalculator;
// - (void).cxx_destruct;	// IMP=0x0000000000221b4c
- (void)_commitPendingSnippets;	// IMP=0x00000000002219f7
- (void)_queueCommitPendingSnippets;	// IMP=0x0000000000221973
- (void)snippetCalculator:(id)arg1 didSkipMessages:(id)arg2;	// IMP=0x00000000002217e2
- (void)snippetCalculator:(id)arg1 didCalculateSnippet:(id)arg2 forMessage:(id)arg3;	// IMP=0x0000000000221393
- (void)_messageBodyDataAvailable:(id)arg1;	// IMP=0x0000000000221277
- (id)fetchSnippetsForMessages:(id)arg1;	// IMP=0x0000000000220d2d
- (void)dealloc;	// IMP=0x0000000000220c28
- (id)init;	// IMP=0x0000000000220ad2

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

