//
//     Generated by class-dump 3.5b1 (64 bit) (Debug version compiled Dec  3 2019 19:59:57).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <MailFW/MFMailbox.h>

@interface MFSpecialMailbox : MFMailbox
{
}

+ (void)readFlagMailboxesFromDiskForFlagMailboxes:(id)arg1;	// IMP=0x0000000000224c5a
+ (id)visibleFlagMailboxes;	// IMP=0x0000000000223b0d
+ (void)updateVisibleFlagMailboxes;	// IMP=0x00000000002238e1
+ (id)flagMailboxes;	// IMP=0x00000000002234ef
+ (id)VIPSendersMailbox;	// IMP=0x00000000002230a4
+ (id)flagsMailbox;	// IMP=0x0000000000222ed0
+ (id)archiveMailbox;	// IMP=0x0000000000222dec
+ (id)trashMailbox;	// IMP=0x0000000000222d08
+ (id)outboxMailbox;	// IMP=0x0000000000222c24
+ (id)junkMailbox;	// IMP=0x0000000000222b40
+ (id)draftsMailbox;	// IMP=0x0000000000222a5c
+ (id)sentMessagesMailbox;	// IMP=0x0000000000222978
+ (id)inboxMailbox;	// IMP=0x0000000000222894
+ (id)specialMailboxForMailboxType:(int)arg1;	// IMP=0x00000000002227c0
+ (id)specialMailboxWithIdentifier:(id)arg1;	// IMP=0x0000000000222644
+ (id)appleScriptNameForMailboxType:(int)arg1;	// IMP=0x0000000000224f48
- (void)_updateDontIndexFlagFile;	// IMP=0x0000000000224c54
- (void)saveUserInfo;	// IMP=0x0000000000224b5e
- (id)_loadUserInfo;	// IMP=0x0000000000224a84
- (id)_viewerAttributesKey;	// IMP=0x00000000002249c2
- (id)persistentUIIdentifier;	// IMP=0x0000000000224968
- (id)_specialMailboxIdentifier;	// IMP=0x00000000002248a7
- (void)setAllCriteriaMustBeSatisfied:(BOOL)arg1;	// IMP=0x000000000022479c
- (BOOL)allCriteriaMustBeSatisfied;	// IMP=0x0000000000224753
- (void)setCriteria:(id)arg1;	// IMP=0x0000000000224638
- (id)criteria;	// IMP=0x00000000002243ea
- (unsigned long long)displayCount;	// IMP=0x000000000022424c
- (unsigned long long)indexToInsertChildMailbox:(id)arg1;	// IMP=0x000000000022423c
- (unsigned long long)indexOfChild:(id)arg1;	// IMP=0x00000000002241c2
- (id)sortedChildAtIndex:(unsigned long long)arg1 hidingGmail:(BOOL)arg2;	// IMP=0x00000000002241b0
- (unsigned long long)numberOfSortedChildrenHidingGmail:(BOOL)arg1;	// IMP=0x000000000022419e
- (unsigned long long)numberOfVisibleChildrenHidingGmail:(BOOL)arg1;	// IMP=0x0000000000224122
- (unsigned long long)numberOfChildren;	// IMP=0x00000000002240de
- (id)visibleChildAtIndex:(unsigned long long)arg1;	// IMP=0x000000000022403b
- (id)childAtIndex:(unsigned long long)arg1;	// IMP=0x0000000000223fdc
- (id)mutableCopyOfChildrenIncludingHiddenChildren:(BOOL)arg1 hidingGmail:(BOOL)arg2;	// IMP=0x0000000000223f98
- (id)childEnumeratorIncludingHiddenChildren:(BOOL)arg1;	// IMP=0x0000000000223f48
- (id)children;	// IMP=0x0000000000223e0e
- (BOOL)hasMessages;	// IMP=0x0000000000223b68
- (id)account;	// IMP=0x00000000002234e7
- (id)displayName;	// IMP=0x00000000002232bd
- (id)criterion;	// IMP=0x000000000022324f
- (id)_initWithName:(id)arg1 type:(int)arg2 uuid:(id)arg3;	// IMP=0x0000000000223188
- (id)messages;	// IMP=0x00000000002251cf
- (id)objectSpecifier;	// IMP=0x00000000002250d4
- (id)appleScriptKey;	// IMP=0x000000000022500c

@end

