//
//     Generated by class-dump 3.5b1 (64 bit) (Debug version compiled Dec  3 2019 19:59:57).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <MailFW/NSFilePresenter-Protocol.h>

@class NSOperationQueue, NSSet, NSString, NSURL;

@interface MFSyncedFile : NSObject <NSFilePresenter>
{
    NSURL *_cloudURL;	// 8 = 0x8
    id _cloudURLLock;	// 16 = 0x10
    id _cloudFileLock;	// 24 = 0x18
    NSURL *_URL;	// 32 = 0x20
    long long _syncState;	// 40 = 0x28
}

+ (void)_checkForiCloudMetadata;	// IMP=0x000000000022c7de
+ (id)_metadataURL;	// IMP=0x000000000022a4c6
+ (void)_setMetadata:(id)arg1;	// IMP=0x000000000022a44f
+ (id)_metadata;	// IMP=0x000000000022a25b
+ (id)_currentiCloudAccount;	// IMP=0x000000000022a204
+ (id)syncedFileForRelativePath:(id)arg1;	// IMP=0x0000000000228f1a
+ (void)initialize;	// IMP=0x00000000002289bf
+ (id)log;	// IMP=0x0000000000228962
@property long long syncState; // @synthesize syncState=_syncState;
@property(readonly, nonatomic) NSURL *URL; // @synthesize URL=_URL;
// - (void).cxx_destruct;	// IMP=0x0000000000230a0e
- (void)_handleIdentityChange:(id)arg1;	// IMP=0x00000000002306ab
- (void)_resolveConflicts;	// IMP=0x0000000000230007
- (id)_ubiquitousFileForVersion:(long long)arg1;	// IMP=0x000000000022fd8e
@property(readonly) NSURL *cloudURL;
- (BOOL)_fileExistsInCloud;	// IMP=0x000000000022fb78
- (BOOL)_writeDataToCloud:(id)arg1 options:(unsigned long long)arg2 error:(id *)arg3;	// IMP=0x000000000022e8d0
- (id)_upgradedLegacyDataIsReachable:(char *)arg1;	// IMP=0x000000000022e5c3
- (BOOL)_updateLocalPostNotification:(BOOL)arg1 didUpdate:(char *)arg2 error:(id *)arg3;	// IMP=0x000000000022dcc8
- (BOOL)_mergeUpdateLocal:(char *)arg1 error:(id *)arg2;	// IMP=0x000000000022d04c
- (BOOL)_waitForMetadata;	// IMP=0x000000000022cdb9
- (BOOL)_syncWithCloudPostNotification:(BOOL)arg1 error:(id *)arg2;	// IMP=0x000000000022c942
- (BOOL)_deleteLocalFileAndReturnError:(id *)arg1;	// IMP=0x000000000022c5e7
- (void)deleteFile;	// IMP=0x000000000022bdfe
- (id)_readPlistWithOptions:(unsigned long long)arg1 error:(id *)arg2;	// IMP=0x000000000022bd41
- (id)readPlistWithOptions:(unsigned long long)arg1;	// IMP=0x000000000022b88b
- (void)writePlist:(id)arg1 options:(unsigned long long)arg2;	// IMP=0x000000000022b3bb
- (id)readDataWithOptions:(unsigned long long)arg1;	// IMP=0x000000000022b02c
- (BOOL)_writeDataLocally:(id)arg1 options:(unsigned long long)arg2 setMetadata:(BOOL)arg3 postNotification:(BOOL)arg4 error:(id *)arg5;	// IMP=0x000000000022adc0
- (BOOL)_writeDataAfterResolvingConflict:(id)arg1 options:(unsigned long long)arg2 error:(id *)arg3;	// IMP=0x000000000022ac35
- (BOOL)_writeData:(id)arg1 options:(unsigned long long)arg2 error:(id *)arg3;	// IMP=0x000000000022a85d
- (void)writeData:(id)arg1 options:(unsigned long long)arg2;	// IMP=0x000000000022a526
- (void)_clearMetadata;	// IMP=0x000000000022a0fa
@property(nonatomic) BOOL hasMigratedFromLegacy;
- (BOOL)_signedInState;	// IMP=0x0000000000229d84
- (void)_setiCloudAccount;	// IMP=0x00000000002299d8
- (id)_iCloudAccount;	// IMP=0x0000000000229753
- (void)presentedItemDidResolveConflictVersion:(id)arg1;	// IMP=0x000000000022974d
- (void)presentedItemDidMoveToURL:(id)arg1;	// IMP=0x000000000022950f
- (void)presentedItemDidGainVersion:(id)arg1;	// IMP=0x00000000002293ad
- (void)presentedItemDidChange;	// IMP=0x0000000000229190
- (void)accommodatePresentedItemDeletionWithCompletionHandler:(id)arg1;	// IMP=0x0000000000229015
@property(readonly, retain) NSOperationQueue *presentedItemOperationQueue;
@property(readonly, copy) NSURL *presentedItemURL;
- (void)dealloc;	// IMP=0x0000000000228dcc
- (id)init;	// IMP=0x0000000000228cfd
- (id)initWithRelativePath:(id)arg1;	// IMP=0x0000000000228afe

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) NSSet *observedPresentedItemUbiquityAttributes;
@property(readonly, copy) NSURL *primaryPresentedItemURL;
@property(readonly) Class superclass;

@end

