//
//     Generated by class-dump 3.5b1 (64 bit) (Debug version compiled Dec  3 2019 19:59:57).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <MailFW/MFRemoveMessagesUpgradeStep.h>

@interface MFTemporaryUIDsCleanupUpgradeStep : MFRemoveMessagesUpgradeStep
{
}

+ (unsigned long long)targetVersion;	// IMP=0x000000000023273c
- (void)runWithRowIDsNeedingConversationRecalculation:(id)arg1;	// IMP=0x0000000000232747

@end

