//
//     Generated by class-dump 3.5b1 (64 bit) (Debug version compiled Dec  3 2019 19:59:57).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSString.h>

@interface NSString (EmailAddressingAdditions)
+ (id)ea_partialSurnames;	// IMP=0x0000000000009e9b
+ (id)ea_nameExtensions;	// IMP=0x0000000000009d70
+ (void)__ea_extractFirstName:(id *)arg1 middleName:(id *)arg2 lastName:(id *)arg3 extension:(id *)arg4 fromString:(id)arg5;	// IMP=0x000000000000910c
- (BOOL)ea_isEqualToEmailAddress:(id)arg1;	// IMP=0x000000000000a1ba
- (id)ea_trimCommasSpacesQuotes;	// IMP=0x0000000000009fd7
- (BOOL)ea_appearsToBeAnInitial;	// IMP=0x0000000000009f67
- (id)ea_personNameComponents;	// IMP=0x0000000000008f81
- (BOOL)ea_isLegalCommentedEmailAddress;	// IMP=0x0000000000008f26
- (id)ea_addressComment;	// IMP=0x0000000000008e12
- (id)ea_addressCommentPersonNameComponents;	// IMP=0x0000000000008896
- (BOOL)ea_isLegalEmailAddress;	// IMP=0x0000000000008213
- (id)ea_uncommentedAddressRespectingGroups;	// IMP=0x0000000000008190
- (id)ea_uncommentedAddress;	// IMP=0x0000000000007d74
@end

