#!/bin/bash

tempBaseDir=/private/tmp/MailTrackerBlocker-Installation-Temp
running="${tempBaseDir}/running"
currentMacOSVer="$(sw_vers -productVersion)"
macOSBigSur="11.0"
targetDir=/Library/Mail/Bundles

# Move our temporary installation into the real destination.
mkdir -p "${targetDir}" || exit 1
rm -rf "${targetDir}/MailTrackerBlocker.mailbundle"
mv "${tempBaseDir}/MailTrackerBlocker.mailbundle" "${targetDir}/"

# macOS 11.0 and up require code signing
# older versions will NOT run if signed so we have to remove the sig
if [ "$(printf '%s\n' "$macOSBigSur" "$currentMacOSVer" | sort -V | head -n1)" != "$macOSBigSur" ]; then
    # xcrun/codesign_allocate errors on some systems so incl. our own unsign tool
    if [[ -e "$tempBaseDir/unsign" ]]; then
        ${tempBaseDir}/unsign ${targetDir}/MailTrackerBlocker.mailbundle/Contents/MacOS/MailTrackerBlocker
        mv ${targetDir}/MailTrackerBlocker.mailbundle/Contents/MacOS/MailTrackerBlocker.unsigned ${targetDir}/MailTrackerBlocker.mailbundle/Contents/MacOS/MailTrackerBlocker
    else
        codesign --remove-signature $targetDir/MailTrackerBlocker.mailbundle || exit 1
    fi
fi 

######
# Note that we are running sudo'd, so these defaults will be written to
# /Library/Preferences/com.apple.mail.plist
#
# Mail must NOT be running by the time this script executes
######
defaults write "/Library/Preferences/com.apple.mail" EnableBundles -bool YES
defaults write com.apple.mail EnableBundles -bool YES

#relaunch mail if it was running before started
if [ -f "$running" ]; then
    osascript -e "activate app \"Mail\""
fi

# Remove our temporary directory so that another user account on the same system can install.
rm -rf "${tempBaseDir}"

exit 0