//
//     Generated by class-dump 3.5b1 (64 bit) (Debug version compiled Dec  3 2019 19:59:57).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSLock.h>

@interface _IMAPLock : NSLock
{
}

- (void)performBlock:(CDUnknownBlockType)arg1;	// IMP=0x000000000005969a

@end

