//
//     Generated by class-dump 3.5b1 (64 bit) (Debug version compiled Dec  3 2019 19:59:57).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IMAP/NSObject-Protocol.h>

@class NSData, NSURL;
@protocol ECMessage;

@protocol ECLocalActionReplayerDelegate <NSObject>
- (BOOL)moveSupportedFromMailboxURL:(NSURL *)arg1 toURL:(NSURL *)arg2;
- (NSData *)messageDataForMessage:(id <ECMessage>)arg1;
@end

