//
//     Generated by class-dump 3.5b1 (64 bit) (Debug version compiled Dec  3 2019 19:59:57).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IMAP/IMAPSingleCommand.h>

@class NSIndexSet, NSMutableArray;
@protocol IMAPFetchResponseHandler;

@interface IMAPFetchCommand : IMAPSingleCommand
{
    NSIndexSet *_messageNumbers;	// 8 = 0x8
    NSMutableArray *_dataItems;	// 16 = 0x10
    id <IMAPFetchResponseHandler> _responseHandler;	// 24 = 0x18
}

+ (id)_fetchDataItemsForMessageSkeletons;	// IMP=0x000000000002eae3
+ (id)_headersToFetch;	// IMP=0x000000000002e5f9
@property(retain) id <IMAPFetchResponseHandler> responseHandler; // @synthesize responseHandler=_responseHandler;
@property(retain) NSMutableArray *dataItems; // @synthesize dataItems=_dataItems;
@property(copy) NSIndexSet *messageNumbers; // @synthesize messageNumbers=_messageNumbers;
- (void).cxx_destruct;	// IMP=0x000000000002ed94
- (long long)maxAllowedConnectionState;	// IMP=0x000000000002ed14
- (long long)minRequiredConnectionState;	// IMP=0x000000000002ed09
- (id)_newMessageSetCommandString;	// IMP=0x000000000002e560
- (struct _NSRange)_nsRangeForIMAPRange:(CDStruct_f792af56)arg1;	// IMP=0x000000000002e53e
- (BOOL)_isLegalRange:(CDStruct_f792af56)arg1;	// IMP=0x000000000002e510
- (BOOL)executeOnConnection:(id)arg1;	// IMP=0x000000000002e4f5
- (id)newCommandDataForLiteralPlus:(BOOL)arg1;	// IMP=0x000000000002dfd3
- (void)addMessageUidsAndFlagsDataItems;	// IMP=0x000000000002df41
- (void)addMessageSkeletonDataItems;	// IMP=0x000000000002ddfa
- (void)addDataItem:(id)arg1;	// IMP=0x000000000002dd85
- (id)activityString;	// IMP=0x000000000002dd18
- (id)commandTypeString;	// IMP=0x000000000002dcf9
@property CDStruct_f792af56 range;
- (void)_imapClientFetchCommandCommonInitWithMessageNumbers:(id)arg1;	// IMP=0x000000000002db32
- (id)description;	// IMP=0x000000000002dae8
- (id)initWithRange:(CDStruct_f792af56)arg1;	// IMP=0x000000000002d92d
- (id)init;	// IMP=0x000000000002d919
- (id)initWithMessageNumbers:(id)arg1;	// IMP=0x000000000002d772

@end

