//
//     Generated by class-dump 3.5b1 (64 bit) (Debug version compiled Dec  3 2019 19:59:57).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IMAP/IMAPFetchResult.h>

@class NSArray;

@interface IMAPEnvelopeFetchResult : IMAPFetchResult
{
    NSArray *_envelope;	// 8 = 0x8
}

@property(copy, nonatomic) NSArray *envelope; // @synthesize envelope=_envelope;
- (void).cxx_destruct;	// IMP=0x0000000000031116
- (id)description;	// IMP=0x0000000000031086

@end

