//
//     Generated by class-dump 3.5b1 (64 bit) (Debug version compiled Dec  3 2019 19:59:57).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IMAP/IMAPResponse.h>

@class NSArray, NSString;

@interface IMAPOtherResponse : IMAPResponse
{
    NSString *_responseName;	// 8 = 0x8
    NSArray *_parameters;	// 16 = 0x10
}

@property(copy, nonatomic) NSArray *parameters; // @synthesize parameters=_parameters;
@property(copy, nonatomic) NSString *responseName; // @synthesize responseName=_responseName;
- (void).cxx_destruct;	// IMP=0x0000000000049ae8
- (id)description;	// IMP=0x00000000000499cc

@end

