//
//     Generated by class-dump 3.5b1 (64 bit) (Debug version compiled Dec  3 2019 19:59:57).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <IMAP/IMAPFetchResponseHandler-Protocol.h>

@class NSMutableArray, NSString;

@interface IMAPDownloadCache : NSObject <IMAPFetchResponseHandler>
{
    NSMutableArray *_downloads;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x000000000000d768
- (void)addCommandsForDownload:(id)arg1 toPipeline:(id)arg2;	// IMP=0x00000000000101e3
- (void)_lockedAddDownload:(id)arg1 atIndex:(unsigned long long)arg2 forUid:(unsigned int)arg3;	// IMP=0x000000000002d479
- (void)addDownload:(id)arg1 forUid:(unsigned int)arg2;	// IMP=0x000000000002d3a1
- (void)cleanUpDownloadsForUid:(unsigned int)arg1;	// IMP=0x0000000000014300
- (id)recoverFromErrorInDownload:(id)arg1;	// IMP=0x000000000002d0cb
- (void)processResultsForUid:(unsigned int)arg1;	// IMP=0x0000000000012d34
- (void)handleFetchResponses:(id)arg1;	// IMP=0x0000000000012a10
- (BOOL)handleFetchResponse:(id)arg1 forUid:(unsigned int)arg2;	// IMP=0x00000000000118e8
- (BOOL)handleResponse:(id)arg1 forCommand:(id)arg2;	// IMP=0x000000000002cfdb
- (BOOL)_lockedUpdateDownloadsInRange:(struct _NSRange)arg1 fetchResults:(id)arg2 error:(id)arg3;	// IMP=0x00000000000119df
- (id)downloadForUid:(unsigned int)arg1 partSectionSpecifier:(id)arg2 textSectionSpecifier:(long long)arg3 expectedLength:(unsigned int)arg4;	// IMP=0x0000000000010a70
- (id)downloadForUid:(unsigned int)arg1 partSectionSpecifier:(id)arg2 textSectionSpecifier:(long long)arg3 length:(unsigned int)arg4;	// IMP=0x0000000000011719
- (id)_getDownloadForUid:(unsigned int)arg1 partSectionSpecifier:(id)arg2 textSectionSpecifier:(long long)arg3 length:(unsigned int)arg4 estimatedLength:(unsigned int)arg5;	// IMP=0x0000000000010a95
- (id)downloadForMessage:(id)arg1;	// IMP=0x000000000000fd81
- (struct _NSRange)_findRangeOrInsertionPointForDownloadsWithUid:(unsigned int)arg1;	// IMP=0x000000000000ff8c
@property(readonly, copy) NSString *description;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

