//
//     Generated by class-dump 3.5b1 (64 bit) (Debug version compiled Dec  3 2019 19:59:57).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface IMAPFetchDataItem : NSObject
{
    NSString *_commandString;	// 8 = 0x8
}

+ (id)gmailLabelsDataItem;	// IMP=0x000000000002f24c
+ (id)modificationSequenceDataItem;	// IMP=0x000000000002f1cc
+ (id)sizeDataItem;	// IMP=0x000000000002f14c
+ (id)internalDateDataItem;	// IMP=0x000000000002f0cc
+ (id)bodyStructureDataItem;	// IMP=0x000000000002f04c
+ (id)UIDDataItem;	// IMP=0x000000000002efcc
+ (id)flagsDataItem;	// IMP=0x000000000002ef4c
@property(copy, nonatomic) NSString *commandString; // @synthesize commandString=_commandString;
- (void).cxx_destruct;	// IMP=0x000000000002f4a3
- (id)description;	// IMP=0x000000000002f3f6
- (unsigned long long)hash;	// IMP=0x000000000002f3b2
- (BOOL)isEqual:(id)arg1;	// IMP=0x000000000002f2cc

@end

