//
//     Generated by class-dump 3.5b1 (64 bit) (Debug version compiled Dec  3 2019 19:59:57).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IMAP/IMAPNetworkTaskOperation.h>

#import <IMAP/ECIMAPLocalActionReplayerDelegate-Protocol.h>

@class ECLocalMessageAction, NSProgress, NSString;
@protocol IMAPMessageActionSyncOperationDelegate, IMAPMessageDataSource;

@interface IMAPMessageActionSyncOperation : IMAPNetworkTaskOperation <ECIMAPLocalActionReplayerDelegate>
{
    id <IMAPMessageDataSource> _dataSource;	// 8 = 0x8
    ECLocalMessageAction *_messageAction;	// 16 = 0x10
    id <IMAPMessageActionSyncOperationDelegate> _delegate;	// 24 = 0x18
    NSProgress *_progress;	// 32 = 0x20
}

@property(retain, nonatomic) NSProgress *progress; // @synthesize progress=_progress;
@property(nonatomic) __weak id <IMAPMessageActionSyncOperationDelegate> delegate; // @synthesize delegate=_delegate;
@property(readonly, nonatomic) ECLocalMessageAction *messageAction; // @synthesize messageAction=_messageAction;
@property(readonly, nonatomic) id <IMAPMessageDataSource> dataSource; // @synthesize dataSource=_dataSource;
- (void).cxx_destruct;	// IMP=0x000000000004431c
- (id)messageDataForRemoteID:(id)arg1 mailboxURL:(id)arg2;	// IMP=0x00000000000441d1
- (BOOL)checkUIDValidity:(unsigned int)arg1 mailboxURL:(id)arg2;	// IMP=0x00000000000440f2
- (id)flagsForIMAPUIDs:(id)arg1 mailboxURL:(id)arg2;	// IMP=0x0000000000043d7a
- (id)imapMailboxNameForMailboxURL:(id)arg1;	// IMP=0x0000000000043cb3
- (BOOL)moveSupportedFromMailboxURL:(id)arg1 toURL:(id)arg2;	// IMP=0x0000000000043b99
- (id)messageDataForMessage:(id)arg1;	// IMP=0x0000000000043b7d
- (void)main;	// IMP=0x0000000000043016
- (BOOL)errorIsIMAPError:(id)arg1;	// IMP=0x0000000000042f2b
@property(readonly, copy) NSString *description;
- (id)initWithMailboxName:(id)arg1;	// IMP=0x0000000000042d8b
- (id)initWithDataSource:(id)arg1 messageAction:(id)arg2;	// IMP=0x0000000000042cbb

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

