//
//     Generated by class-dump 3.5b1 (64 bit) (Debug version compiled Dec  3 2019 19:59:57).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IMAP/IMAPCompoundDownload.h>

@protocol IMAPMessage;

@interface IMAPAttachmentsDownload : IMAPCompoundDownload
{
    unsigned int _bytesFetchedForCompletedSubdownlaods;	// 8 = 0x8
    id <IMAPMessage> _message;	// 16 = 0x10
}

@property(retain) id <IMAPMessage> message; // @synthesize message=_message;
- (void).cxx_destruct;	// IMP=0x0000000000016375
- (unsigned int)bytesFetched;	// IMP=0x000000000001812b
- (void)saveCompletedDownloads;	// IMP=0x0000000000015fcd
- (id)createCopy;	// IMP=0x00000000000180af
- (id)initWithIMAPMessage:(id)arg1;	// IMP=0x0000000000015f48

@end

