//
//     Generated by class-dump 3.5b1 (64 bit) (Debug version compiled Dec  3 2019 19:59:57).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IMAP/NSObject-Protocol.h>

@class IMAPMessageActionPersistResultsOperation, NSMutableSet;

@protocol IMAPMessageActionPersistResultsOperationDelegate <NSObject>
- (void)persistActionResultsOperationCompleted:(IMAPMessageActionPersistResultsOperation *)arg1 needToReplayAction:(BOOL)arg2 messagesNeedingBodies:(NSMutableSet *)arg3;
@end

