//
//     Generated by class-dump 3.5b1 (64 bit) (Debug version compiled Dec  3 2019 19:59:57).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IMAP/IMAPResponse.h>

@class NSString;

@interface IMAPListResponse : IMAPResponse
{
    unsigned long long _mailboxAttributes;	// 8 = 0x8
    NSString *_separator;	// 16 = 0x10
    NSString *_mailboxName;	// 24 = 0x18
}

+ (BOOL)handlesResponseWithName:(const char *)arg1 ofLength:(unsigned long long)arg2;	// IMP=0x0000000000009b42
@property(copy, nonatomic) NSString *mailboxName; // @synthesize mailboxName=_mailboxName;
@property(copy, nonatomic) NSString *separator; // @synthesize separator=_separator;
@property(nonatomic) unsigned long long mailboxAttributes; // @synthesize mailboxAttributes=_mailboxAttributes;
- (void).cxx_destruct;	// IMP=0x000000000000aa35
- (unsigned long long)mailboxAttributesFromSet:(id)arg1;	// IMP=0x000000000000a728
- (id)_newStringForMailboxAttributes;	// IMP=0x0000000000033c6f
- (id)description;	// IMP=0x0000000000033b29
- (const char *)_responseName;	// IMP=0x0000000000033b1c

@end

