//
//     Generated by class-dump 3.5b1 (64 bit) (Debug version compiled Dec  3 2019 19:59:57).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IMAP/IMAPSingleCommand.h>

@class NSString;

@interface IMAPGetQuotaCommand : IMAPSingleCommand
{
    NSString *_quotaRoot;	// 8 = 0x8
}

@property(readonly, copy, nonatomic) NSString *quotaRoot; // @synthesize quotaRoot=_quotaRoot;
- (void).cxx_destruct;	// IMP=0x00000000000500d7
- (long long)maxAllowedConnectionState;	// IMP=0x00000000000500b9
- (long long)minRequiredConnectionState;	// IMP=0x00000000000500ae
- (id)newCommandDataForLiteralPlus:(BOOL)arg1;	// IMP=0x000000000004ffc1
- (BOOL)shouldSendAgainOnError;	// IMP=0x000000000004ffb6
- (id)activityString;	// IMP=0x000000000004ff4a
- (id)commandTypeString;	// IMP=0x000000000004ff2b
- (id)init;	// IMP=0x000000000004ff17
- (id)initWithQuotaRoot:(id)arg1;	// IMP=0x000000000004fe4b

@end

