//
//     Generated by class-dump 3.5b1 (64 bit) (Debug version compiled Dec  3 2019 19:59:57).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IMAP/IMAPPersistenceTaskOperation.h>

@interface IMAPPersistenceBlockOperation : IMAPPersistenceTaskOperation
{
    BOOL _blockCompleted;	// 8 = 0x8
    CDUnknownBlockType _block;	// 16 = 0x10
}

@property(readonly, nonatomic) CDUnknownBlockType block; // @synthesize block=_block;
@property(nonatomic) BOOL blockCompleted; // @synthesize blockCompleted=_blockCompleted;
- (void).cxx_destruct;	// IMP=0x000000000004cd25
- (void)main;	// IMP=0x000000000004cc74
- (id)initWithDataSource:(id)arg1;	// IMP=0x000000000004cba5
- (id)initWithDataSource:(id)arg1 block:(CDUnknownBlockType)arg2;	// IMP=0x000000000004cb0f

@end

