//
//     Generated by class-dump 3.5b1 (64 bit) (Debug version compiled Dec  3 2019 19:59:57).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IMAP/IMAPResponse.h>

@class NSDictionary, NSString;

@interface IMAPStatusResponse : IMAPResponse
{
    NSString *_mailboxName;	// 8 = 0x8
    NSDictionary *_statusEntries;	// 16 = 0x10
}

+ (BOOL)handlesResponseWithName:(const char *)arg1 ofLength:(unsigned long long)arg2;	// IMP=0x000000000000c696
@property(copy, nonatomic) NSDictionary *statusEntries; // @synthesize statusEntries=_statusEntries;
@property(copy, nonatomic) NSString *mailboxName; // @synthesize mailboxName=_mailboxName;
- (void).cxx_destruct;	// IMP=0x000000000000ce2c
- (id)description;	// IMP=0x0000000000055120

@end

