//
//     Generated by class-dump 3.5b1 (64 bit) (Debug version compiled Dec  3 2019 19:59:57).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IMAP/NSObject-Protocol.h>

@class IMAPGetAttachmentsDownloadsOperation, NSArray;

@protocol IMAPGetAttachmentsDownloadsOperationDelegate <NSObject>
- (void)getAttachmentsDownloadsOperation:(IMAPGetAttachmentsDownloadsOperation *)arg1 gotDownloads:(NSArray *)arg2 missedMessages:(NSArray *)arg3;
@end

