//
//     Generated by class-dump 3.5b1 (64 bit) (Debug version compiled Dec  3 2019 19:59:57).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IMAP/NSObject-Protocol.h>

@class IMAPSyncAttachmentsOperation, NSArray;

@protocol IMAPSyncAttachmentsOperationDelegate <NSObject>
- (void)syncAttachmentsOperation:(IMAPSyncAttachmentsOperation *)arg1 syncedAttachmentsForDownloads:(NSArray *)arg2;
@end

