//
//     Generated by class-dump 3.5b1 (64 bit) (Debug version compiled Dec  3 2019 19:59:57).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IMAP/IMAPMessage.h>

@class MCMessageHeaders, NSData;

@interface IMAPMessageWithCache : IMAPMessage
{
    NSData *_messageData;	// 104 = 0x68
    MCMessageHeaders *_headers;	// 112 = 0x70
}

- (void).cxx_destruct;	// IMP=0x0000000000014538
- (id)headerDataFetchIfNotAvailable:(BOOL)arg1 allowPartial:(BOOL)arg2;	// IMP=0x00000000000457b3
- (void)setHeaders:(id)arg1;	// IMP=0x000000000000f9d6
- (id)headersFetchIfNotAvailable:(BOOL)arg1;	// IMP=0x000000000004575d
- (BOOL)isMessageContentLocallyAvailable;	// IMP=0x000000000000fbf1
- (id)bodyDataFetchIfNotAvailable:(BOOL)arg1 allowPartial:(BOOL)arg2;	// IMP=0x0000000000045651
- (id)messageDataFetchIfNotAvailable:(BOOL)arg1 newDocumentID:(id)arg2;	// IMP=0x00000000000454cb
@property(copy) NSData *messageData;

@end

