//
//     Generated by class-dump 3.5b1 (64 bit) (Debug version compiled Dec  3 2019 19:59:57).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IMAP/IMAPSingleCommand.h>

@class NSString;

@interface IMAPMailboxCommand : IMAPSingleCommand
{
    NSString *_mailboxName;	// 8 = 0x8
    NSString *_mailboxArgumentName;	// 16 = 0x10
}

@property(copy) NSString *mailboxArgumentName; // @synthesize mailboxArgumentName=_mailboxArgumentName;
@property(copy) NSString *mailboxName; // @synthesize mailboxName=_mailboxName;
- (void).cxx_destruct;	// IMP=0x0000000000035ef7
- (long long)maxAllowedConnectionState;	// IMP=0x0000000000035e9e
- (long long)minRequiredConnectionState;	// IMP=0x0000000000035e93
- (id)simpleDescriptionString;	// IMP=0x0000000000035dd3
- (id)newCommandDataForLiteralPlus:(BOOL)arg1;	// IMP=0x0000000000035d35
- (id)debugCommandStringWithAccount:(id)arg1;	// IMP=0x0000000000035c3b
- (BOOL)shouldSendAgainOnError;	// IMP=0x0000000000035c30
- (id)init;	// IMP=0x0000000000035b61
- (id)initWithMailboxName:(id)arg1;	// IMP=0x00000000000359fa

@end

