//
//     Generated by class-dump 3.5b1 (64 bit) (Debug version compiled Dec  3 2019 19:59:57).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IMAP/IMAPNetworkTaskOperation.h>

@class IMAPDownloadCache, NSArray;
@protocol IMAPMessageDataSource, IMAPSyncAttachmentsOperationDelegate;

@interface IMAPSyncAttachmentsOperation : IMAPNetworkTaskOperation
{
    NSArray *_downloads;	// 8 = 0x8
    id <IMAPMessageDataSource> _dataSource;	// 16 = 0x10
    id <IMAPSyncAttachmentsOperationDelegate> _delegate;	// 24 = 0x18
    IMAPDownloadCache *_downloadCache;	// 32 = 0x20
}

@property(retain, nonatomic) IMAPDownloadCache *downloadCache; // @synthesize downloadCache=_downloadCache;
@property(readonly, nonatomic) __weak id <IMAPSyncAttachmentsOperationDelegate> delegate; // @synthesize delegate=_delegate;
@property(readonly, nonatomic) id <IMAPMessageDataSource> dataSource; // @synthesize dataSource=_dataSource;
@property(readonly, copy, nonatomic) NSArray *downloads; // @synthesize downloads=_downloads;
- (void).cxx_destruct;	// IMP=0x000000000005607a
- (void)main;	// IMP=0x0000000000055510
- (id)description;	// IMP=0x0000000000055476
- (id)initWithMailboxName:(id)arg1;	// IMP=0x00000000000553a7
- (id)initWithDownloads:(id)arg1 dataSource:(id)arg2 downloadCache:(id)arg3 delegate:(id)arg4;	// IMP=0x0000000000055284

@end

