//
//     Generated by class-dump 3.5b1 (64 bit) (Debug version compiled Dec  3 2019 19:59:57).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IMAP/IMAPTask.h>

#import <IMAP/EFSignpostable-Protocol.h>
#import <IMAP/IMAPGetNewLocalActionsOperationDelegate-Protocol.h>
#import <IMAP/IMAPMessageActionPersistResultsOperationDelegate-Protocol.h>
#import <IMAP/IMAPMessageActionSyncOperationDelegate-Protocol.h>

@class ECLocalMessageActionResults, IMAPTaskManager, NSMutableArray, NSMutableDictionary, NSString, NSURL;
@protocol IMAPMessageDataSource;

@interface IMAPLocalActionSyncTask : IMAPTask <EFSignpostable, IMAPMessageActionSyncOperationDelegate, IMAPMessageActionPersistResultsOperationDelegate, IMAPGetNewLocalActionsOperationDelegate>
{
    NSMutableArray *_messageActions;	// 8 = 0x8
    NSMutableDictionary *_progressesByActionIDs;	// 16 = 0x10
    BOOL _actionOperationRunning;	// 24 = 0x18
    BOOL _needToCheckForActions;	// 25 = 0x19
    BOOL _needToPersistResults;	// 26 = 0x1a
    IMAPTaskManager *_taskManager;	// 32 = 0x20
    NSURL *_currentMailboxURL;	// 40 = 0x28
    id <IMAPMessageDataSource> _currentDataSource;	// 48 = 0x30
    ECLocalMessageActionResults *_resultsToPersist;	// 56 = 0x38
}

+ (id)signpostLog;	// IMP=0x0000000000033d5c
@property(retain, nonatomic) ECLocalMessageActionResults *resultsToPersist; // @synthesize resultsToPersist=_resultsToPersist;
@property(nonatomic) BOOL needToPersistResults; // @synthesize needToPersistResults=_needToPersistResults;
@property(nonatomic) BOOL needToCheckForActions; // @synthesize needToCheckForActions=_needToCheckForActions;
@property(nonatomic) BOOL actionOperationRunning; // @synthesize actionOperationRunning=_actionOperationRunning;
@property(retain, nonatomic) id <IMAPMessageDataSource> currentDataSource; // @synthesize currentDataSource=_currentDataSource;
@property(retain, nonatomic) NSURL *currentMailboxURL; // @synthesize currentMailboxURL=_currentMailboxURL;
@property(retain, nonatomic) IMAPTaskManager *taskManager; // @synthesize taskManager=_taskManager;
- (void).cxx_destruct;	// IMP=0x00000000000355e9
- (void)_createProgressForAction:(id)arg1;	// IMP=0x0000000000035360
- (void)persistActionResultsOperationCompleted:(id)arg1 needToReplayAction:(BOOL)arg2 messagesNeedingBodies:(id)arg3;	// IMP=0x0000000000034f45
- (void)messageActionSyncOperationCompleted:(id)arg1 results:(id)arg2;	// IMP=0x0000000000034e02
- (void)getNewMessageActionsOperation:(id)arg1 didGetActions:(id)arg2;	// IMP=0x0000000000034bc8
- (void)end;	// IMP=0x0000000000034a9e
- (id)nextPersistenceOperation;	// IMP=0x0000000000034855
- (id)nextNetworkOperation;	// IMP=0x0000000000034713
- (void)operationFinished:(id)arg1;	// IMP=0x00000000000346d2
- (void)_updateMailboxIfNeeded;	// IMP=0x000000000003455e
- (void)recalculatePriorities;	// IMP=0x000000000003434a
- (void)addLocalAction:(id)arg1;	// IMP=0x00000000000341f6
- (void)checkForNewMessageActions;	// IMP=0x00000000000341c3
- (id)mailboxNameWithoutPII;	// IMP=0x0000000000034149
- (id)initWithMailboxName:(id)arg1;	// IMP=0x000000000003407a
- (id)initWithTaskManager:(id)arg1;	// IMP=0x0000000000033e75
@property(readonly) unsigned long long signpostID;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

