//
//     Generated by class-dump 3.5b1 (64 bit) (Debug version compiled Dec  3 2019 19:59:57).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IMAP/IMAPNetworkTaskOperation.h>

#import <IMAP/IMAPFetchResponseHandler-Protocol.h>

@class NSIndexSet, NSMutableArray, NSString;
@protocol IMAPSyncSkeletonsOperationDelegate;

@interface IMAPSyncSkeletonsOperation : IMAPNetworkTaskOperation <IMAPFetchResponseHandler>
{
    NSMutableArray *_fetchResponses;	// 8 = 0x8
    BOOL _useUIDs;	// 16 = 0x10
    BOOL _includeLabels;	// 17 = 0x11
    NSIndexSet *_messageNumbers;	// 24 = 0x18
    id <IMAPSyncSkeletonsOperationDelegate> _delegate;	// 32 = 0x20
}

@property(readonly, nonatomic) __weak id <IMAPSyncSkeletonsOperationDelegate> delegate; // @synthesize delegate=_delegate;
@property(readonly, nonatomic) BOOL includeLabels; // @synthesize includeLabels=_includeLabels;
@property(readonly, nonatomic) BOOL useUIDs; // @synthesize useUIDs=_useUIDs;
@property(readonly, copy, nonatomic) NSIndexSet *messageNumbers; // @synthesize messageNumbers=_messageNumbers;
- (void).cxx_destruct;	// IMP=0x00000000000582a3
- (id)_findFetchResponseWithMessageNumber:(unsigned long long)arg1 inIndexRange:(struct _NSRange)arg2;	// IMP=0x0000000000058175
- (id)_findFetchResponseWithMessageNumber:(unsigned long long)arg1;	// IMP=0x0000000000057fc4
- (BOOL)handleResponse:(id)arg1 forCommand:(id)arg2;	// IMP=0x0000000000057819
- (void)main;	// IMP=0x00000000000575a0
@property(readonly, copy) NSString *description;
- (id)initWithMailboxName:(id)arg1;	// IMP=0x00000000000573b1
- (id)initWithMessageNumbers:(id)arg1 useUIDsInstead:(BOOL)arg2 includeLabels:(BOOL)arg3 mailboxName:(id)arg4 delegate:(id)arg5;	// IMP=0x000000000005729d

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

