//
//     Generated by class-dump 3.5b1 (64 bit) (Debug version compiled Dec  3 2019 19:59:57).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IMAP/IMAPNetworkTaskOperation.h>

@protocol IMAPSelectMailboxOperationDelegate;

@interface IMAPSelectMailboxOperation : IMAPNetworkTaskOperation
{
    id <IMAPSelectMailboxOperationDelegate> _delegate;	// 8 = 0x8
}

@property(readonly, nonatomic) __weak id <IMAPSelectMailboxOperationDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;	// IMP=0x00000000000512da
- (void)main;	// IMP=0x00000000000510aa
- (id)initWithMailboxName:(id)arg1;	// IMP=0x0000000000050fdb
- (id)initWithMailboxName:(id)arg1 delegate:(id)arg2;	// IMP=0x0000000000050f50

@end

