//
//     Generated by class-dump 3.5b1 (64 bit) (Debug version compiled Dec  3 2019 19:59:57).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IMAP/IMAPNetworkTaskOperation.h>

@class IMAPDownloadCache, NSOrderedSet;
@protocol IMAPMessageDataSource, IMAPSyncBodiesOperationDelegate;

@interface IMAPSyncBodiesOperation : IMAPNetworkTaskOperation
{
    NSOrderedSet *_messages;	// 8 = 0x8
    id <IMAPMessageDataSource> _dataSource;	// 16 = 0x10
    id <IMAPSyncBodiesOperationDelegate> _delegate;	// 24 = 0x18
    IMAPDownloadCache *_downloadCache;	// 32 = 0x20
}

@property(retain, nonatomic) IMAPDownloadCache *downloadCache; // @synthesize downloadCache=_downloadCache;
@property(readonly, nonatomic) __weak id <IMAPSyncBodiesOperationDelegate> delegate; // @synthesize delegate=_delegate;
@property(readonly, nonatomic) id <IMAPMessageDataSource> dataSource; // @synthesize dataSource=_dataSource;
@property(readonly, copy, nonatomic) NSOrderedSet *messages; // @synthesize messages=_messages;
- (void).cxx_destruct;	// IMP=0x000000000005724c
- (void)main;	// IMP=0x0000000000056357
- (id)description;	// IMP=0x00000000000562bd
- (id)initWithMailboxName:(id)arg1;	// IMP=0x00000000000561ee
- (id)initWithMessages:(id)arg1 dataSource:(id)arg2 downloadCache:(id)arg3 delegate:(id)arg4;	// IMP=0x00000000000560cb

@end

