name: Build and Test

on:
  push:
    paths:
      - 'MailTrackerBlocker.xcodeproj/**'
      - 'Source/**'
      - 'Unit Tests/**'
  pull_request:

jobs:
  unit-test:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2
    - run: make test
    - uses: kishikawakatsumi/xcresulttool@v1.0.3
      with:
        path: TestResults.xcresult
