name: Build and Test

on:
  push:
    paths:
      - 'MailTrackerBlocker.xcodeproj/**'
      - 'Source/**'
      - 'Unit Tests/**'
  pull_request:

jobs:
  unit-test:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2
    - run: make test
    - uses: slidoapp/xcresulttool@v3.1.0
      with:
        path: TestResults.xcresult
      if: success() || failure()
      # ^ This is important because the action will be run
      # even if the test fails in the previous step.